### ISSUE TITLE
Upcoming release bug: ContentNode interface expects fields that some implementing types don't provide

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1116]
```
Interface field ContentNode.termNames expected but Page does not provide it.
Interface field ContentNode.termSlugs expected but Page does not provide it.
Interface field ContentNode.terms expected but Page does not provide it.
Interface field ContentNode.termNames expected but MediaItem does not provide it.
Interface field ContentNode.termSlugs expected but MediaItem does not provide it.
Interface field ContentNode.terms expected but MediaItem does not provide it.
```

**Comment by TylerBarnes** [comment]
This is resolved :)

**Comment by opr-inzn** [comment]
v7.7.0 returns
Missing onError handler for invocation 'extracting-queries', error was 'Error: Interface field WpConnectionType.nodes expected but WpEnqueuedScriptConnectionType
does not provide it.

Interface field WpConnectionType.nodes expected but WpEnqueuedStylesheetConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpActionMonitorActionConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpPluginConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpThemeConnectionType does not provide it.'. Stacktrace was 'Error: Interface field WpConnectionType.nodes
expected but WpEnqueuedScriptConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpEnqueuedStylesheetConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpActionMonitorActionConnectionType does not provide it.

Interface field WpConnectionType.nodes expected but WpPluginConnectionType does not provide it.

**Comment by TylerBarnes** [comment]
@opr-inzn see https://github.com/gatsbyjs/gatsby/issues/37729#issuecomment-1471124277

**Comment by maghaffar** [comment]
@jasonbahl I am getting this error when I upgrade from WPGraphql 1.6.0 to 1.24.0. But when I roll back to 1.6.0 the error is gone. I have tried multiple times and confirmed that this error is due to the new version. I was upgrading because I was getting the duplicate nodes fetched error when building my Gatsby site
![Screenshot from 2024-04-26 11-28-31](https://github.com/wp-graphql/wp-graphql/assets/98881071/c98e4bf3-3507-46a6-b91f-06ed42c9a6bc)
Upgrading WPGraphql to latest version resolved the issue, but now I am getting these two errors 
![Screenshot from 2024-04-26 11-03-31](https://github.com/wp-graphql/wp-graphql/assets/98881071/c230e540-50ef-441a-b539-c3c4663e895b)
![Screenshot from 2024-04-26 11-04-19](https://github.com/wp-graphql/wp-graphql/assets/98881071/a1e63022-67c1-49d3-a50f-73b8fb43129c)
Can you please provide a solution or guide me what to do now?

**Comment by maghaffar** [comment]
@jasonbahl The new version of WPGraphql exposed the following fields in schema
![Screenshot from 2024-04-26 12-57-47](https://github.com/wp-graphql/wp-graphql/assets/98881071/2f730292-7a02-4067-8767-240a3683b838)
But during build time it says cannot query these fields.
![Screenshot from 2024-04-26 13-03-39](https://github.com/wp-graphql/wp-graphql/assets/98881071/e4355a04-9035-4eae-87dd-e73326269eb6)
