### ISSUE TITLE
Have docs site pull extension docs from their repo README files

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1124]
The docs.wpgraphql.com site should pull the README from each extension as the content for the docs shown for that extension. This way, each extension can maintain their canonical docs in their repo and be reflected in the searchable docs site. 

Additional docs required for extensions should be maintained separately by said extension.

**Comment by jasonbahl** [comment]
My thought here is that in the Gatsby site that builds the docs site, we write up a script that pulls in the listed extensions (from a .yml or whatever) and pulls the content for each listed extension from the extension's REAMDE.md file

This _should_ be possible using something Gatsby Source GraphQL pointed at Github's GraphQL API.

I imagine we should be able to query the README info needed from that and create the pages? 

🤔

**Comment by moonmeister** [comment]
Are you interested in bringing packages in automatically at build time via a specific tag and querying the packagist API? If you'd like the manual control that's fine. 

The only possible issue I see with using GitHub as the source is the possible discontinuity of what's published to the package manager vs what's in the repository. Specifically if the master branch is ahead of production releases. If we can get the README.md from packagist it would guarantee the docs on the site match the latest release.

**Comment by renatonascalves** [comment]
I have a different take on this. I think the extensions area should have an organized section with basic information that should be available for each extension.

I, as new user and visitor of the doc, at a minimum, need to know:

* what this extension is (similar to the About section used)
* how it works
* and examples.

In my opinion, this shouldn't be a "marketplace" for extensions only with links to their respective sites/repos. But those that want to be added to the list should go to the trouble to write the minimum documentation necessary for the user to know how it works. Otherwise, we are doing a disservice for the users, considering not every extension owner will have the same care for their documentation.

--

About fetching the readme.md automatically from a package/repo: I'd be against that as we can't enforce any standard or what type of content that could be added from those extensions.

**Comment by moonmeister** [comment]
For what it's worth, this is never been a problem to my knowledge in the Gatsby community. Core plugins always have great docs. Popular non-core plugins maintain their docs and do a good job. 

Basically, poor docs, mean better solutions get built, or people come and help maintain and write better docs. Developers/Maintainers who don't write good docs and aren't active to accepting PRs wouldn't take the extra time to duplicate info and keep it up to date in both locations anyway, so it's mute. 

IMO this is a place to discover wpgraphl extensions(no matter what you call it. Instead of having to search google/bing/etc high and low for a solution, I should be able to come here and find a list of all/most available extensions,  If the project doesn't care to write good docs, I'll find one that does, role my own, or submit a PR.

Consistency is nice but reducing barrier to entry is paramount to making this list truly helpful. If I can't trust this list to have all/most of the best plugins, I won't come here (I can't trust it to have that currently). Gatsby does just that, there's a bunch of crap, and forks in gatsby's plugin page, and that is okay, because I know there is a lot of good stuff too.  By making time strapped maintainers do extra work we raise the barrier to entry and they just won't put plugins here and people won't be able to trust this list as a reliable source for the all their wpgraphql extension needs.

**Comment by jasonbahl** [comment]
@renatonascalves, @moonmeister beat me to it. I agree with his sentiments. We can always help folks improve their docs, and even provide recommendations, but I think the bigger need right now is surfacing what exists in some fashion to lower the barrier to entry for the WPGraphQL community at large. 

I think as extensions start surfacing, we could contribute to their quality by pointing folks to a guide (yet to be written) about our recommendations for what to include in an extension plugin README, or contribute to their READMEs directly as well.

**Comment by jasonbahl** [comment]
> Are you interested in bringing packages in automatically at build time via a specific tag and querying the packagist API? If you'd like the manual control that's fine.

@moonmeister I hadn't thought about pulling from packagist 🤔. They, as far as I know, typically pull from Github though, eh? I suppose they could be from Gitlabl or Bitbucket or elsewhere too though, so perhaps pulling info from Packagist is actually the best. 

I just thought Github initially because I'm familiar with the Github GraphQL API and pulling data in through Gatsby and Gatsby Source GraphQL seemed like a quick win.

I'd have to look into the Packagist API and what's available, but that sounds like a good option.

**Comment by jasonbahl** [comment]
here's a link to the packagist API docs: https://packagist.org/apidoc

Here's a GET request searching for `wp-graphql` through their API: https://packagist.org/search.json?q=wp-graphql

**Comment by jasonbahl** [comment]
extensions have been listed on the website for quite some time. closing this issue.
