### ISSUE TITLE
Not possible to query a user from a comment?

### ISSUE THREAD

**Issue by jkhaui** [wp-graphql/wp-graphql#1139]
Hi,
Maybe I'm missing something, but is it really not possible to traverse a `user` node from a `comment` node? I.e. when retrieving data for a post, I thought it'd be logical to also retrieve all comments for that post, and for each comment, if the comment's author is a registered user, at minimum you'd naturally want to at least display their username too.

As far as I can see one can only query whether the comment's author was of type User or not a registered user. I love everything else about the plugin but find this quite strange. The most obvious use-case (IMO) for headless WP is to create apps with highly relational data between user interactions - social network style - and associating a comment with a user is an essential feature in achieving this

**Comment by jasonbahl** [comment]
@jkhaui Thanks for using WPGraphQL! 🙌 

You can query posts, the post's comments and the author of the comment, and then keep traversing connections the author has with other content, such as Posts, etc. 

Here's an example query:

```
{
	post(id:"cG9zdDoxMjg4") {
    id
    title
    comments {
      nodes {
        id
        content
        author {
          __typename
          ...on CommentAuthor {
            name
          }
          ...on User {
            firstName
            lastName
          }
        }
      }
    }
  }
}
```

And here's a screenshot of it in action with the results:

![Screen Shot 2020-01-31 at 8 45 21 AM](https://user-images.githubusercontent.com/1260765/73552760-0bff6180-4406-11ea-917b-40dbcbec4758.png)

My guess is that when you got to the `comment.author` field, since it returns a `CommentAuthorUnion`, perhaps that tripped you up? 

The reason it returns a Union, is because some authors are guest authors and some are users. The shape of data you can ask for from a Guest Author is different than what you can ask for if the author is a user. 

This is where this portion of the query kicks in: 

```
 ...on CommentAuthor {
  name
}
...on User {
  firstName
  lastName
}
```

This syntax in GraphQL allows us to query fields of Unions. This is telling GraphQL: "Hey, I don't know what type of user the comment author is, but if it turns out it's a User, I want the firstName and lastName, but if it turns out it's a CommentAuthor (not a user), I want just the name"

This feature of GraphQL allows our applications to have predictable results, even in situations that are commonly unpredictable. 

I hope this answers your question and gets you headed in a direction that allows you to build what you're looking to build.

**Comment by jkhaui** [comment]
@jasonbahl Thank you so much for the great example. I just tried using your example provided. I think I understand your explanation, but the problem is now that even when the comment was made by a **user**, the WP GraphQL query is still returning the comment as if it were made by a `CommentAuthor` (i.e. not a registered WP user).

Please see the image below as reference. Here, the comment by `Bob Smith` represents a comment made by a r**egistered WP user** with the first and last name Bob Smith. However, the query is treating it as if it were made by a **non-registered user?** 🤔

![image](https://misc-4.s3-ap-southeast-1.amazonaws.com/wp-graphql-comments.png)
