### ISSUE TITLE
Wordpress filter post_type_link doesn't work in gatsby and wp-graphql environment

### ISSUE THREAD

**Issue by taylorchance** [wp-graphql/wp-graphql#1143]
This issue is basically occurring in my functions.php, not necessarily on the front end part of things, but I have no idea why it's not working other than the different environment. I have tried the exact same code in another wordpress project and its working fine.

Basically my end goal is that I need to have nested URL's based off the slug of another associated post, which is a relational post object chosen in ACF. So basically my link would be "chosen-parent-slug/my-page-slug". I've successfully done this on the front end and gatsby side when I create the pages, but now I need to update the wordpress post links. (unless there is somehow some way to change that on the front end side???)

Here is my code:

```php
function filter_the_post_type_link( $post_link, $post ) {
	switch( $post->post_type ) {
	  case 'CaseStudy':
		   $post_link = get_bloginfo( 'url' );
			  $parent = 'test-string';
			  $post_link .= "/{$parent}/";
			  $post_link .= "$post->post_name";
	  break;
	}
	return $post_link;
}
add_filter( 'post_type_link', 'filter_the_post_type_link', 1, 2 );
```

and the rewrite for my custom post type:
```php
register_post_type( 'CaseStudy', [
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_menu' => 'template-pages',
		'supports' => array( 'title', 'editor', 'revisions', 'slug'),
		'labels'  => [
			'name' => __( 'Case Studies' ),
			'menu_name' => __( 'Case Studies' ),
		],
		'show_in_graphql' => true,
		'hierarchical' => false,
		'menu_icon' => 'dashicons-media-default',
		'graphql_single_name' => 'CaseStudy',
		'graphql_plural_name' => 'CaseStudyPages',
		'rewrite' => array( 
			'slug'          => '/',
			'with_front'    => false 
		),
	 ] );
```

The end goal here for this test scenario is to have the page link be "test-string/my-page-slug" but the test-string isn't working in this instance. Does anybody have any clue why it wouldn't work here?

**Comment by jasonbahl** [comment]
@taylorchance Apologies for how long it's taken to try and reproduce this and get a response. 

I looked into this and it doesn't appear to be a bug with WPGraphQL. 

It looks like when you register a post type as `CaseStudy`, WordPress lowercases the post_type when saving to the database. 

So, in the database the post_type is `casestudy` and not `CaseStudy`. 

This means, in your `post_type_link` filter callback, the switch statement never evaluates true for `case 'CaseStudy':`, because the post_type of the post is `casestudy`. 

If you change your switch statement to `case 'casestudy':` it should work. 

I'd recommend also sticking with the convention of registering your post types with lowercase letters, as suggested in the WordPress core documentation here: https://developer.wordpress.org/reference/functions/register_post_type/#parameters
