### ISSUE TITLE
Provide query to fetch super admins in multisite

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1175]
In PHP, it's possible to get a list of logins for the super admins on the current site in the network by calling `get_super_admins()`. It's often useful to pipe this list directly into a users query to include or exclude super admins, like this:

```php
$non_superadmin_user_query = new WP_User_Query( [
    'login__not_in' => get_super_admins(),
] );
```

I propose that we provide a way in WPGraphQL to query for the super admins on the current site in multisite.

One option would be to add a new root-level query to the schema for getting super admin users (similar to WP's `get_super_admins()` function, but with user objects in the response), but that seems a bit redundant to me, since we already have a `users` query whose purpose is to query for users.

I think the better approach would be to modify the `users` WPGraphQL query so that it's possible to do these things in multisite:

- Query for super admin users only
- Query for super admins, along with other users
- Query only for other users, excluding super admins

I'd love to hear some feedback on what folks think is the best approach.

### Plugin Version
WPGraphQL version: 0.7.0

**Comment by jasonbahl** [comment]
@kellenmace if SuperAdmins are users, I feel like we could probably include them in the regular Users query and do proper cap checks to make sure we only query for and return them to users that have access to see them. 

To me it seems like `get_super_admins()` could be simillar to: 

```graphql
{
  users( where: { roleIn: [ SUPER_ADMIN ] } ) {
     nodes {
        id
        username
     }
  }
}
```

**Comment by jasonbahl** [comment]
If `SUPER_ADMIN` isn't currently an option for the `roleIn` field, we likely need to address the ENUM that shows the roles to have better support for multisite?

**Comment by justlevine** [comment]
A screenshot from a fresh multisite instance with v1.8.0. Should be easy to add `SUPER_ADMIN` as an enum value.
![image](https://user-images.githubusercontent.com/29322304/165838846-d068294d-a56f-4d1a-a298-68f54189e855.png)

**Comment by jasonbahl** [comment]
What are the use cases for this? 

If one were able to filter a list of super admins via GraphQL, what would the utility of this be?

Since there's not really full "network" support for multisite in WPGraphQL, I'm curious what the utility of this is. 

I'm inclined to leave this as plugin territory for now. If/When #259 is considered for WPGraphQL core, we could maybe consider this feature in relation to that?

I'm going to close this for now. 

For anyone who does need this functionality, you could make use of the following actions/filters: 

### Filter the Enum Values

- https://github.com/wp-graphql/wp-graphql/blob/v1.16.0/src/Type/WPEnumType.php#L83
- example (untested): 

```php
add_filter( 'graphql_UserRoleEnum_values', function( $values ) {
  $values['SUPER_ADMIN'] = [
	'description' => __( 'Super Admin', 'wp-graphql' ),
	'value'       => 'super_admin',
  ];
  return $values;
};
```

### Filter how the Enum impacts the query

```php
add_filter( 'graphql_connection_query_args', function( $query_args, \WPGraphQL\Data\Connection\AbstractConnectionResolver $connection, $input_args ) {

	if ( ! $connection instanceof \WPGraphQL\Data\Connection\UserConnectionResolver ) {
		return $query_args;
	}

	if ( isset( $input_args['where']['roleIn'] ) && in_array( 'super_admin', $input_args['where']['roleIn'], true ) ) {
		$super_admins = get_super_admins();
		if ( false !== ( $index = array_search( 'super_admin', $query_args['role__in'], true ) ) ) {
			unset(  $query_args['role__in'][ $index ] );
		}
		$query_args['login__in'] = $super_admins;
	}

	if ( isset( $input_args['where']['roleNotIn'] ) && in_array( 'super_admin', $input_args['where']['roleNotIn'], true ) ) {
		$super_admins = get_super_admins();
		if ( false !== ( $index = array_search( 'super_admin', $query_args['role__not_in'], true ) ) ) {
			unset(  $query_args['role__not_in'][ $index ] );
		}

		$query_args['login__not_in'] = $super_admins;
	}


	return $query_args;

}, 10, 3 );
```

----

Here's the problem with the above, however:

If we query for `roleNotIn`, things work decent. 

Querying for `roleIn` is much trickier. 

Since "Super Admin" is not a role WP_User_Query can handle, we have to unset it from the `role__in` that is sent as an arg to WP_User_Query, but, if we also populate `login__in` with super admin IDs, like we do in the snippet above, it becomes impossible to query by `role__in`. 

for example: 

```php
{
  contributorsAndSuperAdmins: users(where: {roleIn: [SUPER_ADMIN, CONTRIBUTOR]}) {
    nodes {
      id
      name
      roles {
        nodes {
          name
        }
      }
    }
  }
}
```

Given the snippet above, this would translate to the following args passed to WP_User_Query: 

```json
{
    "count_total": false,
    "graphql_args": {
      "where": {
        "roleIn": [
          "super_admin",
          "contributor"
        ]
      }
    },
    "graphql_cursor_compare": "<",
    "graphql_after_cursor": null,
    "graphql_before_cursor": null,
    "number": 11,
    "role__in": {
      "1": "contributor"
    },
    "fields": "ID",
    "order": "ASC",
    "login__in": [
      "jasonbahl"
    ]
  }
```

Since we've filtered by `login__in` AND `role__in` we will end up with zero results, because the super admin (login__in) is not a contributor, and contributors are not going to be in the login__in list (super admins). 

It becomes super tricky to resolve this, and support things like pagination.

**Comment by jasonbahl** [comment]
I'm going to close this issue and recommend that it be solved in an extension plugin/snippet to start. 

If someone has some good use cases for this functionality, can demonstrate use cases, AND wants to solve it in a plugin or snippet, then we could consider it for WPGraphQL core if/when we come back to #259
