### ISSUE TITLE
Feature Request: deleteComment - add an option to remove all children/replies

### ISSUE THREAD

**Issue by holyblast** [wp-graphql/wp-graphql#1177]
Currently the deleteComment mutation has the following input fields:
**clientMutationId**, **id**, **forceDelete**.

if you decide to delete a comment, that is a direct comment to the post.
the children will become directly connected to the post as well, because of the removal of the parentId.

Rather than calling graphql query to delete all children one by one.
i thought it might be better to do it through 1 call by adding another boolean check to the mutation, for example **deleteChildren**.

**Comment by hsimah** [comment]
We are going to be implementing comments in our app soon, and this seems like a useful feature for dealing with trolling etc. If this is something that we should do - recursive deletion of comments, then I would be happy to do up a PR for it.

**Comment by jasonbahl** [comment]
The default behavior of WordPress when a Comment is deleted is to delete the individual comment and move the children (replies) up, but not delete them: 

https://developer.wordpress.org/reference/functions/wp_delete_comment/#source

This is the behavior of the WP REST API as well, as it calls `wp_delee_comment`: 

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-comments-controller.php#L949-L1025

I think if we were to add a mutation to delete a comment and it's children, it _might_ be good to offer it as a different mutation altogether, because the payload that you might ask for in response might be different that what you might ask for in response to a singular `deleteComment` mutation. 

I would suggest working on a new mutation as a plugin, since it's a departure of core WP functionality, and we can discuss it for merge into core WPGraphQL once it's a working plugin?
