### ISSUE TITLE
featured image additional information (Longitude & Latitude) SEO Citation concern

### ISSUE THREAD

**Issue by rayjencode** [wp-graphql/wp-graphql#1184]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://wpgql-slack.herokuapp.com/)).

Just want to request additional information for to fetching the Longitude and Latitude in featured image. This is one of the important of Local SEO citation. 

Thanks

**Comment by jasonbahl** [comment]
@rayjencode is the latitude and longitude of images a core field or do you manage those fields via plugin?

**Comment by rayjencode** [comment]
Hello @jasonbahl it's a premium plugin "Project Supremacy EXIF"

**Comment by izzygld** [comment]
Don't see why this should be in wp-graghql? (it's not in the wordpress core)

it should be a separate plugin wp-graghql-seo?

**Comment by jasonbahl** [comment]
Since this data is not managed by WordPress, WPGraphQL won't be adding support for this. 

I'd suggest reaching out the the authors of "Project Supremacy EXIF" and see if they could expose their data for their plugin in the WPGraphQL Schema. 

If not, you can use the `register_graphql_field()` and `register_graphql_object_type()` methods to register custom Fields and Types to the WPGraphQL Schema. 

Here's a video where we walk through this process: https://www.youtube.com/watch?v=afEKFwGUiyE&t=205
