### ISSUE TITLE
wrong link in 0.8.0 release changelog guide

### ISSUE THREAD

**Issue by a-barbieri** [wp-graphql/wp-graphql#1221]
In release 0.8.0 the following links lead to empty comparison, no line of code is there to be seen...

>New Features
  ...
    Remove resolveNode config arg from most connections registered by the core plugin as the new method for resolving connections doesn't wait until the last second to resolve nodes
        For example: https://github.com/wp-graphql/wp-graphql/compare/master...release/next?expand=1#diff-a04db7b019ce5a16e141cd35799a0718L19-L21, https://github.com/wp-graphql/wp-graphql/compare/master...release/next?expand=1#diff-0b5f575771fc27faf7455a8fa0a05d93L79-L81

**Comment by a-barbieri** [comment]
Same goes for all the other ones in the changelog.

**Comment by CodeProKid** [comment]
Ah yeah they do lead to empty comparisons. I think this is because @jasonbahl creates these links before he cuts the release, and then once he cuts the release `master` and the next release are the same. Probably just need to be a little more explicit in the compare to use the current version and the next release version.

**Comment by jasonbahl** [comment]
Updated the links. Ya, I'll do my best to use the SHA compares in the future. 

Thanks!
