### ISSUE TITLE
Question: Are graphql_single_name and graphql_plural_name optional, if not can they be?

### ISSUE THREAD

**Issue by davidshq** [wp-graphql/wp-graphql#1306]
Setting up graphql for a custom post type following the directions here.

Document indicates that setting graphql_single_name and graphql_plural_name is required. Wondering if this is strictly true and if so why? Seems like WPGraphQL could (by default) pull from the singular and plural labels of the CPT and allow an overwrite using above two if necessary?

Not a huge issue, more curious than anything.

(btw, I'm on the top of my game atm, originally submitted the q under the wrong account in the wrong repo!)

**Comment by jasonbahl** [comment]
@davidshq the `graphql_single_name` and `graphql_plural_name` are required because they should **not** be translated strings like labels on Custom Post Types are. 

Labels are translated, so that when working in the admin you can read the string in the language the locale is set to. 

Schema names should not be translated as each client would then have a completely different Schema based on the locale.
