### ISSUE TITLE
Posts Query with hasPassword should default to false

### ISSUE THREAD

**Issue by jonshipman** [wp-graphql/wp-graphql#1338]
Test case:
Have several posts in WordPress, at least one should be Password Protected and published.
Run the following query:
```
query {
  posts(first: 5, where: {status: PUBLISH}) {
    nodes {
      uri
    }
  }
}
```
If the password protected post is in the first 5, you'll get an Internal error. The error from graphql is "Cannot return null for non-nullable field Post.uri." Run the same query as:
```
query {
  posts(first: 5, where: {status: PUBLISH, hasPassword: false}) {
    nodes {
      uri
    }
  }
}
```
And you'll be greeted with success.

I propose that the default should be hasPassword: false without the need to specify in the query. Should the developer want password posts, they should pass hasPassword: true.

**Comment by jasonbahl** [comment]
@jonshipman Core WordPress makes this attribute public, as in, I can see a PW protected post on the homepage or archive and the permalink will take me to the single page for it, so WPGraphQL should follow suit. 

If I publish a PW protected post, it will show in my blogroll in core WP. 

![Screen Shot 2020-06-05 at 7 59 21 AM](https://user-images.githubusercontent.com/1260765/83884755-9e8c7600-a702-11ea-9001-c1e11595993a.png)

I think what needs to happen is that we need to make the `uri` an allowed restricted field in the Post Model. That should get rid of the bug here.

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Post.php#L127-L137

**Comment by jasonbahl** [comment]
@jonshipman PR here to address this: https://github.com/wp-graphql/wp-graphql/pull/1344
