### ISSUE TITLE
Querying Comment.databaseId returns errors and "null" response

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1437]
Querying for 

```graphql
query {
  comments {
    nodes {
      databaseId
    }
  }
}
```

Returns:

```json
{
  "errors": [
    {
      "debugMessage": "Cannot return null for non-nullable field Comment.databaseId.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "comments",
        "nodes",
        0,
        "databaseId"
      ]
    }
  ],
  "data": {
    "comments": {
      "nodes": [
        null
      ]
    }
  }
}
```

**Comment by TylerBarnes** [comment]
This is on v0.12.1 btw

**Comment by jasonbahl** [comment]
👀

**Comment by jacobarriola** [comment]
I am able to reproduce this as well - v.12.0 + WooGraphQL.

This only happens when trying to run a query outside of wp-graphiql (not authenticated) - works fine when querying inside of WordPress (authenticated).

Attempts to fix:
* added `commentType: "review"` to `where` clause of query, since WooCommerce saves order notes as comments. My guess was that there was some auth issues happening.
* added `databaseId` to the `excludedFields` array for `Comment` type in the gatsby config file, but that made my build fail with this message:
```
Missing onError handler for invocation 'extracting-queries', error was 'Error: Type WpDatabaseIdentifier must define one or more fields.'. Stacktrace was 'Error: Type WpDatabaseIdentifier must define one or more fields.
```

**Comment by jasonbahl** [comment]
I was able to reproduce this.
