### ISSUE TITLE
Query pages showing children with same level as Parent

### ISSUE THREAD

**Issue by schbudy** [wp-graphql/wp-graphql#1547]
I'm using WP Graphql Version 0.13.3
when I run query below, the result showing child page include in same level as parent
The Query
```
query MyQuery {
  pages {
    nodes {
      title
      id
      children {
        nodes {
          id
          uri
          slug
        }
      }
      parentId
    }
  }
}
```
Result:
```
{
  "data": {
    "pages": {
      "nodes": [
        {
          "title": "child page",
          "id": "cG9zdDo4OA==",
          "children": {
            "nodes": []
          },
          "parentId": "cG9zdDoy"
        },
        {
          "title": "Home App",
          "id": "cG9zdDoy",
          "children": {
            "nodes": [
              {
                "id": "cG9zdDo4OA==",
                "uri": "/home-app/child-page/",
                "slug": "child-page"
              }
            ]
          },
          "parentId": null
        }
      ]
    }
  }
}
```
I have try it with all plugins disabled except wp graphql and using default themes Twenty eleven and still same result

**Comment by jasonbahl** [comment]
@schbudy Hello!

Thanks for checking out WPGraphQL! 

This behavior is intentional. Hierarchical content is returned as a flat list by default. You can use a function like the one documented [here](https://docs.wpgraphql.com/getting-started/menus/#converting-a-flat-list-to-hierarchical-list) to convert a flat list to hierarchical on the client. 

Or, if you prefer to query as a hierarchy in GraphQL, you can specify that you want pages where the `parentId: 0`, like so: 

```graphql
{
  pages(where:{parent:0}) {
    nodes {
      id
      title
      uri
      parentId
    }
  }
}
```

That will return just pages with no parent, then you could use the `children` field as you are to get the children.
