### ISSUE TITLE
Upgrade from 13.3 to 15.3 breaks Gatsby site

### ISSUE THREAD

**Issue by mikeriley131** [wp-graphql/wp-graphql#1581]
I'm using WPGraphQL with Gatsby and have been on v13.3 until my host just auto-updated to 15.3. This caused an error where it `Cannot not query field neueamsterdam on type "Query"`. `neueamsterdam` being the `fieldName` I set in the `gatsby-source-graphql` plugin in `gatsby-config.js`

```
{
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'NeueAmsterdam',
        fieldName: 'neueamsterdam',
        url: 'https://admin.neueamsterdam.com/graphql',
        refetchInterval: 30,
      },
    },
```

I searched around and could not find any instruction on what I needed to change to get my site to work with 15.3.
Any help would be greatly appreciated.
Thanks.

**Comment by jasonbahl** [comment]
@mikeriley131 I would recommend using `gatsby-source-wordpress-experimental` if you can, as that's the official plugin Gatsby will be supporting long-term for using WordPress as a source for Gatsby. 

That said, I'd love to help you figure out how to use `gatsby-source-graphql` with the latest versions of WPGraphQL.

The updates from v0.13.3 to v0.15.3 are pretty minor, so I'm not sure that it's actually an issue with WPGraphQL. 

I would recommend running `gatsby clean` to clear all Gatsby caches, and then run `gatsby develop` again. 

The error `Cannot not query field neueamsterdam on type "Query"` makes it seem like `gatsby-source-graphql` wasn't able to properly stitch the Schema. Possibly because the Schema had changed on your WordPress server but an old Schema was still cached in Gatsby. 

If `gatsby clean` doesn't fix things for you, can you provide a repository where we can easily reproduce this error?

**Comment by mikeriley131** [comment]
Thanks Jason.
I did try `gatsby clean` and then `gatsby develop` (a few times) with no luck.
Hitting https://admin.neueamsterdam.com/graphql was still successful even though the query was broken.
I had not made any updates to WP other than the plugin update when the error occurred.
Maybe something else changed during the update but simlply reverting to v13.3 fixed the issue.
I'll see if I can make time tomorrow to create a repo that reproduces the error.

If I switch to `gatsby-source-wordpress-experimental`, does that replace `gatsby-source-graphql`?

**Comment by jasonbahl** [comment]
@mikeriley131 `gatsby-source-wordpress-experimental` would replace your need for using `gatsby-source-graphql`. 

It's getting close to moving out of the "experimental" phase too. I think you'll find the experience using it much better than using `gatsby-source-graphql`. 

I just re-launched [WPGraphQL.com](https://www.wpgraphql.com) today using `gatsby-source-wordpress-experimental` and WPGraphQL v0.15.3, and it's been a blast to build. 

You can check out the repo for the site here to peak under the hood: https://github.com/wp-graphql/wpgraphql.com

I'll be writing some content in the coming weeks detailing how various parts of the site were built as well.

**Comment by jasonbahl** [comment]
@mikeriley131 I created a starter CodeSandbox pointed at your API. This could be a good start to troubleshoot if you update to v0.15.3 again. You might consider setting up a staging WordPress site with v0.15.3 that we can point the CodeSandbox app and see if we can all get on the same page and replicate the error. 

https://codesandbox.io/s/gatsby-starter-default-forked-zp1oq?file=/gatsby-node.js

**Comment by mikeriley131** [comment]
@jasonbahl I've just updated to v0.15.3, ran `gatsby clean` and then `gatsby develop` and am getting `Cannot query field "neueamsterdam" on type "Query".` again.

**Comment by jasonbahl** [comment]
@mikeriley131 ah shoot. I should have remembered. 

GraphQL Introspection is disabled by default from v0.14.0, and must be enabled via the WPGraphQL Settings. 

See the release notes here: https://github.com/wp-graphql/wp-graphql/releases/tag/v0.14.0

**Comment by mikeriley131** [comment]
@jasonbahl Well that was a super simple fix. Thanks!
