### ISSUE TITLE
Return plain text content related fields

### ISSUE THREAD

**Issue by duffn** [wp-graphql/wp-graphql#160]
I'd like wp-graphql to return content related post fields, i.e. `content`, `excerpt`, that are plain text only without HTML tags. I'm specifically requesting fields in addition to the already available fields - `contentRaw`, `excerptRaw` for instance.

These would be helpful for developers using wp-graphql that are building mobile apps or spoken language apps that are only looking for the plain text related fields of a post.

**Comment by jasonbahl** [comment]
My thought, at the moment, would be to either add an argument to the fields that would simply prepare the results of the field differently. 

For example: 

```
post(id:"..."){
  id
  content
  rawContent:content(outputFilters:[RAW])
}
```
Having an argument like `outputFilters` which would accept a list of filters (possibly an enum of available filters) to apply would allow for the consumer to have the response prepared for their needs without having to introduce new "fields" to the schema. 

This could be pretty powerful. 

We could have filters like "raw" that strip all markup, shortcodes, etc. 

We could also have filters that just strip markup, filters that just strip shortcodes, etc. 

So you could potentially do: 

```
post(id:"..."){
  id
  content
  contentWithoutShortcodes:content(outputFilters:[STRIP_SHORTCODES])
  contentWithoutHtmlTags:content(outputFilters:[STRIP_TAGS])
  contentWithoutHtmlTagsOrShortCodes:content(outputFilters:[STRIP_TAGS, STRIP_SHORTCODES])
}
```
Need to explore this more, but this could be a very valuable feature indeed.

**Comment by jasonbahl** [comment]
@jaredcobb, also curious to get your thoughts on this as you've had to do your fair share of transformation of `the_content` and `excerpt`, etc for making it useful in various contexts (a.k.a. syndication, REST, etc)

**Comment by keg** [comment]
@jasonbahl I think what you're suggesting makes sense with strip tag and strip shortcodes filters. Would `STRIP_TAGS` strip media too? The only other transformation that I've regularly hit is encoding, smart quotes etc. Also FWIW I'd make the default return type as close as possible to what is stored in the database.

**Comment by jasonbahl** [comment]
@keg so the default output should be just the results of `$post->post_content` which would include raw shortcodes, etc? 

I think in _most_ places in WordPress, the expectation for "content" is the result of `$post->post_content` with `the_content` filter applied, which converts shortcodes to their rendered output, and includes any other "things" that have been added by other plugins and theme code.

But, I could definitely get down with the default being the data from the DB as-is, and any transformations, such as `apply_filters( 'the_content', $post->post_content )` be something that you the consumer ask for via an argument, like `content(outputFilters:[THE_CONTENT])` or something to that tune?

So default `content` might output something like: 

```
Hello

[some_shortcode]
``` 
And: 

`content(outputFilters:[THE_CONTENT])`

Might output: 

```
Hello

<div id="some_shortcode_id">The rendered markup for some shortcode</div>
```

**Comment by jasonbahl** [comment]
And the array of filters could get applied to `$post->post_content` in the order they're passed to the argument. 

So the consumer could compose the results for their needs, by passing various filters in the order they want them applied. . .and of course custom filters could be registered as well. 

I'm really liking this concept! 

Does the name: `outputFilters` make sense? we could change it to simply `applyFilters` as well, make it a convention that we can apply to other fields over time.

**Comment by jasonbahl** [comment]
So, I'm thinking my concept of applying multiple filters is the right idea, but I totally forgot GraphQL has a spec for this kind of thing, called directives, a powerful feature we haven't taken advantage of at all yet. (http://graphql.org/learn/queries/#directives)

You can see a JS package for graphql-js that provides a series of custom directives here (some of which might be good to implement in our codebase) to get an idea of what can be done with directives: https://www.npmjs.com/package/graphql-custom-directives

**Comment by jasonbahl** [comment]
@kozlowskij I think this is a good conversation for you to provide some input on, as I think your team would use this feature a lot, however it's implemented.

**Comment by jaredcobb** [comment]
@jasonbahl I agree with the approach and directives look like a great way to go.

My 2 cents on what I'd expect the _default_ `content` to return is that it would be the fully rendered content. I find that most sites process content via their own `the_content` filter callbacks (sometimes just minor tweaks, other times major business logic).

What about a `@raw` directive?

```
post(id:"..."){
  id
  content
  contentRaw:content @raw
  contentWithoutShortcodes:content @stripShortcodes
  contentWithoutHtmlTags:content @stripTags
  contentWithoutHtmlTagsOrShortCodes:content @stripTags @stripShortcodes
}
```

Just to ensure we're saying the same thing. I'm defining "raw" as what you'd see directly in the database. And "rendered" is the final output after `the_content` filter has run.

Semi related, as a consumer if I request the content with some combination of directives, I'd expect the directives to apply in a specific order. For example, with `@stripTags @stripShortcodes` I would expect `@stripShortcodes` to always be processed before `@stripTags`.

**Comment by jasonbahl** [comment]
@jaredcobb thanks for the feedback! I'm pretty sure directives will get applied in the order they're passed, but if that's not a built-in feature of GraphQL, I'll make sure we make that a standard at least for WPGraphQL, because I agree that as a consumer, if I passed multiple directives I'd want them processed in the same order I passed them.

**Comment by jaredcobb** [comment]
@jasonbahl Even better! I'm not familiar enough with directives but if the consumer controls the processing order that's great.

**Comment by duffn** [comment]
> With directives, the same query I mentioned above with various args would turn into something like:

This would be excellent.

**Comment by kozlowskij** [comment]
For mobile apps, the biggest pain points come from matching and stripping out the following "assets" from ```content```:

1. Videos. Inform code for example.
2. Article slideshows/galleries.
3. Images wrapped in ```<figure>``` tags (not sure how common these are anymore). 

We then render those assets in predetermined positions in app articles.

Basically, we'd like to see some approach that allows us to query for ```content``` that contains only textual data. HTML wrapping the text is actually fairly useful as it allows us to style headings, etc. (we might not necessarily strip tags, but good to know we could). Beyond that, it's important that there'd then be mobile-specific queries that contain the assets that were in the desktop version of the ```content```, i.e. video and galleries. Otherwise, we're going to continue to need to use middleware for data processing, or use an entirely different approach for rendering content in app articles.

@jasonbahl, let me know if this makes sense and if you need anything more specific, and also if you have some ideas for us. Thanks.

**Comment by jasonbahl** [comment]
Ok, so. . .just wanted to point out that `directives` are not how we'll want to implement this. . .we'll want to implement with `$args` still. 

Args affect the resolving of fields, where directives apply after the field is resolved, so in our case we're trying to have WordPress resolve the field with certain filters applied or not applied, etc. . .which happens in the resolver process, meaning directives would be too late. 

So I think the plan of passing a list of filters to apply as an argument should work, and to @jaredcobb's point, the filters should be applied in the order the args are added. 

so:

```
post() {
   content(filters:[STRIP_SHORTCODES,STRIP_TAGS])
}
```

Would resolve something to this tune: 

```
$content = $post->post_content;
$content = strip_shortcodes( $content );
$content = wp_strip_all_tags( $content );
```
And: 

```
post() {
   content(filters:[STRIP_TAGS,STRIP_SHORTCODES])
}
```

Would resolve something to this tune: 

```
$content = $post->post_content;
$content = wp_strip_all_tags( $content );
$content = strip_shortcodes( $content );
```

I think we should explore a bit more what filters/functions, etc should be allowed, and what the defaults should be if no `$args` are passed.

**Comment by chriszarate** [comment]
Hi! Thanks for this discussion! Thought I'd chime in with what we see as ideal for our purposes. My comment assumes @jasonbahl's last comment directly above is the latest thinking.

In that last comment, I'm interpreting the mapping between "filters" and functions to be an internal, inflexible mapping, e.g., `STRIP_TAGS => wp_strip_all_tags`. I like the idea (function-mapping?), but it seems like you'd receive an endless stream of requests to provide additional mappings for this or that pet use case.

If I'm understanding correctly, I think I'd prefer [this earlier suggestion](https://github.com/wp-graphql/wp-graphql/issues/160#issuecomment-315382732) where the filters mapped implicitly to the argument passed to `apply_filters`. In other words, this query:

```
post() {
   content(filters:[THE_CONTENT, MY_GQL_CONTENT_FILTER])
}
```

would map to:

```
$content = $post->post_content;
$content = apply_filters( 'the_content', $content );
$content = apply_filters( 'my_gql_content_filter', $content );
```

We are then free to provide our own filters to strip tags and/or shortcodes. A hybrid approach could also work, but I would worry about collisions between built-in mappings and custom filters, and the confusion it could cause.

Our use case is wanting something somewhere in between the "raw" `$post->post_content` value and `apply_filters( 'the_content', $post->post_content )`. Via a custom filter, for example, we could apply `wptexturize` and `wpautop` but not `autoembed` and `do_shortcode`. This lines up with our desire to let basic and intentional markup stand (links, emphasis, blockquotes, p, heads, etc.) while implementing "macro"-type transformations (embeds, shortcodes) on the consuming application side. While this is a bit of a half-measure towards structured content, it feels like a good dividing line for us. (Happy to entertain counterpoints to this approach in Slack.) Achieving this via the "function-mapping" approach would require a queue of requests for additional mappings.

Finally just a note about the current behavior that could affect future implementations. Since the resolver is not called inside the loop, certain filters that rely on `global $post` (e.g., `autoembed`) do not work. I'll submit a PR to get this fixed later today.

**Comment by CodeProKid** [comment]
I agree that a consumer should definitely have a filtered & non-filtered option. I think this should apply to every single resolver though, and then the consumer can choose which to retrieve on a field by field basis by passing an argument.

The tricky part comes in with *which* filters should be applied to the content. I feel like we should only be responsible for filtered/unfiltered content, and then let the person consuming be responsible for anything beyond that.

Maybe we can just add a generic filter to each of the resolvers, and attach some of the core filters to them as we see fit. So something like this:
```php
$resolved_data = apply_filters( 'wpgql_content_resolver', $data, $context );
```
and then somewhere in the plugin, run some of core's filters over that data depending on the data, like so:
```php
add_filter( 'wpgql_content_resolver', 'wpgql_apply_content_resolver_filter' );
function wpgql_apply_content_resolver_filter( $data ) {
    return apply_filters( 'the_content', $data );
}
```
Then, someone could manipulate the data the way they want within the `wpgql_content_resolver` filter, and even remove the `the_content` filter with `remove_filter()`. We could also potentially pass the args as `$context` and people could create their own arguments to have finer control over which filters to run.

Overall I think providing anything beyond "raw" and "rendered" is beyond the scope of what this plugin should do. I just don't see a great way to give widespread fine tuned controls over what filters run over the data on a resolver by resolver basis. I feel like this will only lead to a fragmented and inconsistent experience for the consumer since there's know way we will be able to offer the same level of controls for each field.

**Comment by jasonbahl** [comment]
Adding my comment from Slack here for context:

====

Ideally, I'd like the Schema in general to be non-WordPress-y, if you know what I mean

Overall, the consumer shouldn't have any idea what the underlying tech is, they should just be able to declare _what_ they want, not _how_ to get what they want.

This allows for the Schema to resolve data from WordPress, ElasticSearch, 3rd party APIs, etc. . .

The Relay Spec does a pretty good job making some terminology declarative and tech-agnostic. . .like the pagination language `first, last, after, before`  works on ANY data set, where terms WP uses like `posts_per_page` _only_ make sense in WordPress.

Ideally, these filters should make a declaration for what the consumer wants, not _how_ to get it. The Schema shouldn't expose the underlying functions (unless it makes sense to), but should expose ways for the user to declare what they want, and the server takes that declaration and does something.

For example, let's say I were a React native developer who's never used WordPress before. Trying to consume data from an API that I don't even know is on WordPress, I feel like `filters: [THE_CONTENT, GET_THE_EXCERPT]` isn't intuitive as those are very WordPress-y and don't actually allow the consumer to express what they want from the field.

I think it might be good to think of some more declarative ways to handle this, where consumer could declare _what_ they want from the fields and the server does whatever needed to get that result.

Like _maybe_ something to the tune of: `PLAIN_TEXT`, `WEB_READY`, `EXCLUDE_EMBEDS` or something to that tune?

Then the server can take `WEB_READY` and apply whatever transformation is needed on the server, such as `apply_filters( 'the_content', $content )` and `PLAIN_TEXT` could be used by the server to strip tags and shortcodes or something to that tune. . .

This _might_ be an unachievable feat, because we _do_ still need to have the power to apply certain filters as a consumer, in the same way WordPress devs have the ability to do now from within WordPress, and potentially abstracting _too_ much might be difficult/impossible to accomplish both needs :thinking_face:

I'm not 100% opposed to the implementation you put together for the PR, _but_ at least want to discuss it some more (edited)

Schema design is haaaard...

**Comment by duffn** [comment]
> Overall I think providing anything beyond "raw" and "rendered" is beyond the scope of what this plugin should do. I just don't see a great way to give widespread fine tuned controls over what filters run over the data on a resolver by resolver basis. I feel like this will only lead to a fragmented and inconsistent experience for the consumer since there's know way we will be able to offer the same level of controls for each field.

I agree with this one from @CodeProKid. This seems like the extent of manipulation that should come straight from the plugin.

**Comment by jasonbahl** [comment]
#230, and the conversations surrounding it address this (see the slack link above). 

**To summarize:** 
We added an `$arg` "format" which has an ENUM of `RAW` and `RENDERED`. 

This field can be used with the `\AppContext` that gets passed down the resolve tree to alter the content for various situations. 

This way, consumers can declare that they want the `RENDERED` content, and that declaration, combined with their context (Native Mobile, Web, Alexa? Google Home? Siri? Apple TV?, Print?, Apple Watch?, etc), what is returned can be different. 

So, instead of the consumer saying they want to "STRIP_TAGS" and "STRIP_SHORTCODES" they can simply say "I want RENDERED content for the web" or "I want RENDERED content for Native Mobile" and the server gets to determine what to apply (strip tags, strip shortcodes, etc) to get the content prepared for what the client is asking.

This keeps things abstract enough to allow for all sorts of combinations of "format" args and "renderContexts" via the AppContext to be used. 

I'll need to provide more examples and a blog write up most likely, but here's a simple *conceptual* (pseudo code) example to showcase how the "format" and renderContext _could_ hypothetically be used together to return different "content" based on the context of the request: 

```
add_filter( 'graphql_post_fields', function( $fields ) {
     
     $fields['content']['resolve'] => function( $post, $args, $context, $info ) {
         
        if ( 'rendered' === $args['format'] && 'native-mobile' === $context->renderContext ) {
             
              return format_rendered_content_for_mobile( $post->post_content );
         
         } else if (  'raw' === $args['format'] && 'native-mobile' === $context->renderContext ) {
            
               return format_raw_content_for_mobile( $post->post_content );
         
         } else if (  'rendered' === $args['format'] && 'web' === $context->renderContext ) {
         
             return format_rendered_content_for_web( $post->post_content );
        
          }
     }
     
     return $fields;

}, 10, 1 );
```

@kozlowskij @duffn ^ with that said, the specific implementations, like Alexa/Voice Apps as a "renderContext" should be addressed outside of the WPGraphQL core plugin. 

I think a "WPGraphQL Alexa Render Context" and a "WPGraphQL React Native Render Context" plugin sounds fantastic though to solve ya'lls needs. 

We can discuss those further via to get those situations resolved for your needs.
