### ISSUE TITLE
I there a way to allow all subscribers to read private posts ?

### ISSUE THREAD

**Issue by philohelp** [wp-graphql/wp-graphql#1700]
Hello,
It's a great pleasure to work with this plug-in. One thing I was wondering as I'm not at all an expert in WP, is if there was a mean to allow any subscriber to read private content. It's very easy to do that at the theme level, adding two lines in the theme function, but I dont know how I could the same thing to accomplish this with posts retrieved by wp-graphQL.
Thanks a lot for your answers !

FYI, in theme/functions.php:
```
function add_sub_caps() {
    global $wp_roles;
    $role = get_role('subscriber');
    $role->add_cap('read_private_posts');
}
add_action ('admin_init','add_sub_caps');
```

**Comment by CodeProKid** [comment]
@philohelp You could achieve the same thing by adding your callback to the `graphql_init` hook instead of `admin_init`. 

Though I would first ask, why are these posts "private" if subscribers are supposed to be able to view them? Can they just be published instead? 

If you do in fact need them to be "private", a better solution may be to set a custom capability to `read_private_posts` when [registering your post type](https://developer.wordpress.org/reference/functions/register_post_type/#capabilities), and then add that capability to the subscriber role or a custom role. I would be wary of giving the `read_private_posts` cap to the subscriber role since it could have unintended consequences in other areas of the site.

**Comment by philohelp** [comment]
Thanks a lot !
The posts are private because parts of the website are only accessible to
subscribers and other parts are public. The goal is then to mark as private
the posts that can only be seen if you’re registered.

Le dim. 28 févr. 2021 à 23:52, Ryan Kanner <notifications@github.com> a
écrit :
