### ISSUE TITLE
Can we create a new post using mutation in WP-graphql endpoint?

### ISSUE THREAD

**Issue by JayakrishnanJK** [wp-graphql/wp-graphql#175]
Can we create a new postin wordpress using mutation in WP-graphql endpoint?

**Comment by jasonbahl** [comment]
You can!

You can see examples of mutations creating, updating and deleting posts here: https://github.com/wp-graphql/wp-graphql/blob/master/tests/test-post-object-mutations.php

But in order to mutate data, you need to be authenticated and have proper capabilities. 

Authentication is handled outside of WPGraphQL itself, so you can use existing Auth methods (like any of the REST API Auth plugins or if on the same domain you can use Cooke Auth). 

You can see an example of how Cookie Auth is implemented for a React App that is loaded in the `/wp-admin` here: https://github.com/wp-graphql/wp-graphiql/blob/master/assets/app/src/App.js

We use oAuth 1 and Basic Auth via these plugins (https://github.com/WP-API/Basic-Auth, https://github.com/WP-API/OAuth1), and WPGraphQL works with these plugins, just send the proper headers as the plugin instructions say and and WPGraphQL will respect the authenticated user in the resolvers.
