### ISSUE TITLE
graphql endpoint returning 500 on vanilla install

### ISSUE THREAD

**Issue by pmonty** [wp-graphql/wp-graphql#1770]
So I have added wpgraphql and the schema was showing perfectly fine in my local docker wordpress site. The next day I load up and try to hit the endpoint through apolloclient/nextjs app and it returns a 500. No changes to the wordpress site at all. I thought it might be my code so I wanted to confirm and went to the wordpress graphiql IDE and schema wasn't loading and there was a 500 error in the network tab. 

Very strange and frustrating, wondering if the latest version is stable and if anyone else is experiencing issues?

**Comment by jasonbahl** [comment]
Latest version should be working fine. Do you have any PHP error logs? I imagine you might find some helpful information in the PHP error logs. 

I'd also recommend checking out the tips we have on our Debugging page here: https://www.wpgraphql.com/docs/debugging/

Is your endpoint public? Are you using more plugins than just WPGraphQL? There's a chance there's a conflict. 

What did you do in between "Schema showing perfectly fine" and "The next day" when it returned a 500? Did you add any custom code? Install new WordPress plugins, etc?

If it's just random behavior, it could also be something wrong with your hosting setup blocking requests. Depending how you're using Next, it's possible for Next to spawn many different concurrent requests that could overwhelm your server. (see: https://webdevstudios.com/2021/03/09/next-js-headless-wordpress/)

**Comment by jasonbahl** [comment]
Closing this as there's been no response to my previous questions.

**Comment by ShahriarKh** [comment]
Thank you @jasonbahl for pointing out the blog post. I tried many different things, from changing the `revalidate` value (Next.js ISR) to disabling plugins and tweaking WordPress settings. Seems like the Yoast Addon for wp-graphql (https://www.wpgraphql.com/extenstion-plugins/wpgraphql-for-yoast-seo/) is causing the problem, because of the complexity of data. However, I'm not still %100 sure, but before activating this plugin, everything was fine.
(also, I need to note that I get 500 only in my deployment environment; in local, everything is fine even if Yoast Addon is enabled)
