### ISSUE TITLE
WPGraphQL appears to have been installed without it's dependencies

### ISSUE THREAD

**Issue by punkitocom** [wp-graphql/wp-graphql#1814]
Just installed 1.3.2 and faced with this isuue - on the top the message:

WPGraphQL appears to have been installed without it's dependencies. It will not work properly until dependencies are installed. This likely means you have cloned WPGraphQL from Github and need to run the command `composer install`.

And when try to load /wp-graphiql.php it respond with below error:

Error thrown
Class 'WPGraphQL\Router' not found

**Comment by jasonbahl** [comment]
@punkitocom Thanks for checking out WPGraphQL! 

Did you clone from Github? If so, you need to run `composer install` as directed in the message. 

The primary distribution channel for the plugin is now the WordPress.org repository (https://wordpress.org/plugins/wp-graphql/). 

You can install it directly from your WordPress dashboard, or if you want to have the plugin versioned with your code using something like Composer you can install from Packagist.org or WPackagist.org. 

If you're cloning from Github, the assumption is that you're using the code in a developer environment and will need to install the dev dependencies. 

You can read more about the various install methods here: https://www.wpgraphql.com/docs/quick-start/

I'm going to close this issue as I believe it's documented well, but if there's anything you feel could be better about the docs, I'm open for feedback to make things better!

**Comment by punkitocom** [comment]
Thank a lot for your support. I've updated plug-in with WP build in manager and it works now!

**Comment by cmonkey03** [comment]
@jasonbahl Thank you for your answer on this issue. I just wanted to confirm that we should be:

1. Downloading & unzipping the plugin from https://wordpress.org/plugins/wp-graphql/ (not using this repository)
2. Adding it to our plugins directory
3. Committing this to our WPCOMVIP Github account

Thanks!

**Comment by jasonbahl** [comment]
Yes, you will need to end up with an artifact matching what you can download and unzip from wordpress.org, which includes the vendor dependencies such as `graphql-php`

There are numerous ways you can go about this. 

I believe our workflow at the newspaper was to use packagist to manage the versions of the plugins, such as WPGraphQL, that we needed, then we'd `composer install` the plugins then the installed assets would all end up being committed up to VIP. 

I think VIP was just working on their CI tooling at that time, so you might be able to automate with their CI tooling, or automate in some pre-VIP workflow step. 

We liked using composer to manage these things because we could specify a version, run tests against it, then update versions, run tests, etc.
