### ISSUE TITLE
rename_graphql_field doesn't work properly for connections

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1843]
The new `rename_graphql_field` API doesn't work properly for connections. 

## Steps to Reproduce

Add the following code to functions.php or custom plugin code:

```php
add_action( 'graphql_register_types', function() {

  rename_graphql_field( 'RootQuery', 'users', 'wpUsers' );

});
```

### Expectation

The `RootQuery->Users` connections should be named `wpUsers` and I should be able to query: 

```graphql
{
  wpUsers {
    nodes {
       id
       name
    }
  }
}
```

### Actual Behavior

There is no `wpUsers` field added to the Schema. The `RootQuery.users` field remains in the Schema.

## More Info

This appears to be related largely to these filters: 

- https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/WPObjectType.php#L209
- https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/WPObjectType.php#L227
- https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/WPObjectType.php#L239

When the filter to rename fields runs, not all fields (connection fields, for example) have been registered to their connecting Type, so there's no field to rename yet. 

I believe we should formally deprecate the latter 2 filters in favor of the former. This way there's one central filter used to filter fields, instead of 3 different ones. 

This will allow us to better use priorities with filters to determine what's filtered early/later, vs using separate filters altogether.

We should be able to do this in a backward compatible way by having the latter 2 filters hook into the first one, instead of running _after_ the first one. 

There's likely more to the issue than these filters, but I think this is some good starting context.

**Comment by justlevine** [comment]
@jasonbahl I'm not entirely sure the relevance of the `graphql_${lc_type_name}_fields` and `graphql_${uc_type_name_fields` to this issue (though I'm 💯 on board for dropping them).

Ironically, #2945 fixes the bug by _adding_ a filter, but I've marked it as internal since "This way there's one central filter" for users (in this case `graphql_wp_connection_type_config` ) is still a good guiding rule.

Up to you if you want to parcel off the aforementioned filter deprecations to a separate issue (so they dont get lost when #2945 closes out this one ), or if #331 is enough.
