### ISSUE TITLE
Page/Post Templates should be registered to the schema using get_page_templates()

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1845]
Currently WPGraphQL makes use of the global `wp_get_theme()->get_post_templates()` to find all templates. 

This method is not filterable. 

We should switch to use `get_page_templates()` to allow the templates to be filterable. 

We will also need to specify each post_type in order for the filters to be properly applied. 

See: https://core.trac.wordpress.org/browser/tags/5.7/src/wp-includes/class-wp-theme.php#L1265
See: https://core.trac.wordpress.org/browser/tags/5.7/src/wp-includes/class-wp-theme.php#L1281

**Comment by CalebBarnes** [comment]
I was quickly trying to make a WP plugin to allow devs to add templates without creating PHP files in the theme but ran into this issue that my templates are not appearing in`wp_get_theme()->get_post_templates()`

Would love to see this update! Would be a nice boost in productivity since most headless sites don't even need a theme. 👍

I am using the wp filter `theme_page_templates` to add templates from an acf options page. 

Example here if you are interested: https://github.com/CalebBarnes/custom-templates-creator/blob/main/custom-templates-ui.php#L48-L65

**Comment by jasonbahl** [comment]
Closing as this was fixed by @justlevine and released in v1.8.0 (see: https://github.com/wp-graphql/wp-graphql/releases/tag/v1.8.0)
