### ISSUE TITLE
How to query posts using the category ID (example dGVybToxNw== instead of an INT)

### ISSUE THREAD

**Issue by ErikThiart** [wp-graphql/wp-graphql#1892]
This works

```
query GetPostsByCategoryId {
  posts(where: {categoryId: 1}) {
    nodes {
      title
    }
  }
}
```

But I do not have the INT IDs, I have the weird looking ones: `dGVybToxNw==`

begotten like so:

```
      categories {
        nodes {
          id
        }
      }
```
Ergo, why is `categoryId` not working as expected, what am I missing?

Is there any way to query by id instead of categoryId in posts ?

**Comment by jacobarriola** [comment]
@ErikThiart the `id` that you get back is a base 64 encoded string of the type and database id.

So `dGVybToxNw==` translates to `term:17`.

To query by the database ID, you'll need to pass in the `idType` argument because it defaults to the hashed ID.

```graphql
{
  category(id: 17, idType: DATABASE_ID) {
    name
  }
}
```

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1371573/118415166-aae0b900-b65d-11eb-83ba-6e7ce7ed6a62.png">

**Comment by bhardie** [comment]
Closing based on @jacobarriola answer.
