### ISSUE TITLE
register_graphql_field resolve function $post_object is now a protected variable 

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#1899]
Using `1.3.7` and WP-GQL-ACF `0.5.2`.

This function:
```
                register_graphql_field($ucfirst, 'next' . $ucfirst, [
                    'type' => 'Next' . $ucfirst . 'Edge',
                    'description' => __(
                        'The next post of the current port',
                        'wp-graphql'
                    ),
                    'resolve' => function ($post_object, $args, $context) {
                             var_dump($post_object); die;
                    }
                ]);
```

Will now output this:
```
object(WPGraphQL\Model\Post)#17355 (11) {
  ["data":protected]=>
  object(WP_Post)#17347 (24) {
    ["ID"]=>
    int(18760)
    ["post_author"]=>
    string(1) "4"
    ...
```

It did not used to do this, the $post_object was not protected. This makes it difficult to use the $post_object now. It also breaks all my existing custom resolvers.

**Comment by drewbaker** [comment]
If anyone is curious, the hacky work around is this:

```
                register_graphql_field($ucfirst, 'previous' . $ucfirst, [
                    'type' => 'Previous' . $ucfirst . 'Edge',
                    'description' => __(
                        'The previous post of the current post',
                        'wp-graphql'
                    ),
                    'resolve' => function ($post_object, $args, $context) {
                        global $post;
                        $post_object = getProtectedValue($post_object, "data");
                        var_dump($post_object);
                    }
                ]);

                function getProtectedValue($obj, $name) {
                    $array = (array)$obj;
                    $prefix = chr(0).'*'.chr(0);
                    return $array[$prefix.$name];
                }    

```

**Comment by jasonbahl** [comment]
What version of WPGraphQL does "used to" refer to? 

This isn't a new change and is intentional as part of the model layer. And unless there was some regression I'm missing this has been changed for quite a while. 

The WP_Post object (used internally in WordPress abs a while ago in WPGraphQL) doesn't know who can/cannot access the object or properties of it, but the Model objects do. 

The models in WPGraphQL centralize access control to data. 

This makes it so that access control can be handled centrally vs handled in every resolver that asks for an Object, as many different resolvers might get to the same object. 

I'd suggest using properties from the Model to get what you need. 

Such as `$post->databaseId`. 

And even consider extending the Model to centrally control what fields can/cannot be exposed in the Graph.

**Comment by drewbaker** [comment]
Thanks @jasonbahl maybe I'm missing something here. I didn't realize the global $post object works in the resolver.

For future readers, this works:

```
                    'resolve' => function ($post_object, $args, $context) {
                        $post = get_post($post->databaseId);
                        
                        if (is_post_type_hierarchical($post->post_type)) {
    	                    $post_id = get_previous_page_id($post);
                        }
                        else {
    	                    $prev_post = get_previous_post();
    						$post_id = $prev_post->ID;
                        }
                        
                        return $post_id;
                    }
```

So I don't actually need `$post_object`.

**Comment by drewbaker** [comment]
Ok, so the plot thickens. What I've found is this query actually has `$post` in the resolver as the logo attachment from the previous ACF meta block.

```
query WorkDetail($uri: String!) {
    nodeByUri(uri: $uri) {
        id
        ... on Page {
            title
            excerpt
            acfWorkMeta {
                logos {
                    sourceUrl
                }
            }
            nextPage {
                node {
                    ... on Page {
                        title
                        id
                    }
                }
            }
        }
    }
}
```

So that is what is messing me up. @jasonbahl does that make sense to you? Is it possible that WP-GQL-ACF is changing the global post object and breaking my resolver?

**Comment by justlevine** [comment]
@drewbaker In your above code snippet, you're not actually accessing the global `$post` object. Rather, you're trying to `get_post( { undefined }->databaseId )` which defaults to using the global object. Regardless,  you **dont want to be using the global**, since as you see the actual queried object is different based on context.

Instead, you _should_ be getting the ID from the resolver's first parameter. I.e. change `get_post( $post->databaseId )` to `get_post( $post_object->databaseId )`, or simply rename the first argument in the resolver from `$post_object` to `$post`.

**Comment by drewbaker** [comment]
Fixed it with https://github.com/funkhaus/fuxt-backend/commit/b58f56634dcd447b5ab16466c645cc56794d3f09

Thanks so much for this, helps me to better understand these resolvers!
