### ISSUE TITLE
ACF 'User' has inconsistent behavior at server GraphQL Endpoint vs Wordpress Internal GraphIQL

### ISSUE THREAD

**Issue by shawngrona** [wp-graphql/wp-graphql#1931]
## Steps to Reproduce:
1. Open [GraphIQL](https://www.electronjs.org/apps/graphiql) and connect to https://cms.psychedelic.support/graphql
2. Run the following query:
```
 {
  post(id: "cG9zdDo0NzAwNQ==") {
    id
    title
    multipleAuthorsAcf {
          multipleAuthor {
            name
            slug
            description
            avatar{
              url
            }
          }
      }
  }
}
```

### Expected Result:
We receive a 'multipleAuthorsAcf' User array as we do in the Wordpress GraphIQL instance (see attachment)
<img width="1832" alt="Screen Shot 2021-05-27 at 9 33 32 PM" src="https://user-images.githubusercontent.com/7434518/119929890-39ddb300-bf33-11eb-8b16-ca6281518614.png">

### Actual Result:
We don't receive a multipleAuthorsAcf User array
<img width="1279" alt="enneagram-graphiql" src="https://user-images.githubusercontent.com/7434518/119929208-ee76d500-bf31-11eb-9eb4-231fe9c585ef.png">

## System Info
Wordpress v5.7.2

WP GraphQL v 1.3.9
Advanced Custom Fields v 5.9.6
Contextual Related Posts v 3.0.7
Jetpack v9.7
Pressable Automated Migration v4.58
ProfilePress v3.1.3
Safe SVG v1.9.9
Two Factor v0.7.0
Under Construction v3.88
Username Changer v3.2.2
WooCommerce v5.0.0
WP Gatsby v1.0.10
WP Mail SMTP v2.8.0
WP Rollback v1.7.1
WPGraphQL for Advanced Custom Fields v0.5.2
WPGraphql Yoast Seo v4.0.0
Yoast SEO v16.3

**I can also reproduce this behavior on my staging instance with only the following necessary plugins enabled:
Advanced Custom Fields v 5.9.6
WP GraphQL v 1.3.9
WPGraphQL for Advanced Custom Fields v0.5.2

**Comment by shawngrona** [comment]
FWIW I can find other posts which are working with the ACF User multipleAuthorsAcf eg:
```
 {
  post(id: "cG9zdDo0Mjg0Mg==") {
    id
    title
    multipleAuthorsAcf {
          multipleAuthor {
            name
            slug
            description
            avatar{
              url
            }
          }
      }
  }
}
```
<img width="1286" alt="how-to-find-graphiql" src="https://user-images.githubusercontent.com/7434518/119929674-d0f63b00-bf32-11eb-9cad-cac97c331943.png">

**Comment by bhardie** [comment]
Based on what you are sharing, I believe you are setting IDs of users that are unpublished authors.  Unpublished authors are considered private objects in WP.  so, when you run your query as a logged in user, you will see them, but not when querying as a public non-authenticated user.

Here are some links on the topic:
https://www.wpgraphql.com/docs/security/#access-control-rights
https://www.wpgraphql.com/docs/users/#sensitive-data

One thought would be to use a custom post type instead of users so you can set the read permissions for that data.  Based on the above, we are going to close this issue.  If you believe there is another issue beyond this, please open a new issue referencing this one, and include clarifying details.

**Comment by shawngrona** [comment]
Yes @bhardie that was exactly it, thank you so much.  

For those in future, if your use case supports (ie you don't have any sensitive info stored in the wp users) in addition to above suggestion, you can [make all users public](https://www.wpgraphql.com/2020/12/11/allowing-wpgraphql-to-show-unpublished-authors-in-user-queries/)
