### ISSUE TITLE
Content API* key for endpoint?

### ISSUE THREAD

**Issue by everonegraham** [wp-graphql/wp-graphql#2069]
Hey there, I'm doing some research to use the plugin for an upcoming project.

After checking out Ghost API, I realized that WPGraphql doesn't have content API* key built in for fetching data. So anyone could access my endpoint. 

Is this something that will be considered in the future?

Why or why not?

**Comment by jasonbahl** [comment]
@everonegraham WPGraphQL exposes data that's already public as public data in the API and restricts private data to users that have proper capabilities to access the data. 

For example, if you publish a post or a page in WordPress, the title and content of that page are public on a url `yoursite.com/your-page`, and some associated data, such as the author of the post, the featured image, etc are all publicly accessible now. 

This public data can be accessed via WPGraphQL as well. 

Now, if you create a post and save it as a draft in WordPress, this data cannot be seen publicly and WPGraphQL respects that. In order to see a draft post in WPGraphQL, you would have to make an authenticated request. 

You can do this in various ways, such as using WPGraphQL JWT Authentication, where the user would login, get a JWT Auth token, then pass that token in future GraphQL requests to identify who they are, and WPGraphQL would then allow that user to see private data, such as unpublished Draft posts. 

So, right now, WPGraphQL isn't exposing anything from WordPress that isn't already exposed publicly by WordPress. If you believe there's data being exposed publicly by the API that shouldn't be, open an issue and we can discuss and resolve that.

> Is this something that will be considered in the future?

I'm not opposed to considering it. There are various ways already to lock down the API and I've written some articles on the topic, such as: https://www.wpgraphql.com/2019/01/30/preventing-unauthenticated-requests-to-your-wpgraphql-api/

I think there would need to be a strong argument for why this should be something the core WPGraphQL plugin should adopt, and I would indeed consider adopting it if the case were strong!

**Comment by everonegraham** [comment]
Thank you for a detailed reply. Really appreciate it. 😄

**Comment by elhaddajiOtmane** [comment]
@jasonbahl  i thing it would be highly beneficial if the plugin included a builtin setting to configure an API key for accessing the endpoint. This would enhance security and give us more control over who can access the data.

**Comment by justlevine** [comment]
@elhaddajiOtmane you can do this without too much effort by restricting the GraphQL endpoint to authenticated users in the WPGraphQL settings, and then using WordPress's built-in Application Passwords in the request header as a fallback if a specific user isnt authenticated on the frontend.
