### ISSUE TITLE
GraphQL IDE "NO SCHEMA AVAILABLE" - v1.6.5

### ISSUE THREAD

**Issue by WillSquire** [wp-graphql/wp-graphql#2104]
Upgrading to `"wp-graphql/wp-graphql": "^1.6",` causes the GraphQL IDE to return `undefined` for the introspection query. Console outputs:

```
Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined.
```

The explorer tab only shows "NO SCHEMA AVAILABLE".

I noticed similar issues open for when other plugins are active. However, I don't have those plugins installed.

The precise package version is `v1.6.5`. All packages were upgraded one by one to find the faulty package. The complete list of changes are:

```
- Upgrading webonyx/graphql-php (v14.8.0 => v14.9.0): Extracting archive
- Upgrading ivome/graphql-relay-php (v0.5.0 => v0.6.0): Extracting archive
- Upgrading wp-graphql/wp-graphql (v1.5.0 => v1.6.5): Extracting archive
```

**Comment by jasonbahl** [comment]
@WillSquire My hunch is that you were running into a conflict with the `register_setting()` API and how some plugins (such as Stackable and Google Web Stories) register settings and how those settings were mapped to the WPGraphQL Schema. 

I believe this is fixed by #2262, which is part of the v1.7.0 release.
