### ISSUE TITLE
Wrong hasPreviousPage and hasNextPage values on first load

### ISSUE THREAD

**Issue by DidoMarchet** [wp-graphql/wp-graphql#2156]
Hi,
I'm running **wp-graphql v1.6.7** on **Wordpress v5.8.2**.

I've got an issue with `pageInfo`.

On the first load it returns me `hasPreviousPage` and `hasNextPage` as **false** despite I've got a lot of pages:

![screen-cursor-no-ok](https://user-images.githubusercontent.com/38940340/142463795-1999c5b4-2392-4764-83fd-4fb5748e88df.png)

Instead if I try to add a the cursor into the query it return me the right values:

![screen-cursor-ok](https://user-images.githubusercontent.com/38940340/142463460-92aeb049-7d0d-4c13-ab2a-2f020bcc1d90.png)

Do you noticed this issue or do you have any advice?

Thanks in advance and kind regards,

Davide

**Comment by jasonbahl** [comment]
@DidoMarchet this is expected behavior per the Relay specification. 

If the query does not ask for a specific number of items using the `first` or `last` argument, then `hasNextPage` and `hasPreviousPage` will return false. 

In order to paginate, you need to use `first` and `after` (forward pagination), or `last` and `before` (backward pagination).

**Comment by DidoMarchet** [comment]
Hi, thanks for the support and have a nice day, 
Davide
