### ISSUE TITLE
Get BuddyPress data and custom table from database

### ISSUE THREAD

**Issue by EddieLi** [wp-graphql/wp-graphql#222]
I wrote a few custom tables to store new feature data for my website, how do I grab them using this plugin? 

Or is there a hook I can use?

Any help is appreciated, thanks!

**Comment by jasonbahl** [comment]
@EddieLi Hey!

Since you're using a custom data source, you'd have to do some leg work and define a Type (or multiple types depending on the shape of your data). Then you'd have to hook into the Schema to provide fields to resolve the data. 

This should elaborate on some of the hooks and concepts to get you going: https://github.com/wp-graphql/wp-graphql/issues/11#issuecomment-308881788

Essentially, every GraphQL field has a Type, Description and Resolver. The resolver needs to resolve to the same "type" that is defined for the field. That field can define a scalar type (string, integer, boolean, etc) or an ObjectType (that you define), and the resolver needs to return data matching that type. 

Without knowing anything about your custom data that you're storing it's hard for me to provide any insight into how you should shape things. You can shape the schema for your needs however you want, but I would highly suggest shaping it similar using the Relay spec as a guide. . .making use of Connections, Edges and Nodes. You should be able to check the source code for how I have postObjectConnections setup, etc to get an idea how you can implement for your custom data. 

Hope this helps!

**Comment by jasonbahl** [comment]
@EddieLi I'm going to close this, but feel free to post back (here or in a new issue) if you have more specific questions and I'll do my best to help. Good luck with your project!
