### ISSUE TITLE
User Registration Mutation

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#223]
Need to add a mutation for user registration. The mutation should only be available if the "allow anyone to register for the site" is checked, and the newly registered user should just get the default user role attached to it.

**Comment by kellenmace** [comment]
I submitted a PR that adds this mutation for registering new users. If WP's "Anyone can register" setting is false or the username/password is not provided, WPGraphQL responds with the appropriate error message. Otherwise, if "Anyone can register" is set to true and valid args were provided, the new user is registered and the user's details are included in the response.

I added tests to address when "Anyone can register" is enabled, as well as when it's disabled. Please let me know if I can make any additional changes. Thanks!

Here is a gif showing the new feature in action:
https://cloudup.com/cFdVhxOlsYn

P.S. This plugin rules! Thanks for creating it! 🙌🏼

**Comment by CodeProKid** [comment]
This was released here -> https://github.com/wp-graphql/wp-graphql/releases/tag/v0.0.33
