### ISSUE TITLE
Post object connection returning wrong number of 'total pages'

### ISSUE THREAD

**Issue by BenMcD0nald** [wp-graphql/wp-graphql#2250]
Hey,

I'm trying to pull data about the total page count in the request but I've hit a bit of a wall

The filter I'm using is:

`add_filter('graphql_connection_page_info', function ($page_info, $connection) {
	$page_info['total'] = null;
	if ($connection->get_query() instanceof \WP_Query) {
		if (isset($connection->get_query()->found_posts)) {
			$page_info['total'] = (int) $connection->get_query()->max_num_pages;
		}
	}
	return $page_info;
}, 10, 2);`

but this is pulling back the wrong count. This is demonstrated in the below image where 12 results are requested from 2556. Page count should be 213 but it's showing 197. The reason for this appears to be because the post count of the query is 13 instead of 12. I'm presuming this is something to do with the core of how WPGraphql works.

![1](https://user-images.githubusercontent.com/30300743/155611013-e9683b37-5646-4164-a2a5-3d96e48b869e.png)

Can you confirm if you're aware of the above and if it's intended? Also, do you know any way around it because I'm running out of ideas. 

(I did also take a look at  'get_query()->post_count' but this shows the amount of posts in front i.e. it doesn't consider results behind the cursor...therefore the number changes and doesn't represent total posts)

Thanks
Ben

**Comment by jasonbahl** [comment]
@BenMcD0nald this is intentional behavior. 

The `post_count` is the number of items returned from the query. WPGraphQL uses `cursor` pagination vs page-based pagination, and to do this it asks for 1 more record than the query has asked for. 

So, when the query asks for `first: 12`, that translates to a SQL query of `LIMIT 13`.

If `13` records were returned by SQL, then `hasNextPage` will be set to true, as we've now determined there's at least one more record than the 12 that were asked for. If 12 or fewer records are returned, then `hasNextPage` would be false, as we know you've hit the end of the list of records. 

It looks like you might be modifying something to get the `found_posts` because WPGraphQL intentionally doesn't calculate the total number of posts for any given query.

The code that sets the `posts_per_page` to be equal to the number asked for, +1 is here: 

posts: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L190-L193

comments: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/CommentConnectionResolver.php#L45

terms: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/TermObjectConnectionResolver.php#L70

users: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/UserConnectionResolver.php#L76

**Comment by jasonbahl** [comment]
@BenMcD0nald I'm going to close this, as I don't believe there's an issue to be addressed and I believe I provided relevant information about how this works under the hood. 

If there is indeed a bug or other issue you feel needs to be addressed here, please open another issue and feel free to reference this one for context. 

Thanks! 🙏🏻

**Comment by BenMcD0nald** [comment]
Apologies for not responding sooner and thanks for the detailed response.

Yep, agreed that this is not a bug it just wasn't really how I was expecting it to operate as I could apply a filter to pull back the total just that the total was only correct on the first page, otherwise it would show total _remaining_. I'm going to dig into the code a little to see if there is a better way to do it but in the meantime I feel like I've come up with a workaround where I'm only using the total results received on the first page and only updating where the query is again a first page (i.e. fresh query).

Thanks as always for your time and feedback and for the great work you and the team are doing!!
