### ISSUE TITLE
allWpMediaItem returns nothings

### ISSUE THREAD

**Issue by opr-inzn** [wp-graphql/wp-graphql#2258]
Since today I am having trouble with WPGraphQL, WordPress and GatsbyJS. I have a post (slug: can-touch-this) with an image gallery (Gutenberg). I used to query for the image captions like this: 

```
{
  allWpMediaItem(
    filter: {wpParent: {node: {slug: {eq: "can-touch-this"}}}}
  ) {
    edges {
      node {
        caption
      }
    }
  }
}
```

However, this does not return anything anymore. What shall I do?

WPGraphQL: Version 1.6.12

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    npm: 8.4.1 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.3
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0
    gatsby-plugin-image: ^2.8.1 => 2.8.1
    gatsby-plugin-manifest: ^4.8.1 => 4.8.1
    gatsby-plugin-sharp: ^4.8.1 => 4.8.1
    gatsby-source-filesystem: ^4.8.1 => 4.8.1
    gatsby-source-wordpress: ^6.8.1 => 6.8.1
    gatsby-transformer-sharp: ^4.8.0 => 4.8.0
  npmGlobalPackages:
    gatsby-cli: 4.8.1
    gatsby: 4.8.1

**Comment by jasonbahl** [comment]
@opr-inzn Since you're having issues with a Gatsby query, the issue could be in WordPress / WPGraphQL, or it could be in on the Gatsby / Gatsby Source WordPress side of things. 

Can you query media items in WPGraphQL directly?

For example: 

```php
{
  mediaItems {
    node {
      __typename
      id
    }
  }
}
```

If so, this means WPGraphQL is returning MediaItems, so I would believe that the issue is on the Gatsby side. 

When querying data in Gatsby, you're querying against Gatsby's copy of the data, and not against WPGraphQL directly. 

So, when you're having issues with a query like `allWpMediaItem` that query isn't making a request to WPGraphQL directly. If that's returning no results, it means Gatsby didn't load any images from WordPress. 

There might be some configuration in Gatsby Source WordPress that might help you here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#typemediaitem

If you're not able to overcome this issue by adjusting some of the plugin options, I would recommend opening an issue on one of the Gatsby repos to get official support from Gatsby. 

You could also try the #gatsby channel in the [WPGraphQL Slack](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA).

**Comment by peach-inzn** [comment]
Hey @jasonbahl! Thank you so much for your response(s)! 

> And is there a formal connection between the post "can-touch-this" and the media item?
This was the problem. I was not aware that only images uploaded directly to the post will have a formal connection.

Thanks a lot for your help!

**Comment by opr-inzn** [comment]
Hey @jasonbahl! Thank you so much for your response(s)!

And is there a formal connection between the post "can-touch-this" and the media item?
This was the problem. I was not aware that only images uploaded directly to the post will have a formal connection.

Thanks a lot for your help!

**Comment by jasonbahl** [comment]
@opr-inzn I don't think there's a guarantee that there will be data, so you might need to use some [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) here:

`view?.localFile?.childImageSharp.gatsbyImageData`, for example?

🤷🏻

**Comment by opr-inzn** [comment]
@jasonbahl I made the rather stupid mistake of importing `GatsbyImage` like this:
`import { GatsbyImage } from "gatsby"`
instead of the correct: 
`import { GatsbyImage } from "gatsby-plugin-image"`

Please excuse me and thanks again!
