### ISSUE TITLE
Add built version of the plugin to pull requests to make it easy(er) to test

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2272]
As the maintainer of WPGraphQL, I would like pull requests to generate a built version of the plugin and upload it as a .zip to the pull request so that I and anyone reviewing the pull request can more easily test the plugin at that state. 

For users that already have the codebase cloned, it's not too hard to pul it down and install dependencies, but having a built zip can make some tasks easier to test. 

fwiw, this Github Action might help here: https://github.com/gavv/pull-request-artifacts

**Comment by justlevine** [comment]
Hey @markkelnar , you should be able to use `pull_request_target` instead of `pull_request` to keep the secrets accessible yet safe.

That said, there are [other security concerns that need to be considered](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), and having manually checkout the PR provides a barrier to entry for those who may not know they should review the code before running a PR locally or those that just don't know what to look for.

Downloading the branch from the fork, and running `composer install` isn't that big of a barrier to entry on local (and less onerous than needing to have the git set up locally to checkout), but still a headache for for testing on on of those disposable cloud WP instances.

Alternatively, we could just start including the composer autoloader in the repo, and then any branch downloaded from GitHub would work. They'd need to be generated on the PR to ensure references to dev deps don't get committed if someone doesn't run `composer dump-autoload --no-dev --optimize` before pushing, tho.

**Comment by jasonbahl** [comment]
I like the idea of changing it to use `pull_request_target` but with a condition of a specific label being applied. 

That way, once a PR has been reviewed by a maintainer, the label (such as `build plugin zip`) could be applied and the zip could be built 🤔 

I tried making some changes to the PR based on what I read in [this article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) but I'm not having luck 🤷🏻‍♂️

**Comment by jasonbahl** [comment]
Closing for now. We can re-visit if we feel it's important enough at a later date.
