### ISSUE TITLE
Installing WPGraphQL with Composer doesn't include the built GraphiQL app

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2282]
When installing WPGraphQL from composer, using `composer require wp-graphql/wp-graphql` starting with v1.7.0, the GraphiQL App is not included anymore. 

In previous versions, I was building the GraphiQL app locally and committing / versioning the built app. The built files were included in the distribution to Packagist and therefore included in the installed files from composer. 

Now, the built JavaScript app is not versioned in Github, but instead it is built for deploying to WordPress.org. 

However, the JavaScript app is _not_ built before deploying to Packagist.org. 

I'm not fully sure if there's a way to do this, as Packagist.org picks up the package when a release is tagged. If theres some sort of "middleware" I can hook into between release on Github and Packagist getting the files, that would be one option to ensure the JavaScript app gets built and included in the packagist archive. 

Another option, would be to update the documentation to guide users that install with composer, to install from wpackagist.org, which gets the built plugin from the WordPress.org repo.

**Comment by esamattis** [comment]
1.7.0 broke wp-graphiql for us since we install from Packagist but I guess we can just move to the [wp-packagist version](https://wpackagist.org/search?q=wp-graphql&type=any&search=) to get the pre-build version.


> I'm not fully sure if there's a way to do this, as Packagist.org picks up the package when a release is tagged. If theres some sort of "middleware" I can hook into between release on Github and Packagist getting the files, that would be one option to ensure the JavaScript app gets built and included in the packagist archive.

You could simulate the "middleware" with Github Workflows. Ex:

1. Trigger release by pushing to a `release/v1.7.2` **branch**
2. (run tests)
3. Build the app
4. Commit the build assets
5. Add `v1.7.2` tag (infer it from the branch name)
6. Push the commit and tag back to the repository
7. And Packagist will pick up the release from the tag

The cool thing about this is that the tag is not created if the build or test fails.

**Comment by jasonbahl** [comment]
@esamattis ya, that might be something to consider 🤔 

You could also add a `post-install-cmd` to your composer.json that runs `npm install && npm run build` in the wp-graphql plugin after install: https://getcomposer.org/doc/articles/scripts.md#command-events

**Comment by esamattis** [comment]
> You could also add a `post-install-cmd` to your composer.json that runs `npm install && npm run build` in the wp-graphql plugin after install: [getcomposer.org/doc/articles/scripts.md#command-events](https://getcomposer.org/doc/articles/scripts.md#command-events)

This feels a bit awkward solution because now you need to have node.js installed to install it with Composer  :/

I guess most people have it is installed but there are some caveats to consider:

- What if the user has too old node.js/npm version installed?
    - It would be pretty weird to get npm install errors from running `composer install` 😅 
- CI environments / Docker container builds might not have it
- The installation is slower

**Comment by justlevine** [comment]
Related: #1831

**Comment by justlevine** [comment]
>Another option, would be to update the documentation to guide users that install with composer, to install from wpackagist.org, which gets the built plugin from the WordPress.org repo.

While the docs should definitely be updated, I'm not sure if it's the best alternative to bundling with packagist - at least in the short term.  People who are already using composer are going to update at some point, and since they already had things working they're not going to check the installation docs.

Maybe we should log a composer warning  (e.g. with `packages.json` telling them to switch?

**Comment by jasonbahl** [comment]
ya....I'm thinking it probably makes the most sense to have some workflow build the JS and commit it back to the source during the release cycle. 🤔 

That way folks can still use composer without an npm build script to run, but folks that  want to work on the JS side of things can run the scripts to re-build, run in dev mode, etc. 

So, we'd be back to versioning the built files, but with better automation around it.

**Comment by jasonbahl** [comment]
I have a PR in progress for this. 

The plan:

- add the `build` directory & built assets for GraphiQL back to the repo 
- remove `post-install-cmd` from composer.json so that running `composer install` does not also run `npm ci && npm run build`
- Add a github workflow that checks to see if any given Pull Request or push to develop/master includes changes to `/packages` directory, and if so, run the `npm ci && npm run build` command, then commit the changes from that command back to the codebase
- leave the `build` directory in `.gitignore` so that contributors aren't including changes to these files in their PRs directly

**Comment by jasonbahl** [comment]
@esamattis @justlevine I've opened a PR to address this: https://github.com/wp-graphql/wp-graphql/pull/2332

Let me know what you think. Does this approach make sense?

**Comment by jasonbahl** [comment]
Ok, so we've got a Github action running for this now!

If changes are made to either `/build` or `/packages` directory, we run `npm ci && npm run build`, then commit and push the changes to the `/build` directory. 

This is triggered for pushes to `develop` and `master`, so any Pull Requests that are merged will get this treatment. 

So now `develop` and `master` should both be updated with the latest built GraphiQL, and therefore also included when folks install from Composer. 👏🏻 

The next release will be out shortly and folks should be able to update from Composer and have a functioning GraphiQL IDE again

**Comment by jasonbahl** [comment]
👋🏻  WPGraphQL v1.8.0 has been released and this should be resolved. You should be able to install WPGraphQL via composer and have GraphiQL included now without needing to run `npm install && npm run build`. 

If ya'll have issues with installing composer, please open another issue with steps to reproduce, and mention this issue for reference. 🙏🏻
