### ISSUE TITLE
Wrong hyperlink URL in Next.js

### ISSUE THREAD

**Issue by marco910** [wp-graphql/wp-graphql#2324]
On my WordPress website, I installed this plugin and use it to output the content on my Headless Next.js website.

In WordPress, I use Advanced Custom Fields and the Classic Editor, among others. When I place a hyperlink to another page of the WP website in the Classic Editor, the permalink of the linked site (or item) is placed as a link target. When I now query the page where I placed the hyperlink in the editor via the GraphiQL in the WP backend, I'm getting a `<a>` with the permalink as link target. So far, so good.

When I now query the same page with Apollo Client on my Next.js site, the link target is still the WP permalink, which won't work on the Next.js site.
Is this a bug that the link isn't replaced to a relative one, or do I have to build a custom solution?

(I'm using the same setup on another WP installation where I use the content to a Gatsby site. There it works and all hyperlink getting replaced.)

WPGraphQL Version 1.7.2
WordPress Version 5.9.2
Next.js Version 12.1.0

**Comment by justlevine** [comment]
Hey @marco910 

This is indeed intentional behavior. On its own WPGraphQL is fairly agnostic as to where your put your frontend, but the default assumption is that you're _replacing_ the WordPress frontend, and that you're maintaining the permalink structure you've configured in WordPress.

While Gatsby and other opinionated frameworks (headless-wp-starter, FaustJS) will overwrite the urls to fit their custom routing, if you're rolling your own you'll need to configure wordpress's permalinks. There's a lot of different ways to do this (setting `WP_HOME`, filtering `wp_rewrite`, str_replacing the post content to alter the html, and others), so implementation will depend on what your specific needs.

**Comment by marco910** [comment]
@justlevine The permalonk structures WP is already the same as on my Next.js site. So I only would have to remove the domain and protocol from the link to get the relative url. 
What's the easiest way to do that?

**Comment by justlevine** [comment]
In wp-config.php you can add `define( 'WP_HOME', 'http://myfrontend.com' );` to replace the base domain to frontend urls.
If you want to made all urls in the post/page content relative, you can use WP's `the_content` filter to `preg_replace` any `href` attributes. There are a few plugins in the WP Plugin  directory that will do this for you too.

**Comment by marco910** [comment]
Thanks, @justlevine 

For everyone having the same problem: I added this line of code to my Next.js site to replace the WP domain in the `href` of links
```
data.content.replace(/https:\/\/cms\.mydomain\.com/g, "");
```
It removes the CMS domain from all links, but does not replace the links with the next `Link` component. But I'm fine with that so far.
