### ISSUE TITLE
MenuItems should have a relative `uri`.

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wp-graphql#2362]
As a headless WordPress user, I'd like menu paths to be relative to the current WordPress site in order to manage multiple Faust frontends from a multisite using subdirectories.

### Current
<img width="1385" alt="GraphQL response showing multisite subdirectory prepended to path" src="https://user-images.githubusercontent.com/6676674/166810643-64b21e8f-b7d7-4f92-a8ab-158f9b17bc20.png">

### Expected
<img width="1385" alt="GraphQL response showing menu paths without multisite subdirectory" src="https://user-images.githubusercontent.com/6676674/166810714-51da5929-844b-48f1-8ef2-1931b88ea721.png">

## Environment

- **wordpress**: `5.9.3`
- **wp-graphql**: `1.8.0`
- **faustwp**: `0.7.7`

## Related Issues
- https://github.com/wp-graphql/wp-graphql/issues/259
- https://github.com/wp-graphql/wp-graphql/issues/1001

**Comment by justlevine** [comment]
Hey @josephfusco,
If I understand correctly, the issue isn't that the `path` has the subdirectory in it (it's supposed to be the directory path), but rather that `menuItems` don't have a `uri` field (i.e. a relative permalink).
Please let me know if I'm mistaken.

PS: I don't know your actual site config, but I'm assuming the `url` shouldnt be `localhost:3000/my-slug`, but `localhost:3000/my-subdir/my-slug`. If so that's definitely a bug. Can you confirm your subsite's home url (and test with faust disabled to see if the problem is with the plugin or with faust)?

**Comment by josephfusco** [comment]
@justlevine Correct, my semantics may be off with where the relative permalink should live, but the goal would be to have a a multisite subdirectory site be the primary backend for Faust/Next application without the subdirectory in the Next route.

I would agree with your observation that `localhost:3000/my-slug` should be `localhost:3000/my-subdir/my-slug` as the subdirectory exists in the URL with faustwp deactivated.

<img width="1192" alt="Screen Shot 2022-05-05 at 8 54 56 AM" src="https://user-images.githubusercontent.com/6676674/166927277-15b89bd4-43ef-4052-bb1c-4922b223dcc2.png">

**Comment by josephfusco** [comment]
See comment https://github.com/wp-graphql/wp-graphql/pull/2363#issuecomment-1119710067
