### ISSUE TITLE
ACF Sections for Flexible content not showing in the IDE since 1.7+

### ISSUE THREAD

**Issue by nhankla-kl** [wp-graphql/wp-graphql#2370]
Found a bug in the updated WpGraphQL 1.7.1 and ACF
We use Flexible Fields a lot and the updated WPGraphQL does not show the flexible fields in the scheme:
Vs 1.6.10

1.6.10
![Screen Shot 2022-03-08 at 9 40 55 AM](https://user-images.githubusercontent.com/67442303/167448732-a98f74eb-5ac5-49a9-bb43-9373c83b2ba2.png)

1.7+
![image](https://user-images.githubusercontent.com/67442303/167448737-1cfe838c-3aa4-488d-968a-d74100c74fff.png)

**Comment by rodrigo-arias** [comment]
Leaving a comment here, as this is still an issue.

**Comment by jensmercedesbenz** [comment]
Described issue still present in WPGraphQL 1.9.1

@justlevine What does the [status: awaiting reviewer response](https://github.com/wp-graphql/wp-graphql/labels/status%3A%20awaiting%20reviewer%20response) mean/refer to?

**Comment by justlevine** [comment]
@jensmercedesbenz in this context, it means someone with a deeper understanding of the codebase needs to figure what's causing this issue, so it can be addressed. 

Everyone is encouraged to do their own sleuthing to help us get to the bottom of this and ship a fix, the label just lets committees/maintainers know this could benefit from their 👀

**Comment by jensmercedesbenz** [comment]
Described issue still present in WPGraphQL 1.10.0 and with latest update to WPGraphQL for Advanced Custom Fields 0.6.1

I've tried doing some poking around on my own but without any real progress. Any good ideas or pointers on a good entry point or process to take on such an endeavour @justlevine ?

**Comment by justlevine** [comment]
@jensmercedesbenz I'm personally not all that familiar with `wp-graphql-acf`. In general, issues like these (i.e. missing GraphQL fields when upgrading to v1.7.0+) are due to the way types -especially those on an interface/union) get lazy-loaded. 
Depending on the specific implementation, the solution is usually to change the logic used to register the field/type, or if that fails (since it comes at a performance cost), to set the relevant config to `'eagerlyLoadType' => true`.

@jasonbahl should we move this issue to the ACF repo, so it doesn't get overlooked? (I don't have the necessary permissions or id do it myself).

**Comment by rodrigo-arias** [comment]
@justlevine maybe not be titled the same, but I think [this ACF issue](https://github.com/wp-graphql/wp-graphql-acf/issues/319) started at the same time so they may be related.

**Comment by jasonbahl** [comment]
This was fixed in release 1.13.0
