### ISSUE TITLE
Add hooks and filters for mutations

### ISSUE THREAD

**Issue by nickcernis** [wp-graphql/wp-graphql#2371]
### Feature request
The ability to alter the capabilities required to perform mutations on a given custom post type.

(Previously discussed in #2365.)

### Current situation
Changing capabilities to create or update a post is tricky today because permission checks are not easy to adjust — they're baked into the `mutate_and_get_payload` anonymous function in `wp-graphql/src/Mutation/PostObjectCreate.php`:

https://github.com/wp-graphql/wp-graphql/blob/c1c2255762394b5ec56ce6b8f6e56cbb212433b7/src/Mutation/PostObjectCreate.php#L200-L206

### Possible solutions
- Extract permissions checks for all mutations into a `permissionCallback` that runs at the beginning of the mutation logic (after type/input checking, but before mutations occur), and returns a filterable boolean to allow/deny the mutation.
- Wrap existing capabilities checks with filters.

Both options would need to pass in some contextual info (the mutation/post type they're acting on).

**Comment by jasonbahl** [comment]
WPGraphQL already has a layer kind of like this for fields.

For example, I can do the following: 

```php
add_action( 'graphql_register_types', function() {

	register_graphql_field( 'RootQuery', 'privateField', [
		'type' => 'String',
		'resolve' => function() {
			return 'some private data';
		},
		'auth' => [
			'callback' => function() {
				return current_user_can( 'edit_posts' );
			}
		]
	] );

} );
```

And if I query as a public user, I get `null` for the data and a UserError

![CleanShot 2022-05-13 at 12 22 14](https://user-images.githubusercontent.com/1260765/168344333-69b8eb11-30aa-474c-a10a-7f40580c6df5.png)

But if I execute as an authenticated user with `edit_posts` capability, I will see the field returned.

![CleanShot 2022-05-13 at 12 22 22](https://user-images.githubusercontent.com/1260765/168344418-ae6ce4a8-a5b9-4f09-a8aa-65efe35ab4e0.png)

I can use this same technique with mutations right now:

```php
	register_graphql_mutation( 'doSomethingPrivate', [
		'inputFields' => [],
		'outputFields' => [
			'somethingPrivate' => [
				'type' => 'String',
                                 // provide auth callback on a specific field of the mutation response
				'auth' => [
					'callback' => function() {
						return current_user_can( 'edit_posts' );
					}
				]
			]
		],
		'mutateAndGetPayload' => function() {
			return [
				'somethingPrivate' => 'something private'
			];
		}
	] );
```

And if I execute the mutation, you see I can't get the data in response:

![CleanShot 2022-05-13 at 12 29 59](https://user-images.githubusercontent.com/1260765/168345321-47fd7c93-cdef-4a57-a559-de342c18fe7e.png)

The problem here, though, is that this was applied on the response, not on the input. . .so the mutation would still execute, but the field `somethingPrivate` would be restricted from being returned in the response. 

Not what we want.

Instead, it would be good to apply this to the mutation itself, like so: 

```php
	register_graphql_mutation( 'doSomethingPrivate', [
		'inputFields' => [],
		'outputFields' => [
			'somethingPrivate' => [
				'type' => 'String',
			]
		],
                // provide an auth callback for the mutation as a whole
		'auth' => [
			'callback' => function() {
				return current_user_can( 'edit_posts' );
			},
			'errorMessage' => __( 'You do not have permission to "doSomethingPrivate"' ),
		],
		'mutateAndGetPayload' => function() {
			return [
				'somethingPrivate' => 'something private'
			];
		}
	] );
```

We can see that this auth callback isn't applied to the mutation right now 😢 . A public user can submit the mutation and get the response. 

![CleanShot 2022-05-13 at 12 33 04](https://user-images.githubusercontent.com/1260765/168345814-1d8d6545-4d04-4d6b-b903-98e61d834257.png)

But! With one small change to the `register_graphql_mutation` function (merge the $config with this array), we could get the same behavior working for mutations.

Like so:

![CleanShot 2022-05-13 at 12 38 11](https://user-images.githubusercontent.com/1260765/168346438-25e8245e-29c7-405c-af06-8a2d0e5ce54c.png)


-----

## Why isn't this used/documented more??

I know what you're thinking. Why has this feature of WPGraphQL flown under the radar for so long? This seems so useful!!

Well, it is useful, but it comes at a cost. 

This puts the logic at the field level, where it probably should live at a lower (Model) level. 

After using this pattern for some time, we came up with the Model Layer, which centrally decides what can/cannot be returned from a Model. 

This way, I can register many different fields that can access the same object in the Graph, and when the thing is loaded from the Model layer, the rules on what can/cannot be returned have been determined. 

This reduces a LOT of duplicate code. 

For example, let's say the Model Layer didn't exist and we did all this at the field level, then we'd be repeating ourselves a lot. 

Here's a simple contrived example, but I think you can easily spot the repetition that can get out of hand. 

```php
register_graphql_fields( 'Post', [
  'content' => [
     'type' => 'String',
     'auth' => [
         'callback' => function( $post ) {
             if ( $post->status === 'private' && ! current_user_can( 'read_private_posts' ) ) {
               return null;
             }
             return $post->post_content;
         }
     ]
  ],
  'trimmedContent' => [
     'type' => 'String',
     'description' => 'Content, trimmed to a certain length, just for demo sake',
     ''auth' => [
         'callback' => function( $post ) {
             if ( $post->status === 'private' && ! current_user_can( 'read_private_posts' ) ) {
               return null;
             }
             return function_to_trim_the_content( $post->post_content );
         }
     ]
  ]
] );
```

The Model layer came about to reduce the duplication. Fields that are used in different places in the graph can be centralized to the Model to determine whether it should be allowed or not. 

I believe this is where we should go with Mutations as well. 

I think there could be use cases where the Schema can benefit from this existing layer, but it could lead to a lot of overhead and duplicate logic running over and over. 

I'd like to see a Model layer for mutations come about, where we can do things like

```
$PostModel->create( $input );
$PostModel->update( $input );
$UserModel->create( $input );
$UserModel->update( $input );
```

And the logic to determine what can/cannot happen would happen more centrally. 

That way, if/when more specific mutations are introduced, for example (also contrived, but hopefully you get the idea): 

```
mutation updatePostTitle( $input: UpdatePostTitleInput ) { ... }
mutation likePost( $input: LikePostInput ) { ... }
mutation unlikePost( $input: UnlikePostInput ) { ... }
```

Instead of having to repeat ourselves and determine, at the mutation field level, what capabilities, etc are required to execute this mutation, it could happen at the Model layer and there would be a lot less repetition and a lot less maintenance. 

If the rules were defined at the Schema level, not the Model layer, then each of these 3 mutations would need to be updated to check if `current_user_can( 'do_whatever' )`, etc. 

I think we should explore what a Model Layer for mutations could look like, as I believe that will have the most impact. 

In the mean time, we can also pass the `$config` from `register_graphql_mutation` down to the mutation field so the current `auth` callbacks, etc will properly work, as demonstrated in my example above.

**Comment by justlevine** [comment]
> I think we should explore what a Model Layer for mutations could look like, as I believe that will have the most impact.

💯

That said, we can still make short-term gains in the interim by grouping some of existing server-side checks in a method wrapped with actions/filters, similar to the existing `prepare_{type}_object()` / `apply_filters( 'graphql_{type}_insert_post_args )` pattern already in use for _some_ mutations.

**Comment by jasonbahl** [comment]
Ya. I think there's for sure room for both!

**Comment by jasonbahl** [comment]
I'm going to open a PR to address what I suggested about passing the `$config` through to `register_graphql_mutation` so at least mutations can take advantage of the existing layer. 

We can/should still brainstorm and implement other patterns to handle pre-execution / post-execution checks AND still explore better centralization of things in a Model layer as that should reduce a lot of duplicate code and scaling issues. 

I'd like for plugins, etc to be able to filter a Model and it work for _all_ mutations vs having to specify one-off rules for _every_ mutation.

**Comment by jasonbahl** [comment]
@nickcernis this doesn't solve the larger problem, but this PR https://github.com/wp-graphql/wp-graphql/pull/2376 brings the existing `isPrivate` / `auth` callback layer that exists for fields, to work with the `register_graphql_mutation()` API

There's definitely more to be done!

**Comment by jasonbahl** [comment]
@nickcernis @justlevine also related: https://github.com/wp-graphql/wp-graphql/issues/965

**Comment by nickcernis** [comment]
@jasonbahl Nice progress, thanks so much for the PRs and info! It looks like the work left to solve this issue is to:

- Introduce the isPrivate/auth array values to existing create/update mutations.
- Add a filter to the auth callback to make it hookable.

I guess those could potentially be introduced in one PR, and I think it gives us the ability to change mutation capabilities at the custom post type level.
