### ISSUE TITLE
Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by igorluiza4d** [wp-graphql/wp-graphql#2436]
I'm trying to use wp-graphql and I'm getting this message. I figured it could be some plugin or theme that is getting in the way, so I tried to test it with a pure wordpress and I kept getting this message.

Again I tried to do another test, but now with all new installations but the same problem.

Within Wordpress I can do the searches, but via code ( NEXTJS ) it displays the message.

Here is the configuration of my last test:

- Wordpress: 6.0
- WP GraphQL: Version 1.8.6
- Web Server: NGINX (tested with apache and had the same problem)
- PHP: 7.4.1
- MySQL: 8.0.16

My codes:

```js
// apollo.js
import { ApolloClient, InMemoryCache } from "@apollo/client";
export const client = new ApolloClient({
  uri: `${process.env.NEXT_PUBLIC_WORDPRESS_API_URL}/graphql`,
  cache: new InMemoryCache(),
  headers: { Accept: 'application/json' }
});

// index.js
  const response = await client.query({
    query: GET_POSTS,
    context:{
      headers: { Accept: 'application/json' }
    }
  })
```

**Comment by tsdexter** [comment]
do you have any `actions` or `filters` that output HTML straight to the output buffer? For example, when we got the same error on our install, it was because we had a gravity-forms filter that output a script tag to the page....only for pages with an embedded gravity form so we didn't notice it when playing around in GraphiQL but when we tried to call for "all pages" or a specific page with a form then we got the error

Here's an example of what we had:

```
add_filter('gform_pre_render', 'gw_first_error_focus');
function gw_first_error_focus($form)
{
    add_filter('gform_confirmation_anchor_' . $form['id'], '__return_false'); ?>
<script type="text/javascript">
  if (window['jQuery']) {
    (function($) {
      $(document).bind('gform_post_render', function() {
        var $firstError = $('li.gfield.gfield_error:first');
        if ($firstError.length > 0) {
          $firstError.find('input, select, textarea').eq(0).focus();
          document.body.scrollTop = $firstError.offset().top;
        }
      });
    })(jQuery);
  }
</script>
<?php
 return $form;
}
```

**Comment by justlevine** [comment]
Hey @igorluiza4d ,

Have you sorted this out yet?

As @tsdexter noted, unexpected tokens in json is usually when something gets printed instead of returned. This happens most commonly when you have a fatal PHP error somewhere in your code.

Please follow the debugging steps [here](https://www.wpgraphql.com/docs/debugging/#unexpected-token-in-json-at-position-0), and if you're still stuck, let us know 😎

**Comment by justlevine** [comment]
@igorluiza4d I'm closing this for now, but if you're still experiencing this issue, please comment (along with the requested info) and we'll reopen
