### ISSUE TITLE
"You do not have permission to request a User by Username"

### ISSUE THREAD

**Issue by AcidBurnHen** [wp-graphql/wp-graphql#2493]
### Description

Trying to query the user by username 

### Steps to reproduce

I am trying to create a hook to check if a user already exists before I do login/register on my website.

Example of a query that throws the error:
```
query MyQuery {
  user(id: "imagine_a_username_here", idType: USERNAME) {
    id
  }
}
```

The error message:
`"message": "You do not have permission to request a User by Username"`

Querying by Email also throws the same error.

I tried deactivating other plugins, and the bug is still there.

### Additional context

If this is meant not to work for unauthorized requests I think it should still work for me on the Query Composer as I have the Super Admin role. 

### WPGraphQL Version

1.9.1

### WordPress Version

6.0

### PHP Version

8.0

### Additional enviornment details

I am building this in SolidJS but don't think that the problem is with the frontend framework, as this issue was thrown in the Query Composer when I tried to send a request over Postman. ,

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @AcidBurnHen 

> If this is meant not to work for unauthorized requests I think it should still work for me on the Query Composer as I have the Super Admin role.

Users indeed require one to be logged in with the proper permissions before querying. 
Can you confirm that you are running your queries in GraphiQL as an authenticated user? (note the green dot on the profile image. If you dont have one, just click the profile image to toggle)

![image](https://user-images.githubusercontent.com/29322304/187774720-cc189b94-025f-4d7f-a5c5-84cc5d5b3c0b.png)

> I am trying to create a hook to check if a user already exists before I do login/register on my website.

*PS*:  the register mutation [should already throw an error if the user exists](https://github.com/wp-graphql/wp-graphql/blob/de26556e3ca0121227dad822cb775e37787db223/src/Mutation/UserRegister.php#L104). Would assume whatever is handling your login mutation is doing the same, but if it doesnt, a much better approach from a lifecycle POV would be to use one of WPGraphQL's hooks to check and throw an error on the server side for those mutations, instead of forcing multiple server <-> client trips.

**Comment by AcidBurnHen** [comment]
Alright, thank you.
