### ISSUE TITLE
Lazy-loaded interfaces are missing from GraphiQL

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2598]
### What problem does this address?

Lazy-loading GraphQL types is a powerful tool for performance. Currently, however, types are lazy-loaded in the GraphiQL IDE, leading to them being missing from the Query Composer / Documentation Explorer, IDE linting, even though the actual query/mutations work fine.

This issue is particular annoying when it comes to building up types with interfaces.

See https://github.com/wp-graphql/wp-graphql/issues/2287#issuecomment-1295415546

### What is your proposed solution?
If the source of this problem is inherent to lazy-loading, then the GraphQL IDE should eagerly load the entire schema so all registered types can be looked-up/referenced without sacrificing the performance of actual GraphQL queries/mutations.

Additionally [existing interfaces](https://github.com/wp-graphql/wp-graphql/search?q=eagerlyLoadType) should be reviewed to see if they _actually_ need to be eagerly-loaded for queries to work, and not just for display in the IDE.

### What alternatives have you considered?

Setting `$config['eagerlyLoadType']` to `true`. IMO this is improper usage of this property, and can have major performance impacts when [exposing complex graphql types composed of lots of interfaces](https://github.com/harness-software/wp-graphql-gravity-forms/pull/273).

### Additional Context

While alone, this might result in a longer first-load of the IDE, this can be mitigated/optimized via better caching/invalidation, or even first loading the lazy-version of the schema, and then replacing it in the background with the full eagerly-loaded version.

**Comment by jasonbahl** [comment]
@justlevine `eagerlyLoadType` does the 2nd thing documented here: https://webonyx.github.io/graphql-php/type-definitions/interfaces/#prevent-invisible-types

![CleanShot 2023-07-20 at 09 14 32](https://github.com/wp-graphql/wp-graphql/assets/1260765/62cada79-00e8-4c09-921d-92031035a5cd)

Are you suggesting that when the GraphiQL IDE makes an introspection query, we detect some context about the request set `eagerlyLoadType => true`, but for "normal" requests we leave it false? 🤔

**Comment by justlevine** [comment]
@jasonbahl I might be misunderstanding the API and/or misusing the terminology so bear with me 😅

- Lazy-loaded types: both interfaces and their resulting children don't always appear in GraphiQL Query Composer or as linting hints, or sometimes in the Docs explorer (actual validation once fully typed out works usually).
- Ultimately the goal of this issue is to get those types exposed in the IDE.
- My assumption is that while lazy-loading is a desired perf enhancement, schema completeness is more important in an IDE setting. As such my solve is to turn off type lazy loading on the IDE, but I might have coupled that too much with the actual issue and I'm open to other solutions.
- I did a search of the codebase, and the only place I see `'types'` as a config key is with [WPUnion types](https://github.com/wp-graphql/wp-graphql/blob/e3940e380d64bb643129c5099698128b7c17ad5c/src/Type/WPUnionType.php#L42) where it's set manually or via the Union's `get_possible_types()` callable. I don't see it used on interfaces at all.
- What I _do_ see `eagerlyLoadType` do is [queue up those types separately](https://github.com/wp-graphql/wp-graphql/blob/e3940e380d64bb643129c5099698128b7c17ad5c/src/Registry/TypeRegistry.php#L682), so my assumption is _that's_ the behavior that needs to change when GraphiQL is hydrated with the schema.

If the solution is as simple as exposing and setting the `'types'` value on interfaces the way we do unions, then I'm all for that.

**Comment by jasonbahl** [comment]
So `eagerlyLoadType` was introduced to solve the "Invisible Types" problem (https://webonyx.github.io/graphql-php/type-definitions/interfaces/#prevent-invisible-types)

When a Type exists in the Schema but is not defined as a direct resolveType of a field, the type is "invisible" to the Schema. 

i.e. in the case of WPGraphQL Content Blocks, there's no field that directly returns a `CoreParagraph` block or a `CoreImage` block.  Instead, these Types implement the `EditorBlock` Interface and the `editorBlocks` field returns that interface. 

Because these Types are not directly returned by any field in the Schema, they are "invisible". As far as I am aware, this doesn't impact resolution, just tooling that makes use of introspection queries. 

The introduction of `eagerlyLoadType` was to allow Types (such as Blocks) to register themselves as eagerlyLoaded so that they'd be able to be returned to introspection even they're not directly referenced as a resolveType of a field. 

I believe we _might_ be able to somehow identify if the query being made is an introspection query, and if it is, let the value of `eagerlyLoadType` be what it is, but if it's a standard, non-introspection query, we set `eagerlyLoadType` to false for _all_ types. 

🤔

**Comment by jasonbahl** [comment]
> If the solution is as simple as exposing and setting the 'types' value on interfaces the way we do unions, then I'm all for that.

I don't know if it is that simple, largely because any Type can implement any Interface, where Unions could not be "implemented" 

So, to be part of a Union, you have to modify that Union directly. There's more of an explicitness where the Union knows all the possible types. 

To be part of an Interface, any Type can implement the interface, so the Interface itself doesn't exactly know ahead of time what Types have implemented it.

**Comment by jasonbahl** [comment]
@justlevine with the work done in https://github.com/wp-graphql/wp-graphql/releases/tag/v1.28.0, is this still an issue?

**Comment by justlevine** [comment]
Yup #3172 means you don't need to worry about the performance hit of setting the type to load eagerly.

I still wonder why/whether there's a benefit to having to manually set eagerlyLoadTypes to get interfaces into the Query Composer, but 🤷
