### ISSUE TITLE
Tests for preflight OPTIONS requests

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#260]
We accidentally broke some things in some clients since they sometimes send preflight requests to GraphQL in the form of an `OPTIONS` request. This was fixed in #257 but we should also write some unit tests for this to make sure we don't break this again in the future.

**Comment by jordancrawfordnz** [comment]
I'll take this one!

**Comment by jordancrawfordnz** [comment]
I'm having some trouble with this, as I mentioned in Slack.

I'm trying to set the `REQUEST_METHOD` to `OPTIONS`. What I have so far (seems to just crash the test because I guess you can't just set things in `$_SERVER`), here is what I have so far:
https://github.com/jordancrawfordnz/wp-graphql/commit/a2166748b60ae2a562f5f1db232fbd24ea47eab5

Any thoughts?

**Comment by jordancrawfordnz** [comment]
@jasonbahl, thanks for your comment on my commit, but as I mentioned in this issue, it isn't actually working because setting the `REQUEST_METHOD` in the way I'm doing (trying to set a property on `$_SERVER`) means the test doesn't run at all.

Any thoughts?

**Comment by jasonbahl** [comment]
Now that we have functional testing up and running via Docker / Codeception, this should be much easier to test now. 

We should be able to send a real HTTP request with OPTIONS specified and make sure the response is what we expect.
