### ISSUE TITLE
No  was found with the ID: post

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#267]
When I tried to fetch a single post by its ID I got the error message below:

![screenshot_42](https://user-images.githubusercontent.com/4064582/31641226-a0513cfa-b33f-11e7-8861-02b7ee961e0a.jpg)

**Comment by towfiqi** [comment]
Try this:

`query{
	postBy(postId:1851){
    title
  }
}`

**Comment by cr101** [comment]
That's confusing because I thought that the param `id` was referring to the ID of the post I was trying to retrieve as it's shown below:
![screenshot_43](https://user-images.githubusercontent.com/4064582/31654733-55285aee-b383-11e7-9320-8be96ca2e2c4.jpg)

If you look at `function resolve_post_object` which generated the error the comments say:
`@param int    $id        ID of the post you are trying to retrieve`

**Comment by towfiqi** [comment]
id field is reserved for graphql, you should use postId.

**Comment by jasonbahl** [comment]
@cr101 the IDs are a global ID per the relay spec, so that they can be globally unique in a client side cache. If the ID was just `1`, or `2`, etc, there could be multiple entities with conflicting IDs. . .the entity with id `1` could be a user or a post or whatever else. By using Global IDs, which are base64encoded strings that combine the Type and it's Database ID `(post:2)` `(user:2)`, etc... client caches are able to store entities without conflict.

By keeping the IDs opaque this also gives some freedom to the server to change how IDs are generated in the future if more info is needed to make it truly globally identifiable.

When the Global ID is passed back to GraphQL, it gets base64decoded and the database ID is then passed to `function resolve_post_object` as you were seeing, so the Docblock comment `@param int $id ID of the post you are trying to retrieve` is still accurate there.
