### ISSUE TITLE
uri field is null when querying the page for posts uri

### ISSUE THREAD

**Issue by shrenik9** [wp-graphql/wp-graphql#2823]
### Description

I can not longer grab uri attribute of the posts page using the page query. I'm using latest version on wp-graphql still getting this issue.

### Steps to reproduce

1. Settings->Reading
2. Change Static Page for Posts page to : Blog
<img width="537" alt="Screenshot 2023-05-24 at 9 30 10 PM" src="https://github.com/wp-graphql/wp-graphql/assets/16605433/5c55415b-756b-4b88-815e-a2d5495b1af2">

1. Go to GraphQL IDE
<img width="984" alt="Screenshot 2023-05-24 at 9 31 05 PM" src="https://github.com/wp-graphql/wp-graphql/assets/16605433/2607a7ce-4e76-4800-bedd-ee482c1e14d4">

3. Run below query
`query MyQuery {
  pages(first:1000){
    edges{
      node{
        uri
       slug
        __typename
      }
    }
  }
}`
4. Query will return below response
`{
  "data": {
    "pages": {
      "edges": [
        {
          "node": {
            "uri": "/",
            "slug": "home",
            "__typename": "Page"
          }
        },
        {
          "node": {
            "uri": null,
            "slug": "blog",
            "__typename": "Page"
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}`
5. Blog's uri value coming null

### WPGraphQL Version

1.14.3

### WordPress Version

6.2.2

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@shrenik9 thanks for opening this issue and providing detailed context. 

I don't believe this is a bug. 

If you set the posts page, as you have done, then the page object itself doesn't actually have a uri. There's no public facing url that you can use to navigate to that page. Instead, the uri `/blog` would take you to the blog archive, which in GraphQL would be a `ContentType`. 

For example, if I leave my settings like so:
 
![CleanShot 2023-05-24 at 13 38 09](https://github.com/wp-graphql/wp-graphql/assets/1260765/d844d9bf-90df-4a66-8eb1-9f88ce4e80e7)

Then create a "Blog" page, I can visit the page at `/blog` and we can see that a non-headless WordPress theme identifies this url as a page. 

![CleanShot 2023-05-24 at 13 37 44](https://github.com/wp-graphql/wp-graphql/assets/1260765/cd326f43-b732-4348-b25e-25660ef552e9)


And we can query this in GraphQL like so: 

```graphql
{
  nodeByUri(uri: "/blog") {
    __typename
    uri
  }
  pages {
    nodes {
      __typename
      id
      uri
    }
  }
}
```

and see results like so: 

![CleanShot 2023-05-24 at 13 40 02](https://github.com/wp-graphql/wp-graphql/assets/1260765/f76bfc5c-b38c-4447-a4e1-e0dcfca5b0d3)

The Blog "page" has a uri of `/blog` and we can also get to that page by querying with `nodeByUri`. 

However, if we switch our settings to the following:

![CleanShot 2023-05-24 at 13 41 20](https://github.com/wp-graphql/wp-graphql/assets/1260765/5a7e0af6-64a6-4d0b-a4cf-14662f6ab52d)

Then visit the `/blog` url, we will see that the non-headless WordPress theme returns an archive of posts, and not a page. 

![CleanShot 2023-05-24 at 13 42 47](https://github.com/wp-graphql/wp-graphql/assets/1260765/964e9ca3-8cda-40b1-8be0-5bf817f11b16)

The `/blog` uri doesn't represent a page anymore when you change the reading settings.

Thus, GraphQL is correctly returning `null` for the `/blog` page, because that page doesn't actually have a `uri` that it can be accessed from. The URI now belongs to the Post `ContentType`. 

Our GraphQL query now returns a `ContentType` for the `nodeByUri` query, matching the behavior we get when asking for the `/blog` url in the browser and letting a WordPress theme resolve. 

![CleanShot 2023-05-24 at 13 44 57](https://github.com/wp-graphql/wp-graphql/assets/1260765/4656de97-ae2c-4606-be53-251f5a6c88d8)

**Comment by shrenik9** [comment]
Okay but in previous version we are able to get this URI. only in new version it is coming null. @jasonbahl

**Comment by justlevine** [comment]
@shrenik9 this was fixed in [v1.10.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v1.10.0) released last September.

**Comment by shrenik9** [comment]
@justlevine yes correct but in latest version 1.14.3 it's coming null.

**Comment by justlevine** [comment]
Again, as Jason said it _should_ be returning null  if you're treating it like a `Page` when you have it set up as a `ContentType`.

Before v1.10.0, the uri would _incorrectly_ leak a value - this was a bug that was corrected in v1.10.0 when it was released a year ago, and is the behavior for all the releases since.

In general, if you're updating from such an old release version, I suggest you review the changelogs. There might be some other bugfixes you may have been unintentionally relying on as features.

**Comment by jasonbahl** [comment]
What version? 

And it's a bug that was fixed. 

URI means unique resource identifier. 

2 nodes (a Page and a ContentType) both having the same uri is a bug. 

If you want the field to resolve differently for your site and allow 2 different nodes to both return the same `uri`, you can filter the resolver for the `uri` field on the Page type.

**Comment by justlevine** [comment]
> If you want the field to resolve differently for your site and allow 2 different nodes to both return the same `uri`, you can filter the resolver for the `uri` field on the Page type.

@shrenik9 here's a code example
https://github.com/wp-graphql/wp-graphql/issues/2486#issuecomment-1232169375

**Comment by shrenik9** [comment]
Thank you for clearing my doubt @jasonbahl and @justlevine
