### ISSUE TITLE
Users with the role "subscriber" are not added comments in the admin panel

### ISSUE THREAD

**Issue by MaximProger** [wp-graphql/wp-graphql#2885]
### Description

Hello! Comments are not added to the admin panel from users with the "subscriber" role. If you send them through administrator or without specifying e-mail, everything is ok. How can I make it so that a user with any role can leave a comment?

### Steps to reproduce

![image](https://github.com/wp-graphql/wp-graphql/assets/34797426/606b80c6-72eb-44a6-9aba-766d2231bb59)

### WPGraphQL Version

1.14.7

### WordPress Version

6.1.3 

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @MaximProger thanks for taking the time to report this.

1. I see youre running older versions of both WordPress and WPGraphQL, can you confirm using the latest 6.2.2 and 1.14.10 (respectively)?

2. I'm not sure I follow what the actual issue is, and for the steps to reproduce you only left a screenshot of a mutation _successfully_ submitting a comment. Can you please add detailed reproduction steps (including what the _expected_ behavior should be), and while you're at it clarify what you mean by "admin panel"?

3. Lastly, I see you have GraphQL debugging disabled. Please make sure you follow the [WPGraphQL Debugging steps](https://www.wpgraphql.com/docs/debugging), and make sure to check (and share) any issues getting logged in `debug.log` or returned in the GraphQL response. 

Once we have this information, we can try to replicate and provide a fix if necessary. 🙏

**Comment by MaximProger** [comment]
@justlevine 

1. I have updated WordPress to 6.3 and WPGraphQL to 1.14.10.

**Comment by MaximProger** [comment]
@justlevine 

1. I have updated WordPress to 6.3 and WPGraphQL to 1.14.10.

2. I'm running a mutation on creating a comment. If I specify the e-mail of a user who has the "subscriber" role, the comment is not created.

**Comment by jasonbahl** [comment]
I think in order to reproduce, we'd at least need to know more about your site's settings under "Settings > Discussion". 

Here's my settings: 

![CleanShot 2023-10-10 at 10 36 31](https://github.com/wp-graphql/wp-graphql/assets/1260765/7126c7f3-754d-4f72-b83f-bbc9c7bbe74a)

And when I execute the mutation:

![CleanShot 2023-10-10 at 10 35 22](https://github.com/wp-graphql/wp-graphql/assets/1260765/42ba62e0-bbf8-4107-99c3-71914ea1bc44)


I am able to see a comment in WordPress awaiting moderation: 

![CleanShot 2023-10-10 at 10 34 31](https://github.com/wp-graphql/wp-graphql/assets/1260765/17b5300c-87e5-4206-9154-3ee3c511d3f3)

I am not able to query for the comment and see it publicly, because it has not been approved yet

**Comment by justlevine** [comment]
Hey @MaximProger , it's been a few weeks since we last heard from you, so I'm going to go ahead and assume that you're sorted (and most likely were able to find the "missing" comments awaiting approval on the backend).

If you're still struggling with this, please reply with [more details](https://github.com/wp-graphql/wp-graphql/issues/2885#issuecomment-1755810905) about your config, and we'll be happy to reopen this ticket and try again to replicate.
