### ISSUE TITLE
Unable to query menuItems from "UTILITY" menu location with Apollo (works in GraphiQL)

### ISSUE THREAD

**Issue by brockduncan** [wp-graphql/wp-graphql#2970]
### Description

Added Utility menu to Utility menu location
<img width="730" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/22098339/4dcd5f23-c7a3-4591-8b7b-1d1267deff62">

I have this menu location returning menu items here
<img width="1110" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/22098339/ffd02fb1-f995-45a2-99d4-91bb0db714e7">

However this query isn't working in my NextJS header
<img width="459" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/22098339/21fe0707-8d2f-41d8-abf0-b37f726f28a4">

<img width="858" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/22098339/3d866f06-de27-45a5-a974-c82b21cf6066">

### Steps to reproduce

1. Added Utility menu to Utility menu location
2. Query menuItems where location: UTILITY 

### Additional context

I feel like I'm missing something obvious here since it works in the GraphiQL IDE... but I've searched and can't find anything so here we are.

### WPGraphQL Version

1.17.0

### WordPress Version

6.3.0

### PHP Version

8.0

### Additional environment details

<img width="664" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/22098339/56722d28-e634-4db3-a36c-6a81e468ee32">

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @brockduncan , couple ideas:
1. Have you regenerated Apollo's possible types / GraphQL codegen / etc since you added the `Utility` location? It's a breaking schema change so if you don't, your tooling won't know what to look for.
2. This is just a shot in the dark, but any chance it works if you rename it to something other than `Utility`? Between Apollo and Faust you got some things preprocessing your schema, could be that's a reserved keyword causing a conflict?

If it's working on the backend, then my guess is that the issue is on the Faust side of things (and their discord/repo would be a better way to get help), but hopefully the above will point us in the right direction

**Comment by brockduncan** [comment]
@justlevine thanks!! Good shot in the dark. I changed the menu location name to "HeaderTop" and it works now.

**Comment by justlevine** [comment]
In that case, it definitely sounds like something to report over to faust. 

CC @blakewilson

**Comment by blakewilson** [comment]
Hey @brockduncan, did you try generating possible types after you created this new menu?

```
faust generatePossibleTypes
```

**Comment by brockduncan** [comment]
@blakewilson yep, I did run after creating "Utility" and it didn't fail but also didn't seem to fix the issue. I ran it again after creating the "HeaderTop" menu as well and then it worked.
