### ISSUE TITLE
How can we add comment to an existing post using mutation?

### ISSUE THREAD

**Issue by wpgraphqladmin** [wp-graphql/wp-graphql#307]
@jasonbahl  We can see fields under query section for getting data from comment section. like that how can we insert a comment against apost using mutation

Thanks in advance. Please help us to achieve this.

**Comment by jasonbahl** [comment]
@wpgraphqladmin we haven't built the mutations for comments yet. 

We're trying to work on it soon, but I don't have a solid ETA yet. If you're interested in working on it, it's still an open issue labeled "Help Wanted": https://github.com/wp-graphql/wp-graphql/issues/8

Otherwise you could also just filter in specific mutation support for your immediate needs using some of the techniques showcased here, just utilizing WP core functions to read and write comments back to the database: https://github.com/wp-graphql/wp-graphql/issues/299#issuecomment-342845257

I'm going to close this issue as we still have #8 open.
