### ISSUE TITLE
WPGraphql fetching duplicated nodes in Gatsby

### ISSUE THREAD

**Issue by maghaffar** [wp-graphql/wp-graphql#3105]
### Description

I am using WPGraphql with Gatsby and it is fetching duplicate nodes in a taxonomy type from wordpress. It replaces one original node with duplicated node and i am having a bad time due to this.
![Screenshot from 2024-04-25 16-50-34](https://github.com/wp-graphql/wp-graphql/assets/98881071/73864c2f-9b72-4151-82de-33650d9ed5a6)

### Steps to reproduce

I can't provide steps to reproduce due to certain issues.

### WPGraphQL Version

1.6.10

### WordPress Version

5.8.2

### PHP Version

7.3.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @maghaffar 

Afaik both `gatsby-source-wordpress` and it's companion `wp-gatsby` have been all but discontinued.

I'm not entirely sure what "bug in WPGraphQL" [that error message is referring to](https://github.com/gatsbyjs/gatsby/blob/89cb1292f3c8524a53fdbb109f5c400b4a2a62e9/packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js#L124), but there's been a lot of improvements to pagination on the WPGraphQL side of things, so it's hard to know at a glance if it's still relevant.

Sadly, there's not much we can do without the ability to replicate, and even less when it involves a 3rd party extension. I'd recommend trying your luck by [opening an issue in GatsbyJS](https://github.com/gatsbyjs/gatsby/issues), but they'll likely also require some form of replication steps in order to address.

**Comment by justlevine** [comment]
PS: I've marked this ticket as `invalid?`. This doesnt imply that _your issue_ is isn't real, but rather indicates that its likely beyond the scope of WPGraphQL core, and therefore not actionable by the maintainers using GitHub's bug tracker.

**Comment by maghaffar** [comment]
> PS: I've marked this ticket as `invalid?`. This doesnt imply that _your issue_ isn't real, but rather indicates that its likely beyond the scope of WPGraphQL core, and therefore not actionable by the maintainers using GitHub's bug tracker.

@justlevine Actually this was the problem with WPGraphql 1.6.10. When I upgraded to 1.24 the latest version, the error was gone. But the latest version is causing another problem. First after some minutes, WPGraphql is roll backed to its previous 1.6 version. I don't know why?. And second it is causing an error, I am attaching ss.
![Screenshot from 2024-04-26 11-04-19](https://github.com/wp-graphql/wp-graphql/assets/98881071/5da5bd68-105e-4f5b-be2e-104ecea60398)
![Screenshot from 2024-04-26 11-03-31](https://github.com/wp-graphql/wp-graphql/assets/98881071/d5692a5b-3761-438d-8aa7-b499360f3b9a)
The above errors are gone with 1.6 and when I upgrade to 1.24, they happen again on Netlify

**Comment by justlevine** [comment]
Thanks @maghaffar for the additional context 🙇

Those errors in red indeed point to an issue in _Gatsby_. [V1.16.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v1.16.0) fixed numerous stability issues with resolvers, leading to issues with plugins who were using features as bugs or otherwise incorrectly implementing the Relay Pagination spec.

As mentioned, Gatsby's WordPress solution has been mostly abandoned for quite a while (with Gatsby itself following suit more recently). It's possible people in the `#gatsby` channel on WPGraphQL slack have found workarounds (I suggest you check/ask there), but the likelihood of an official fix in `gatsby-source-wordpress` is slim to none.

(The errors in white are either unrelated, or a similarly sourced side effect. Your OP said you weren't using any other plugins; if that's indeed true then you should take a look whatever custom code you're using to expose `Product` types to the schema. If you _are_ using an extension, I'd suggest trying to replicate those queries in _WPGraphQL_'s IDE (_not_ Gatsby's GraphQL endpoint) to see how the plugin's schema has changed and what fields are currently available, and rule out any issues from Gatsby's automagical transformations.

**Comment by justlevine** [comment]
@maghaffar it seems you found the related issues over in #1116 and the even more relevant https://github.com/gatsbyjs/gatsby/issues/37729, so I'm going to go ahead and close out this bug report, since as mentioned there's nothing we can really do to address bugs in 3rd party code, and to keep all the relevant conversations in one place in the hope they actually can become actionable by the relevant external plugins.

Please free to open any future bug reports you discover in WPGraphQL's core plugin as issues in this repository, and to ask for usage support over in GitHub Discussions or the relevant Slack channel.

**Comment by TylerBarnes** [comment]
👋 @maghaffar I'm the former maintainer of WPGatsby and `gatsby-source-wordpress`. 
Some context on the two errors seen above:

1. The "duplicate IDs" error happens when WPGraphQL pagination is broken - this is usually due to a WPGraphQL PHP extension plugin not working properly with the latest WPGraphQL due to changes in how WPGraphQL pagination works _or_ a similar reason like custom PHP site code doing something it shouldn't. We've seen that many times with WPGraphQL over the years whenever pagination logic in WPGQL changes, or when plugins do something weird, hence why I added that error message.

2. The interface error is either one of two posibilities (or both?). graphql-js seems to be more strict than graphql-php about properly implementing interface types. I've seen that before in the past, and it seems odd that `Interface field WordpresswpHierarchicalContentNode.lastEditedBy expects WordpressWpContentNodeToContentTypeConnectionEdge` but it's a different type, as those types aren't hardcoded in `gatsby-source-wordpress`. Or WPGraphQL made a breaking change in a minor release because the change wouldn't effect most users (ie it probably didn't change anything for any non-gatsby users).

In any case, what @justlevine said is true, there is no one maintaining `gatsby-source-wordpress`. I recodmmend pinning to an older WPGraphQL version and looking at migrating off of `gatsby-source-wordpress`

However, pre V1.0 of WPGraphQL, these errors in Gatsby actually revealed a ton of bugs in WPGraphQL because Gatsby essentially acts as a giant integration test of the entire WPGraphQL schema. So if I was a WPGraphQL maintainer, I wouldn't investigate this issue to fix Gatsby, but I would to make sure WPGQL is actually working properly.

**Comment by justlevine** [comment]
Thanks as always @TylerBarnes for those details - especially the explanation of that error message!

> Or WPGraphQL made a breaking change in a minor release because the change wouldn't effect most users (ie it probably didn't change anything for any non-gatsby users).

This is a particular important note. I know two minors since v1.6 in 2021 that accidentally broke b/c just off the top of my head, and then of course the Relay pagination enforcement fix that had a significantly more breaking impact than expected on all of those `id: Int` nodes 😳. We've since become a lot better about enforcing SemVer and have significantly increased test coverage, but theres still gaps we need to look out for.

> So if I was a WPGraphQL maintainer, I wouldn't investigate this issue to fix Gatsby, but I would to make sure WPGQL is actually working properly.

So much this. 

@maghaffar I want to be super clear (in case I came off otherwise) that I'm not trying to dismiss your issue. We track discussions on closed bug reports the same as open ones. My sole intent was to consolidate the bug tracking to the preexisting issue you found that has more actionable context while pointing you to the ideal support channels where people can help walk you through finding a solution to your particular issue or at the very least help you generate some more context to your issue can become actionable. Again, so sorry if I came off otherwise!
