### ISSUE TITLE
CoreTable column alignment returns null

### ISSUE THREAD

**Issue by brysonchiu** [wp-graphql/wp-graphql#3128]
### Description

The core table block is returning null values for cell alignment even when it is set.  The cell alignment is instead set by the whole table alignment. This seems like a mistake.

### Steps to reproduce

1. Add a core table into a page and adjust the alignment on a **column** (not the alignment of the table).
2. Add this into your page query:
`editorBlocks {
      ... on CoreTable {
        anchor
        apiVersion
        attributes {
          body {
            cells {
              align
            }
          }
          foot {
            cells {
              align
            }
          }
          head {
            cells {
              align
            }
          }
        }
      }
    }`

### WPGraphQL Version

1.25.0

### WordPress Version

6.5.3

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @brysonchiu ,

Blocks are not yet a feature in WPGraphQL core, so that core table block must becoming from some extension.

There's several Gutenberg extensions for WPGraphQL out there, but since you didn't fill out the Issue Template, I'm not sure where to direct you. Perhaps https://github.com/wpengine/wp-graphql-content-blocks ?

Whichever the plugin, I suggest opening up a bug request there 🍀

(Marking this as `invalid?` not to imply that your issue is invalid, but rather because we can't fix bugs in code that isn't in our codebase)

**Comment by brysonchiu** [comment]
Aw yes, thanks @justlevine .  I forgot I have WPGraphQL Content Blocks by WP Engine installed as well.  Ill reach out to them. Thanks!
