### ISSUE TITLE
Create post as a public user

### ISSUE THREAD

**Issue by Starlette** [wp-graphql/wp-graphql#3156]
### What problem does this address?

I can't create a post from a form in my headless WordPress app because I'm not authenticated.

### What is your proposed solution?

I want to be able to create a post without being authenticated.

**Comment by josephfusco** [comment]
Hey @Starlette, instead of using the createUser mutation, public users can use the [registerUser mutation](https://www.wpgraphql.com/docs/users#register-user).

Note "anyone can register" needs to be enabled under WordPress general settings.

I'm going to close this as this is already a supported feature. 🙌🏼
