### ISSUE TITLE
CommentAuthor no longer returning the name set in comment_author for comments by non-anonymous users

### ISSUE THREAD

**Issue by amxmln** [wp-graphql/wp-graphql#3197]
### Description

Querying the `name` field of a comment author used to return the name set in the `comment_author` field in the `wp_comments` database, it no longer does if the comment was created by a logged in user from the WordPress Admin-Panel. Instead, it always returns the name of the user.

I understand that the node returned by `CommentToCommenterConnectionEdge` can either be a `User` *or* a `CommentAuthor`, but I think if there is a name set in `comment_author` querying the `name` field should always return that value.

This seems to be how it used to work, as we’ve been adding a generic team name to our replies to anonymous comments and until recently (probably v1.27.0) got the team name back in the query, not the name of the WordPress user.

### Steps to reproduce

1. Add a comment in the WordPress Admin Panel
2. Change the `comment_author` field to `'Generic Team'` by editing the comment in the Admin Panel
3. Note the Comment’s ID
4. In the GraphQL IDE execute the following query:

```graphql
query {
  comment(id: [the ID of the comment], idType: DATABASE_ID) {
    author {
      node {
        name
      }
    }
  }
}
```

The expected result should be the following:

```json
{
  "data": {
    "comment": {
      "author": {
        "node": {
          "name": "Generic Team"
        }
      }
    }
  }
}
```

Instead, the result is:

```json
{
  "data": {
    "comment": {
      "author": {
        "node": {
          "name": [Your WordPress User First Name + Last Name]
        }
      }
    }
  }
}
```

### Additional context

I’m quite new to WP GraphQL, so it might very well be that I’m missing something, but the code worked before and only recently stopped working.

Interestingly enough, comments created *before* the update to `v1.27.0` still return the content of `comment_author` despite the comment having a `user_id` that isn’t `0`.

### WPGraphQL Version

1.28.1

### WordPress Version

6.6.1

### PHP Version

8.3.6

### Additional environment details

Frontend is running via Next.js, but the issue can be reproduced in the GraphQL IDE. WordPress is run through Roots Bedrock.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by amxmln** [comment]
I have created a minimal reproduction example [here](https://github.com/amxmln/wpgraphql-comments-issue/tree/main) which can hopefully help with reproducing this issue.

**Comment by jasonbahl** [comment]
@amxmln the way comment authors work in WPGraphQL is to return a User if possible, and fall back to a generic "CommentAuthor" type if the User cannot be returned. 

Since your comment has a valid user, and that User is publicly visible to the requestor, the User is being returned, and thus fields on the `User` are returned. 

If you were to edit the `user_id` value of the comment in the database to an invalid ID, then the Type returned for the author would be `CommentAuthor` and the data would be resolved from the `comment` (i.e. `comment_author` field) instead of the user. 

I believe what we need here is "edge" data to be exposed on the connection. 

The `comment_author` field is a relational field between the comment and the user that made the comment and we would be best served exposing that as a field "between" the "Comment" and the "Commentor" node (either User or CommentAuthor)

That would allow for querying the author Node while also querying the "display" data such as `commentAuthorName` and then the consuming application could chose which field to use when rendering the UI. 

My proposal is to expose `commentAuthorName` and `commentAuthorUrl` as "edge" fields on the `CommentToCommentAuthor` connection. 

Then users could query like so: 

```graphql
query {
  comment(id: [the ID of the comment], idType: DATABASE_ID) {
    author {
      
      # relational data between the specific comment and the author of the comment
      commentAuthorName 
      commentAuthorUrl
      commentAuthorEmail
      
      node {
        name
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@amxmln I've got a PR in the works that adds support for this "edge" data. 

Here's a screenshot of this in action:

![CleanShot 2024-09-10 at 13 20 53](https://github.com/user-attachments/assets/0788e3ae-358c-4eb0-9d18-aa24f02f6f2a)


With this, I would be able to use this query to create a UI similar to what is displayed in the WP Admin, where I see some information (avatar, etc) from the User node, and some information (commenter's name) in place of the User's information:


![CleanShot 2024-09-10 at 13 19 25](https://github.com/user-attachments/assets/76ef2f05-9502-4b09-a98c-e5408500d550)

**Comment by jasonbahl** [comment]
@amxmln I've opened a PR exposing the conditional relational fields as "edge" fields in the Schema. 

You can read more in the PR #3208

**Comment by amxmln** [comment]
Sorry for the late reply, busy week. Thank you so much for taking a look and fixing this. 😊
