### ISSUE TITLE
URI Query - Receiving Post for Incorrect Slug Path

### ISSUE THREAD

**Issue by Messa1** [wp-graphql/wp-graphql#3240]
### Description

Is there a way to query by URI?
I have attempted this, but I encountered an issue in my React frontend. When I use $slug with /test/, I receive the post as expected. The same happens when I use /news/test/.
However, I only want to receive the post for /news/test/.

### Steps to reproduce

1. Set backend permalink to `/news/%postname%/`
2. Try query
```
query GetPage($slug: String!) {
  nodeByUri(uri: $slug) {
    __typename
    ... on Page {
      id
      title
      slug
    }
    ... on Post {
      id
      title
      slug
    }
    uri
  }
}
```
First 
```
{
  "slug": "test"
}
```

Second

```
{
  "slug": "/news/test"
}
```

### Additional context

![grafik](https://github.com/user-attachments/assets/067f1e10-69a8-4e49-8717-d6b134c8e372)
![grafik](https://github.com/user-attachments/assets/35439f64-2afb-4da3-abd2-50748cd4c672)
![grafik](https://github.com/user-attachments/assets/b9fb519d-cc8b-4566-981f-48af9d1722c3)

### WPGraphQL Version

4.3.1 

### WordPress Version

6.6.2.

### PHP Version

8.2.x

### Additional environment details

Im at the moment testing it local.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@Messa1 WPGraphQL should be resolving uri's the same way that core WordPress would if you visited the uri in a non-headless theme. 

What does WordPress do if you visit `/news/test` and `/test` in the browser?

Does it also resolve to `/news/test` in both cases?

**Comment by jasonbahl** [comment]
@Messa1 ok, I was actually able to reproduce this and indeed WPGraphQL's behavior does NOT match core WordPress's behavior in a theme. 

I set my permalinks the same as you: 

![CleanShot 2024-12-04 at 09 21 47](https://github.com/user-attachments/assets/b51577df-08cc-4ec1-a327-dc6dc9bf1e29)

I then published a post with the slug "test"

![CleanShot 2024-12-04 at 09 22 21](https://github.com/user-attachments/assets/f6961174-9b76-4dd7-b3ff-1c07a5c994a7)

If I visit the `/news/test/` uri in the browser I get the expected post:

![CleanShot 2024-12-04 at 09 22 45](https://github.com/user-attachments/assets/4c7fd158-2d27-4892-948d-cadc86d1db47)

However, if I visit the `/test/` uri, I get a 404. 

![CleanShot 2024-12-04 at 09 23 01](https://github.com/user-attachments/assets/5a2d9542-e527-4a88-ab21-e47abb235119)


BUT, if I query `nodeByUri( uri: "/test/" ) { ... }`, I get the `/news/test` node instead of a `null`. 

![CleanShot 2024-12-04 at 09 27 55](https://github.com/user-attachments/assets/9224560a-e283-42f7-8a96-fadf2db5e354)

So, this is confirmation that the `nodeByUri` behavior is indeed different than core's resolution of a uri in the browser in a traditional theme setup. 

----

Until we have a fix for this, one suggestion might be to compare the `$uri` with the `node.uri` response, and redirect to the resolved node uri in the client. 

i.e. if you query for `/test` and a node is returned with uri of `/news/test` you could redirect to that uri.

**Comment by Messa1** [comment]
@jasonbahl Yeah - I got the same behavour ob my system.
![Bildschirmfoto 2024-12-04 um 17 39 00](https://github.com/user-attachments/assets/3f1efa52-472d-46b3-a438-6567e19f78a9)
![Bildschirmfoto 2024-12-04 um 17 39 38](https://github.com/user-attachments/assets/aa4ebefc-9f37-45fd-8aa8-0cfda15f3802)

I could use a redirect, but I suspect the issue might be on my side.
Do you think using a redirect could have any negative effects? Perhaps on SEO or user behavior with direct redirects?

**Comment by jasonbahl** [comment]
> Do you think using a redirect could have any negative effects? Perhaps on SEO or user behavior with direct redirects?

Unlikely. Redirects are pretty common. WordPress has plugins like yoast, redirection, etc that all allow for redirects to occur after a request to WordPress has been made.

**Comment by Messa1** [comment]
@jasonbahl I will use it as a temporary solution. 😄 Hope you got time to find a fix. If you need someone to test something just write.

**Comment by jasonbahl** [comment]
@Messa1 I've opened up this PR #3250
