### ISSUE TITLE
Query Doesnt display Private Posts or Drafts

### ISSUE THREAD

**Issue by towfiqi** [wp-graphql/wp-graphql#325]
Hi,

The posts queried doesnt display the private posts or draft posts(which we need).  Our users can create lists that are only visible to them but we cannot display these private posts with the `viewer` query.

How do we override this behavior?

**Comment by jasonbahl** [comment]
@towfiqi you can pass args to the query to get a specific status. 

```
{
  posts( status: DRAFT ) {
    edges {
       node {
         id
       }
    }
  }
}
```

Note that in the near future, we will respect WordPress roles though, so only folks with proper access will be able to have content they have permission to access be resolved.

**Comment by towfiqi** [comment]
Thanks.

We let the "Subscribers" create/edit/delete a custom post type and set them to private. They are the author of these posts. 
So in future, we wont be able to display their posts (private, public, draft) with the `viewer` query?

**Comment by jasonbahl** [comment]
We will try and mirror core capabilities as much as possible. So, if your roles/capabilities are set up to allow `subscribers` to do crud operations on posts or custom post types, WPGraphQL will do it's best to respect that by default, and give you control to override and customize to the field level as needed.

**Comment by jrmcdona** [comment]
Is there a way to view posts in draft mode?   My query is not returning drafts which I want to use on the test environment for authors to preview that content on the front end.

**Comment by jasonbahl** [comment]
@jrmcdona Draft posts are considered non-public resources in WordPress and WPGraphQL respects that. 

You need to be authenticated to see drafts. 

If you are authenticated, then you can include drafts in queries like so:

```
{
  posts(where: { stati: [PUBLISH, DRAFT]}) {
    nodes {
      id
      title
      status
    }
  }
} 
```

**Comment by MitchEff** [comment]
@jasonbahl would I be correct in saying you can't do that for single posts, for some reason? 
I can see _'posts'_ has a 'where' input, but _'post'_ does not.

**Comment by MitchEff** [comment]
Okay I've tried absolutely everything I can think of, and zero drafts are being returned from anywhere. This affects custom post types, but I haven't tried with regular posts.

I've enabled viewing of drafts on the authenticated user role:
```
	add_role('investor', 'Investor (Approved)',[
		'read'         => true,
		'edit_posts'   => false,
		'delete_posts' => false,
		'read_private_posts' => true
	]);

	$role = get_role( 'investor' );
	$role->add_cap( 'read_private_posts' );
```

and I'm just querying for every post:
```

export const GET_DEAL = gql`
    query GET_DEAL{
        deals (
            where: {
                stati: [DRAFT]
            }
        ) {
            nodes {
                id
            }
        }
`
```

Zero results. I can remove 'stati', and I get all the published ones though. @jasonbahl are you able to take a look at this?

**Comment by valstu** [comment]
So I noticed something weird that could be related but didn't open a new issue yet. Lets say I have this custom post type called `cars`. I have set custom capabilities so that current user (eg. subscriber) can only edit and read their own cars. So the user has following caps:
`read, edit_cars`. All the posts are private. Now if i query the cars with following query I'll get my cars (my user id is 1513).
```
query GET_CARS {
  cars(where: {status: PRIVATE, author: 1513}) {
    nodes {
      title
    }
  }
}
```
But If I query the content with some other author id, nodes will be empty, which makes sense since I do not have capabilities to do that.

If I remove the author input completely I will only get two of my cars even though I have three in the database. Those two cars are latest cars I added to database so that is probably the reason why they're included, my third car was added months ago. I noticed if I sort the cars for example with title I will get empty array from that query. Seems like there is also some sort of pagination going on even though I should get only three results. Could it be that somehow behind the scenes WP GraphQL is counting all the cars but exposing only the three in my results? And If I would paginate through all the 1000 cars I have on my database I would eventually get my third car? It's late and hopefully this explanation makes some sense but what do you think @jasonbahl should I open new issue about this?

**Comment by jasonbahl** [comment]
@valstu ya, open an issue with as much info as possible so I can replicate the data, etc as well.

**Comment by RodrigoKoiti** [comment]
Hi, i had the same issue. I found this way to show all private and draft posts on query:

`//Product visibility draft, trash, etc
add_filter( 'graphql_object_visibility', __NAMESPACE__ . '\change_graphql_visibility', 10, 5 );
function change_graphql_visibility( $visibility, $model_name, $data, $owner, $current_user ) {
   
	// change productobject cap
	if ( $model_name == 'ProductObject' ) {
        if( current_user_can( 'administrator' ) ){
            $visibility = 'public';
        }
    }

    return $visibility;
}`

**Comment by RodrigoKoiti** [comment]
Hi, i had the same issue. I found this way to show all private and draft posts on query:

```
//Product visibility draft, trash, etc
add_filter( 'graphql_object_visibility', __NAMESPACE__ . '\change_graphql_visibility', 10, 5 );
function change_graphql_visibility( $visibility, $model_name, $data, $owner, $current_user ) {
   
	// change productobject cap
	if ( $model_name == 'ProductObject' ) {
        if( current_user_can( 'administrator' ) ){
            $visibility = 'public';
        }
    }

    return $visibility;
}
```

**Comment by nbuttt** [comment]
![Uploading Screenshot 2024-06-21 110140.png…]()
