### ISSUE TITLE
Feature Request: Subscriptions

### ISSUE THREAD

**Issue by kalebheitzman** [wp-graphql/wp-graphql#423]
I'm not sure it's even possible with the server architecture for Wordpress but subscriptions would be nice. If there's any direction for this I would gladly start working on it (unless it's already a thing!)

**Comment by jasonbahl** [comment]
@kalebheitzman WordPress actually lends itself great to GraphQL subscriptions since WordPress is all event based. So GraphQL Subscriptions can easily be hooked into things like creating posts, updating meta, etc. 

The problem lies in the transport. 

In my experimentation with WPGraphQL Subscriptions to this point, the WordPress install would need to send events to a Websocket (or somiliar) server to handle the transport to/from WPGraphQL to the client. 

I imagine Apollo's subscription transport project may work well, but haven't tried it yet: https://github.com/apollographql/subscriptions-transport-ws

I think it would be good to explore WPGraphQL subscriptions as an extension for those that want to manage a separate transport server, that way it's not in the Core plugin as a misleading feature, but something that folks can activate if they want to take advantage of it and maintain whatever supplemental infrastructure they need for transports. 

It would be interesting to possibly offer some sort of Transport as a Service option for WPGraphQL users though. 🤔

**Comment by jasonbahl** [comment]
If you're seriously interested in working on this, let me know and we can chat. I've done some experimentation locally, and actually succeeded in using Graph.Cool's websockets as my transport, in a hacky way. 😉

**Comment by achataing** [comment]
Good day! Any updates on the subject? I am currently starting a new project which uses react-native react nativebase and apollo client... The way things are working are great but I am missing the subscriptions from this repo... Is there any guidelines on how one could start implementing such features? thanks in advanced

**Comment by szagi3891** [comment]
> I’d be interested in formalizing subscriptions in the core WPGraphQL Schema but the transport will probably be left to each system making use of them.
And it's great. Implementing a websocket server with mobx is an easy task.

So you add it to the standard "core WPGraphQL Schema" ? :)

**Comment by jasonbahl** [comment]
I'm going to close this issue in this repo. We have a repo here to start working on subscriptions. Depending on the shape it takes, we could merge it back into this repo.

https://github.com/wp-graphql/wp-graphql-subscriptions

**Comment by dyontaistaton** [comment]
Hello, I would love to use this! I see you posted a video demo-ing this [here]( https://www.youtube.com/watch?v=CzI6quuFqks&ab_channel=WPGraphQL-GraphQLAPIforWordPress) but notice within this [repo](https://github.com/wp-graphql/wp-graphql-subscriptions) there is nothing really there? By chance could you push what you had?
