### ISSUE TITLE
menu item type (post, page, custom-link, category)

### ISSUE THREAD

**Issue by izzygld** [wp-graphql/wp-graphql#510]
How do we Query the MenuItem for its `post meta` (i.e. page, post, custom link...) ?

I see it being declared [here:](https://github.com/wp-graphql/wp-graphql/blob/develop/tests/wpunit/MenuItemQueriesTest.php#L19)

**Comment by chriszarate** [comment]
The "type" of a WP nav menu item is stored in the post meta key `_menu_item_type` and describes whether the menu item points to a post or a term or is a custom link. In WPGraphQL-speak, it describes the type of the object that is connected to the menuItem; in the query below, it informs the `__typename` of the `connectedObject` field:

```
query {
  menuItems(
    where: {
      location: MY_MENU_LOCATION
    }
  ) {
    nodes {
      connectedObject {
        __typename
        ... on Post {  # post, _menu_item_type = post_type
          title
        }
        ... on Book {  # custom post type, _menu_item_type = post_type
          title
        }
        ... on Category {  # tax term, _menu_item_type = taxonomy
          name
        }
        ... on MenuItem {  # "custom link", _menu_item_type is empty
          title
        }
      }
    }
  }
}
```

You can see that the meta key value of `_menu_item_type` quickly becomes irrelevant, because it not connected to WPGraphQL's type system. What you're really asking for is a way to filter the `menuItem`s by the `__typename` of their connectedObject.

You can do that manually, of course, once you get the results back. Implementing it as a query arg, however, would mean either (a) using a post meta query (non-starter, too expensive), or (b) getting all of the menu items and then filtering them on the WPGraphQL side.

I'm not sure if doing (b) makes sense or might lead to issues (e.g., complicated pagination). Under the hood, we're using `wp_get_nav_menu_items` to the get the menu items so it's not straightforward to combine query args.

So this needs some investigation. In the meantime, I can recommend filtering by `__typename` on the consuming side.

**Comment by jasonbahl** [comment]
@chriszarate thanks for responding to this. 

@izzygld does that cover what you were looking for? Can we close this or do you believe there's something to be addressed still?

**Comment by izzygld** [comment]
I Concur.
In the mean time i am using a filter by __typename on the consuming side.

Thanks @chriszarate👍
