### ISSUE TITLE
Prevent duplicate mutations from occurring in rapid succession

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#602]
@CodeProKid brought up (https://github.com/wp-graphql/wp-graphql/pull/597#discussion_r238781799) the fact that sending an email over and over and over could be harmful to a WP server. 

It seems that any GraphQL Query or Mutation sent in rapid succession could be harmful. 

We should investigate if it makes sense to try and prevent duplicate requests from being processed if they occur in rapid succession. 

Not sure entirely if this needs to be a solution of the WPGraphQL plugin or not, but worth discussing either way

**Comment by CodeProKid** [comment]
So, the more I've been thinking about this, the more I think the scope of this should be limited to un-authenticated mutations only...

Many queries in rapid succession could take down a site, but so could a ton of requests to an uncached page on a WP site, or many requests to a REST endpoint, so I don't think we should be responsible for rate limiting the reading of data. I feel like that should be handled by the site owner, or handled with query complexity limits.

Similarly, for authenticated mutations if the rapid succession of them are becoming an issue, it's probably by the creation of the application developer. Their app is either making too many requests, or a bad actor has access to their app and is doing some bad stuff, and I don't think we should be responsible for either of those things.

I think it _is_ our responsibility to protect public mutations, because they provide an easy way to actually change data in the database without any authentication, which seems like something that could be ripe for abuse.

I think a simple solution for this would be to create a simple util function that would store a flag in the object cache for a certain time period, and if that flag hasn't expired the next time a mutation happens, it blocks it from happening. Some psuedo code:
```php
function should_limit_action( $name, $identifier ) {
    $group = 'wp-graphql';
    $key = wp_hash( $name . $identifier );
    $key_found = wp_cache_get( $key, $group );
    if ( false === $key_found ) {
        wp_cache_set( $key, time(), $group, apply_filters( 'graphql_limit_action_expiration', 60 ) );
        return false;
    }
    return true;
}
```
I think the object cache should be used here since it would add some fairly significant overhead if we were to use the DB for storage. Sites not using an object cache won't really get this advantage, but I think it's a fair tradeoff.

We could implement this in the password reset mutation for example here -> https://github.com/wp-graphql/wp-graphql/blob/b4bb06568b883a41b92a4fef792371eae351d8a6/src/Mutation/SendPasswordResetEmail.php#L47 like so:
```php
if ( false === should_limit_action( 'passowrd_reset', $input['username'] ) ) {
    wp_mail();....
} else {
    throw new UserError( 'Too many password reset attempts have been sent for this user' );
}
```

**Comment by jasonbahl** [comment]
@CodeProKid ok, so we need a way to identify which mutations are public and which are not so that we can properly apply something like this across the board. 

We can add something like `isPrivate` or `requireAuth` or something to that tune to the `register_graphql_mutation` args, and apply that to any where `isPrivate` is false or something

**Comment by jasonbahl** [comment]
@CodeProKid so, the transaction ID would be a combination of the: 
- Context (current user)
- query string
- variables
- operation name

We can hash those to use as the cache key, then when a mutation begins execution we can check to see if the mutation was registered as `isPrivate` or `requireAuth` or whatever, and if that's true we ignore the cache rule to allow the request to continue execution.

If that's not true, and it's a public mutation, then we can check the cache to see if there was a duplicate request in the last XX seconds/minutes, and if so, kill the request and return some error or whatever. 

Does that make sense?

so we could hook into `graphql_before_resolve_field`, check the config for the mutation to see if it's registered as a publicMutation or not, then execute the logic to block the duplicate if a cache is present. 

Something to this tune: 

```

add_action( 'graphql_before_resolve_field', function( $source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info, $field_resolver, $type_name, $field_key, $field ) {

	if ( 'RootMutation' === $info->parentType->name ) {
		$type  = \WPGraphQL\TypeRegistry::get_type( $type_name );
		if ( isset( $type ) && ! empty( $field = $type->getField( $field_key ) ) ) {
			if ( isset( $field->config['isPublic'] ) && true === $field->config['isPublic'] ) {
				if ( true === someFunctionToCheckTheCache() ) {
					throw new Exception( __( 'This mutation has been executed too many times in the allowed timeframe', 'wp-graphql' ) );
				}
			}
		}
	}
	return;

}, 10, 8 );
```

**Comment by betweenbrain** [comment]
Out of curiosity, would this require some sort of admin UI to enable/disable and to configure the rates? I could see the need, in some cases, to turn this off or maybe even enable during a DOS attack.

**Comment by jasonbahl** [comment]
I'm going to close this as I believe this responsibility doesn't belong to WPGraphQL core.
