### ISSUE TITLE
Expose post count for the User type

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#614]
Currently, in the WordPress dashboard, when looking at the user list table there's a "count" field in the table that exposes the number of posts associated with a user. 

This can be expensive, so it's not included as an exposed field in WPGraphQL by default. 

There needs to be more discussion on whether this field even makes sense to be exposed. 

For example, what would `user.count` even represent? (What does it represent now)? All posts of all types and all statuses? Just public post_types and published posts? 

I think this needs more discussion on what value this field provides and if a simple integer as a field is a good decision or not. 

It could take many shapes. . .like it could be edge data between users and a connection to the posts connection instead?

**Comment by jkhaui** [comment]
Hi @jasonbahl , 

As someone who is working extensively on a WordPress/GraphQL/React project (by extensive I mean a social network-style platform where the intention is to expose a lot of metadata), I can personally say that the count feature for post types holds a lot of value - and it doesn't need to be more than a simple integer.

Obviously, everyone's use-case is different, but for my purposes, a user's post count would be a way of displaying their reputation - kind of like how many questions you've posted or answered on StackOverflow. 
IMHO I believe the true value of GraphQL for WordPress is precisely in exposing a lot of metadata that would otherwise not have been feasible via individual REST API endpoints. For example, I use GraphQL to expose fields like tag descriptions and comment_meta-based fields frequently in my app. It complements the UX of a dynamic SPA.

Performance-wise:  I can't really comment as I'm only using a seed database of about ~100 users, ~40 tags and ~100 CPTs atm. But I am running WordPress on a micro instance with a lot of processes and, so far, have not noticed any performance issues whatsoever. And if it's good enough for Facebook... :)

**Comment by jasonbahl** [comment]
There's no immediate plan to expose counts on connections out of the box, as it can be a performance issue. 

Should site owners feel that it's safe to expose counts on connections, there was work in the v0.3.0 release that has made it easier to expose them.

See: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/AbstractConnectionResolver.php#L476-L503
