### ISSUE TITLE
Query with multiple operations

### ISSUE THREAD

**Issue by ManUtopiK** [wp-graphql/wp-graphql#653]
It is possible to query multiple operations?
I can reproduce the error in your playground:
1. Go to https://playground.wpgraphql.com/#/
2. Paste this on the query field:
```gql
query allPosts {
  posts {
    edges {
      node {
        id
        title
        date
        excerpt
      }
    }
  }
}

query onePosts {
  post(id:"cG9zdDox") {
    id
    title
    date
  }
}
```
3. Execute query for allPosts or onePosts.
=> errors.message: `"Must provide operation name if query contains multiple operations."`

**Comment by chriszarate** [comment]
If you're asking if you can _execute_ multiple queries, no. But you combine your operations into a single query:

```
query allPostsAndOnePost {
  posts {
    edges {
      node {
        id
        title
        date
        excerpt
      }
    }
  }
  post(id:"cG9zdDox") {
    id
    title
    date
  }
}
```

You can also ship multiple queries and specify which you want to run by sending an operation name. The issue here is that WPGraphQL is expecting the operation name to be provided as `operation` in the request body, but GraphiQL sends it as `operationName`. The latter appears to be correct.

https://graphql.org/learn/serving-over-http/#post-request

Here's how you can do it now with cURL:

```sh
curl 'https://api.wpgraphql.com/graphql' \
-X POST \
-H 'Content-Type: application/json' \
--data-binary '{"query":"query postsQuery {\n  posts {\n    nodes {\n      slug\n    }\n  }\n}\n\nquery tagQuery {\n  tags {\n    nodes {\n      slug\n    }\n  }\n}","variables":null,"operation":"postsQuery"}'
```

We should align on `operationName`.

**Comment by chriszarate** [comment]
Follow-up: You can also _batch_ multiple queries together (something that WPGraphQL supports), but that's more of a transport feature:

https://blog.apollographql.com/batching-client-graphql-queries-a685f5bcd41b

**Comment by ManUtopiK** [comment]
> You can also ship multiple queries and specify which you want to run by sending an operation name. 

That's what I want to do!

> The issue here is that WPGraphQL is expecting the operation name to be provided as operation in the request body, but GraphiQL sends it as operationName. The latter appears to be correct.
 
WPGraphQL should use "operationName", because all graphiql client seem use it. I took a look on:
- google chrome graphiql extension
- google chrome altair extension
- insomnia app
- graphiql app
- and ever wp-graphiql !

**Comment by jasonbahl** [comment]
@ManUtopiK it looks like there might be a bug with `playground.wpgraphql.com` which is causing the errors. 

You _should_ be able to use GraphiQL to select which of the queries you would like to run, if they are named queries, and yours are. 

When I paste in your query, GraphiQL allows me to select which query to execute, and it sends the request properly, but then responds with `Must provide operation name if query contains multiple operations.`

When I look at the request that `playground.wpgraphql.com` is sending, it looks like it's sending both queries as if they were a single query instead of just sending the one selected. 

So the actual request being sent by `playground.wpgraphql.com` is: 

```
{
  operationName: "allPosts"
  query: "query allPosts { posts { edges { node {  id,title,date,excerpt } } } } query onePosts { post(id:"cG9zdDox") { id,title,date } }"
  variables: null
}
```

So the behavior of `playground.wpgraphql.com` appears to be the bug here. 

----

As @chriszarate mentioned, you could do a single RootQuery with multiple RootQuery fields, or you could do batch requests, where you send an array of requests in the body, like so (you can paste this into your Chrome console to test): 

```
fetch( 'https://www.wpgraphql.com/graphql', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify([
    { 
      "query": 'query allPosts {posts { nodes { id, title, date }}}',
      "operationName": 'allPosts'
    }, 
    { 
      "query": 'query onePost { post(id:"cG9zdDo5Njg=") { id, title, date } }',
      "operationName": 'onePost'
    }
  ]),
})
.then( res => res.json() )
.then( console.log );
```

I think the issues you're experiencing may be related to updates needed on `api.wpgraphql.com` and `playground.wpgraphql.com`

**Comment by jasonbahl** [comment]
> WPGraphQL should use "operationName", because all graphiql client seem use it. I took a look on:
@ManUtopiK where are you seeing that WPGraphQL doesn't expect `operationName` from requests?

**Comment by jasonbahl** [comment]
@ManUtopiK I'll look into getting both `api.wpgraphql.com` and `playground.wpgraphql.com` working, but check your own WP site with the latest WPGraphQL activated to make sure behavior is as expected there. 😄

**Comment by ManUtopiK** [comment]
> > WPGraphQL should use "operationName", because all graphiql client seem use it. I took a look on:
> 
> @ManUtopiK where are you seeing that WPGraphQL doesn't expect `operationName` from requests?

No, sorry, it's a mistake.

> When I look at the request that playground.wpgraphql.com is sending, it looks like it's sending both queries as if they were a single query instead of just sending the one selected.

Although it's quite curious, it seems like it's normal behavior. Like I said, graphiql and altair chrome extensions do that, also insomnia and official graphiql electron app.

> but check your own WP site with the latest WPGraphQL activated to make sure behavior is as expected there.

I did git pull and tested it on master and develop branch.

**Comment by jasonbahl** [comment]
@ManUtopiK ok, I see that many of the GraphQL clients do indeed send multiple queries as the query string in the request. 

This is interesting. . .I'm not quite sure _why_ they would do this instead of just sending the selected query 🤔 

But clearly this is common and WPGraphQL isn't supporting it properly. 

Thanks for pointing this out! 

It's definitely an issue (and I understand it now 😉). We'll look at getting it resolved, as having things _not_ work in WPGraphiQL, etc is no fun.

**Comment by jasonbahl** [comment]
FWIW, I know this did work at one point. My current hunch is that something broke when I did work for supporting Batch Requests. 

Not 💯 sure what, but I think it's a good place to start by looking at what changed when Batch Request support was implemented.

**Comment by ManUtopiK** [comment]
I found an issue 🎉  I was not really sure...

**Comment by jasonbahl** [comment]
@ManUtopiK I tracked down the issue to the underlying GraphQL-PHP library. 

The version we were on tries to parse `operation` instead of `operationName`

Updating the underlying GraphQL-PHP library to version 0.12.6 fixes this bug. 

Can't believe this has been broken this long. Good catch. We've been wanting to update GraphQL-PHP for a while and this lit the 🔥 to get that done. 😄
