### ISSUE TITLE
[Feature Request] skip and orderBy arguments for pagination

### ISSUE THREAD

**Issue by snnsnn** [wp-graphql/wp-graphql#702]
Hi, thank you for this great plugin.

Please can you add `skip` and `orderBy` arguments for pagination since query results can intersect and one may want to sort and skip certain number of items to prevent data duplication.

Lets say I have two queries, and for the second query I would like to get last ten items after skipping five because first query already spits them on page.

**Comment by snnsnn** [comment]
After reading and re-reading relay pagination implementation, I see offset is intentionally left out. So, can anyone help me how to achieve skipping items without all the intricacies.

**Comment by jasonbahl** [comment]
When you ask for data, use the `pageInfo` field to get the `endCursor` then use that value as the `after` value in your next query. 

Tracking the cursor is the same amount of effort as tracking a skip value, and using that value for the `after` arg is the same effort as using the skip value for a skip arg. 

There’s documentation on pagination here:

**Comment by rafaelderolez** [comment]
@jasonbahl This means you can only implement pagination using a 'load more' button, opposed to having `skip` and being able have 'Previous / Next' buttons, right? I don't have the source by hand right now but I think SEO-wise prev/next is "better"?

**Comment by jasonbahl** [comment]
@rafaelderolez hey! You can setup Previous/Next buttons with WPGraphQL. 

Here's an example of this concept in React using Apollo Client: 

https://codesandbox.io/embed/apollo-client-hooks-example-ldwig?fontsize=14&hidenavigation=1&theme=dark

**Comment by rafaelderolez** [comment]
That works, but we're looking for a server-side solution (using Next.js on this project). We ended up installing this plugin [wp-graphql-offset-pagination](https://github.com/valu-digital/wp-graphql-offset-pagination) which allows us to calculate the offset from a url param (?page=2). Thanks for the quick reply though!

**Comment by jasonbahl** [comment]
@rafaelderolez you can do this server side as well. Where I'm using the cursor in the variables, you can use in a query paramater. So instead of `?page=2` you could do `?after=$pageInfo.endCursor`

I'm writing up a blog post that explains cursor pagination a bit more.

**Comment by rafaelderolez** [comment]
My bad, didn't mean to imply that it wasn't possible server-side! I feel like ?page is a bit more robust (doesn't break if you delete posts and then go back to the site using that url), and looks a bit nicer to the user as well.

**Comment by jasonbahl** [comment]
The cursor pagination _shouldn't_ break if you delete posts either. Have you experienced otherwise?

In fact, in my blog post, I go over how page-based pagination actually causes more data inconsistency than cursor based. 

In short, let's say you have 5 items per page. The user loads page 1 and sees items 1-5. While they're on that page, you delete items 4 & 5. Items 6 and 7 would now "slide up" to be 4 & 5, but when the user clicks Page 2, items 6 & 7 wouldn't be there, because they'd now be part of Page 1. So the user would miss out on content and would see items 8-12, and have no way of knowing they missed items 6 & 7.

That's because the underlying query for page based uses offsets. 

```
SELECT * FROM table ORDER BY timestamp OFFSET  0 LIMIT 5
SELECT * FROM table ORDER BY timestamp OFFSET  5 LIMIT 5
``` 
So you're skipping a number of posts, regardless of whether new content was published or old content was deleted. 

With cursor pagination, the cursor is a reference to a point in the database. So if you were to delete items 4 & 5, and you loaded the next set of posts with `?after=cursor_for_post_5`, you would appropriately get items 6-10 still, instead of getting items 8-12. 

The cursor in this case would be a timestamp, since posts are default ordered by publish date, so any post published _before_ item 5 would be loaded. So the user would appropriately get items 6 & 7, even if there were deletions.

```
SELECT * FROM table WHERE cursor > timestamp ORDER BY timestamp LIMIT 5
```

----

That said, I love that you found the offset pagination plugin and that it's working for you! I just want to provide some info on why we have cursor pagination by default and provide some insight into how it works and how it can be implemented. 😄

**Comment by rafaelderolez** [comment]
Good point, I hadn't thought about it like that. (About missing posts, and posts sliding between pages)
Looking forward to your blog-post about it!

**Comment by jasonbahl** [comment]
@rafaelderolez I just published the blog post: https://www.wpgraphql.com/2020/03/26/forward-and-backward-pagination-with-wpgraphql/

**Comment by ivanjeremic** [comment]
The issue title is about  _**skip and orderBy**_ issue on pagination, Is this solved already or are we currently not able to use cursor pagination and _**orderBy**_ together?

**Comment by janus-reith** [comment]
@jasonbahl I agree about offset pagination having a higher probability of breaking an order and missing items/showing duplicates across pages as I had the same considerations before, but I'd like to catch up on the nextjs usecase @rafaelderolez mentioned to reason why I still think this should be there.

And I agree that UX-Wise, it would also work out to just load more results on scroll instead of paginating, IF I want to query the api from the client, thereby also resulting in more requests.

Let' say I do static fallback generation with nextjs and have a list of blog posts, I want to go to a list of older entries on a page 2,3 and so on, only executing requests on the server, while serving statically generated pages to the client(I could still refresh them at some point with nextjs revalidation, which would still be less requests than each user calling the api ).

I might be using fallback rendering and therefore could query a page 5, which did not exist during build time. 
I could provide a cursor Id in the url for static generation instead, but couldn‘t make readable urls with that.
Also, I couldn‘t do something like e.g.  display a go-to page x selector on any page which could allow me to go from page  1 to page x, as I don‘t have a cursor id for that page yet.

I agree that in general, the page index doesn't really say much, although it works as a kind of workaround during a certain time frame in which the content probably  won't change that much - E.g. I might be interested to look up something from a certain time span, so I could see that relevant posts from end of 2018 are at around Page 50 - I could go back and forward from there, as I might be trying to look up something specific, and get a general idea of how much posts.
This could also be solved with cursor pagination, probably more elegant, by fetching starting cursors for each year/month/whatever and then allowing users to jump to that point, I was just trying to point out that the pagination is not useless in general in giving viewers a certain overview.

I guess I will explore now how an endless scrolling could be achieved in nextjs with static generation and fallbacks, by fetching the static props  which would also be used for the static generation of that page as json, so If someone else might jump to that point in a certain timeframe, no db query would execute, and no additional server render would execute If someone might jump there directly coming from an external page - Wonder how that will work out, this could be a viable solution where I would not need to fall back on Pagination.

Still, there might be stacks not allowing these specific and rather advanced possibilities, where having offset could be a quick simple solution.

**Comment by KevinBatdorf** [comment]
Using NextJS (without Apollo) it doesn't look like it's possible to build out traditional pagination via `getStaticPaths()` so you can't do SSR without the skip/offset option. Has anyone solved this without having to add a plugin? 

Regarding the philosophical stuff -> If the client wants the traditional type pagination, I don't care enough to argue with them about why it's useless. I just want to get the job done as fast an efficiently as possible so I can get paid and move on to the next project.
