### ISSUE TITLE
Enhancement: Add graphql_register_fields action

### ISSUE THREAD

**Issue by benallfree** [wp-graphql/wp-graphql#801]
Currently, only a `graphql_register_types` action exists for registering both types and fields. This makes sense for most use cases, but a separate `graphql_register_fields` action would help for use cases where types and fields need to be registered separately. (For example, when a circular dependency exists such as `<Type1>.foo` returns `<Type2>` and `<Type2>.bar` returns `<Type1>`).

This can already be accomplished with different hook priorities in `graphql_register_types`, but I think it's cleaner to have a separate action specifically for registering fields after all types have been registered.

**Comment by jasonbahl** [comment]
So, I think the issue you want is to be able to register an object type without explicitly registering fields that belong to it. 

Right now, if you `register_graphql_field`, that's only acted on when the Type is being instantiated. 

The `graphql_{$type_name}_fields` filter is this "action" (filters/actions are the same, filters just expect an output). 

The problem I believe you're running into is wanting to register a Type, but not register it's fields within the Type definition directly.

I'm not quite sure the best way to handle this case, as there's no real guarantee that fields will be registered separately, so an object type _needs_ to have at least one field registered to it to instantiate. 

The only thing I can think of is to have something like a default fallback field, like if an object type is registered with no fields defined, a default field will be added to it (like a `typename` field or something) to make sure it _can_ be instantiated properly. 

🤔 

You can register circular types as-is, because fields are registered when Types are being instantiated, and Types have already been registered by that point.

**Comment by jasonbahl** [comment]
For example, you can do a circular type like so:

```
add_action( 'graphql_register_types', function() {

	$myCustomType = [
		'someField'    => 'Some value...',
	];

	register_graphql_object_type( 'MyCustomType', [
		'fields' => [
			'someField' => [
				'type'    => 'string',
				'resolve' => function() {
					return 'Some value...';
				}
			],
			'child'     => [
				'type'    => 'MyCustomType',
				'resolve' => function() use ( $myCustomType ) {
					return $myCustomType;
				}
			],
		]
	] );
	register_graphql_field( 'RootQuery', 'myCustomType', [
		'type' => 'MyCustomType',
		'resolve' => function() use ( $myCustomType ) {
			return $myCustomType;
		}

	]);
});
```

And query it like so:

![Screen Shot 2019-04-26 at 12 53 47 PM](https://user-images.githubusercontent.com/1260765/56830359-5faf9f80-6823-11e9-94ba-6e1263e0dfde.png)

**Comment by jasonbahl** [comment]
I don't think this is actually an issue. Can re-open if new info proves otherwise.
