### ISSUE TITLE
Exception has occurred. GraphQL\Error\InvariantViolation: Cannot return null for non-nullable field Post.id.

### ISSUE THREAD

**Issue by pristas-peter** [wp-graphql/wp-graphql#848]
The queried post is private and therefore the model layer cannot return proper ID. Should this result in internal server error?

**Comment by jasonbahl** [comment]
Can you give more info on the query you executed and the result that you’re seeing, etc?

**Comment by pristas-peter** [comment]
```graphql
query pages {
  postBy(postId: 1) {
    id
  }
}
```
$ wp shell
wp> 
wp> 
wp> get_post(1)
=> phar:///usr/local/Cellar/wp-cli/2.1.0/bin/wp/vendor/wp-cli/shell-command/src/WP_CLI/REPL.php:43:
class WP_Post#3995 (24) {
  public $ID =>
  int(1)
  public $post_author =>
  string(1) "1"
  public $post_date =>
  string(19) "2019-04-03 18:22:29"
  public $post_date_gmt =>
  string(19) "2019-04-03 18:22:29"
  public $post_content =>
  string(137) "
<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
"
  public $post_title =>
  string(12) "Hello world!"
  public $post_excerpt =>
  string(0) ""
  public $post_status =>
  string(5) "trash"
  public $comment_status =>
  string(4) "open"
  public $ping_status =>
  string(4) "open"
  public $post_password =>
  string(0) ""
  public $post_name =>
  string(20) "hello-world__trashed"
  public $to_ping =>
  string(0) ""
  public $pinged =>
  string(0) ""
  public $post_modified =>
  string(19) "2019-04-24 13:12:20"
  public $post_modified_gmt =>
  string(19) "2019-04-24 13:12:20"
  public $post_content_filtered =>
  string(0) ""
  public $post_parent =>
  int(0)
  public $guid =>
  string(28) "https://pjur.hobo53.com/?p=1"
  public $menu_order =>
  int(0)
  public $post_type =>
  string(4) "post"
  public $post_mime_type =>
  string(0) ""
  public $comment_count =>
  string(1) "1"
  public $filter =>
  string(3) "raw"
}
```

```

**Comment by pristas-peter** [comment]
![Uploading Screenshot 2019-05-11 at 15.54.11.png…]()

**Comment by jasonbahl** [comment]
Ah ya, this would be expected behavior currently. If you try and ask for something that doesn’t exist, it will throw that error. 

According to access rights, if you don’t have proper capabilities to access a private thing, it will return as if it doesn’t exist at all. 

Much like if you as a public user visited the url for a trashed post you would see a 404. 

Do you have other expectations for how this should behave? 

If you make an authenticated request and have proper capabilities the post would be returned.

**Comment by pristas-peter** [comment]
I agree, but I think that the post should not be resolved at all (null should be returned) and withou internal error

**Comment by jasonbahl** [comment]
Well, the ID field on the Post Type is defined as a nonNull field, and the GraphQL spec specifies that an error should be returned if a non null is asked for but can’t be resolved. 

Since a single node is being asked for and the id field can’t be resolved an error is returned. 

I think one thing that will fix this is to change the shape of the queries from:

```
{
  post( id: “...” ) {
     id 
     title
  }
}
```
To:


```
{
  post( id: “...” ) {
     node {
       id 
       title
     }
  }
}
```

That edge space between post and node will allow the post field to return null for the node field without an error I believe. 

I have an old issue about adding one-to-one connections, and this is more of a reason to address that sooner than later

**Comment by pristas-peter** [comment]
Cannot query return something like this?:
```graphql
{post: null}
```

**Comment by jasonbahl** [comment]
It already is. You are already getting a null. 

You are _also_ getting an error though because ID is a non_null field on Post

**Comment by pristas-peter** [comment]
I meant without the error. Because it's not a server error, it's an auth error. So it should be Auth Error or something like that, or no error at all. Because with Internal Error, the result is confusing.

**Comment by jasonbahl** [comment]
It's kind of like visiting a private post like `site.com/private-post` on WordPress and you will get a 404, even if the post exists.

I get what you mean, but not returning an error in this particular case that would not follow the GraphQL Spec.

We can probably change the error message to something like `A post by that ID does not exist` but it would still return an error. 

It might be equally as confusing to ask for a post, not get results and have no error. . . like what if you visited a private post and didn't get a 404, but just a blank white page? The 404 response is helpful. And here the error can be helpful as well. 

I think our options here are to have it return a more helpful error message or, as mentioned previously, change the shape of the Schema to what I mentioned above, where the entry field returns an Edge, and on that Edge you ask for the `node`. (that's in the backlog anyway).

The `ID` field is going to be `non_null` always per the Relay Spec, but if the `node` field is nullable, then you could ask for:

```
{
  postBy( id: "..." ) {
     node {
       id
       title
    }
  }
}
```

and you could get back:

```
{
  postBy: {
     node: null
  }
}
```

with no error, because `node` would be nullable.

**Comment by TylerBarnes** [comment]
I think this should 100% return null. This breaks the whole query but you may also be requesting some fields you have access to or that can be null. So it should be nullable.

**Comment by TylerBarnes** [comment]
Sorry, I misread this issue in a noisey room! ignore my last comment :p

**Comment by hsimah** [comment]
+1 for null payload and no error

**Comment by TylerBarnes** [comment]
I've been running into this when building the new Gatsby source plugin and I'm thinking more that I agree it should be null payload with no error.

This returns a very similar error for me:
```
query {
  categories {
    nodes {
      slug
      taxonomy {
        connectedPostTypes {
          id
        }
      }
    }
  }
}

```

I believe it's because there are no connected post types so I get `"Cannot return null for non-nullable field PostType.id."`. I get that this is following the GraphQL spec but it seems unhelpful. If there are no connected post types it should return null. When an error is returned it makes it seem like something is wrong though everything is actually fine.

**Comment by jasonbahl** [comment]
The original issue has been addressed. 

You can now query `postBy` with a non-existing ID, and you will get a null with no error
