### ISSUE TITLE
add deregister_graphql_mutation API

### ISSUE THREAD

**Issue by mhinton** [wp-graphql/wp-graphql#874]
When using deregister_graphql_field the field name argument is wrong. The field name arg has to be lowercase. 

This is what should work

`deregister_graphql_field('TypeName', 'menuOrder');`

but that doesn't remove the field.

This is does remove the field 

`deregister_graphql_field('TypeName', 'menuorder');`

I am on the release/v0.2.3 branch.

**Comment by betweenbrain** [comment]
Adding that this seems to still be an issue with v0.3.2

**Comment by CodeProKid** [comment]
This may have been fixed, need to reproduce and close / update this issue.

**Comment by jasonbahl** [comment]
Ok, I've confirmed this is an issue. When you do use `deregister_graphql_field()` to remove a mutation from `RootMutation`, it _does_ remove the field as intended. 

However, it doesn't remove the registered Types that are used by the mutation. 

We should offer a `deregister_graphql_mutation()`, which will cleanup the mutation field, but also the input type(s) and output type(s) that are registered along with it.

**Comment by hsimah** [comment]
I am looking to prevent some CPT mutations from existing (they're created as side effects of other actions). Instead of adding a deregister mutation and removing the input types etc, maybe a config options `graphql_mutation`? Config options:

|Param|Outcome|
|--|--|
|`true`|Normal behaviour (default)|
|`false`|No mutations generated|
|`'create'`|Generates creation mutation only|
|`'update'`|Generates update mutation only|

**Comment by desmondhoward** [comment]
any update on this? a `deregister_graphql_mutation` function is crucial as the typings for previously registered mutations stick around forever and can't be updated.

**Comment by jasonbahl** [comment]
@desmondhoward It's not been a priority to work on yet. If it's causing issues, I'd love to see a PR tackling this. 

Let me know if you're interested in working on a PR?

**Comment by desmondhoward** [comment]
unfortunately not willing to work on a PR since I am not well versed in PHP.
please let me know if this will be added to an upcoming milestone though.

**Comment by justlevine** [comment]
@jasonbahl is there currently a way to deregister a GraphQL `type` (not a `field` on a type) that I'm missing, or do we need to add a new filter to short circuit `TypeRegistry::register_{type}()`?

**Comment by jasonbahl** [comment]
> @jasonbahl is there currently a way to deregister a GraphQL type (not a field on a type) that I'm missing, or do we need to add a new filter to short circuit TypeRegistry::register_{type}()?

@justlevine A little late responding here, and I know you have some PRs in this realm already open/in the works. 

But here's some thoughts. 

I originally didn't include a `deregister_graphql_type` API because it felt like it could cause a lot of problems. 

Types are referenced SO often across the Graph and plugins, etc will often expect them to be there. 

If a plugin does something like registers a connection from TypeA to TypeB, and then other plugin de-registers TypeA, what happens?

Or what happens if you `deregister_graphql_type( 'Post' );`? 

Do all queries that return a `Post` go away from the Schema? Or do they fallback to some other Type? I think currently there's some logic somewhere that defaults to `String` if an invalid Type is used in the field config. 

Anyway, just some things to think about. I imagine you already have thought about these things, and I'm sure when I go look at your PRs, I'll realize as much too 😆

**Comment by justlevine** [comment]
@jasonbahl yep, I def did my best in #2557 to guard against those sorts of issues (and I'm sure you'll spot something I didnt when you review ;) ), but it works by removing all types and all references to the type anywhere else, which is a pretty heavy-handed approach

That said #2563 should provides a pathway to just deregister the mutation + generated types a lot less destructively 🤞

**Comment by jasonbahl** [comment]
Ok nice! 

I just read your description on #2557 and it does indeed consider these things!

Genius. 🙌
