### ISSUE TITLE
JWT Auth not working with Menus: 403 Response

### ISSUE THREAD

**Issue by rotexhawk** [wp-graphql/wp-graphql#879]
I am using the master branch and I am having trouble with JWT and menus. When the user is Authenticated, the menu query returns 403. I ran this in graphiql as well and got an error. If I change the query to i.e pages, everything works.

**Comment by drewbaker** [comment]
I had a similar error, but solved it by clearing all my cookies and localStorage. I think Apollo caches the JWT token and if for some reason that changes (in my cases I changed the salts on the server) then Apollo is sending that token with all requests, even ones that don't need auth, so WordPress gives out the auth error.

**Comment by jasonbahl** [comment]
From what I can tell, the issue here is expired tokens. Auth tokens have a 5 minute lifespan before they need to be refreshed. 

If you pass an expired token, WPGraphQL will 403 because it's invalid. 

The typical workflow I suggest is: 

- use the `login` mutation to get an authToken
- store the authToken as a cookie or localStorage
- for future requests, use the authToken to make authenticated requests
- upon successful authenticated requests, check the headers for `X-JWT-Auth`, which will be valid for 5 more minutes. 
- Replace your auth token in the cookie/localStorage with the fresh x-jwt-auth token from the headers

That flow should allow you to continually have a fresh token after each authenticated action a user takes. 

You can also write an Apollo Link middleware that manually checks the expiration of the JWT token _before_ sending auth headers in a request, and if expired it can use the JWT Refresh Token to make a `refreshToken` mutation, get a fresh authToken, then use that in the request. 

If a token can't be refreshed, the user needs to re-authenticate to get another token.
