### ISSUE TITLE
No sub-categories showing on posts if also getting featuredImage

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#887]
This is a strange bug, if you try to to get all posts, and do a nested categories query, and also ask for the featuredImage on the post, then the categories come back with no sub-categories. If you remove the featured image query, then you get all the sub-categories!

See the two screen shots, the only difference is the `featuredImage`.

<img width="1264" alt="Screen Shot 2019-06-23 at 6 20 52 PM" src="https://user-images.githubusercontent.com/475015/59985040-b9de9e00-95e3-11e9-969a-56d5c00c41c6.png">
<img width="1253" alt="Screen Shot 2019-06-23 at 6 21 01 PM" src="https://user-images.githubusercontent.com/475015/59985041-b9de9e00-95e3-11e9-9422-8da55b6aafd7.png">

**Comment by jasonbahl** [comment]
@drewbaker his one is strange indeed. 🤔 

Seems like a global is perhaps not getting set/reset properly. 

Thanks for reporting. Will check it out shortly.

**Comment by jasonbahl** [comment]
@drewbaker I've been able to verify this locally. Looking into this further now.

**Comment by jasonbahl** [comment]
@drewbaker Got this fixed locally. Running some tests then will have a PR shortly. 😄

**Comment by jasonbahl** [comment]
Ok, so here's a rundown of the issue and what I plan to do to address:

Right now when you query something like: 

```
{
  posts {
    nodes {
         id
         title
         categories {
              nodes {
                  id
                  name
                  children {
                       nodes {
                           id
                           name
                       }
                   }
              }
          }
     }
  }
}
```

I was attempting to pass "state" down from the Post being queried all the way down to the children of the categories being queried, so that when you query the children, you would only get children that were _also_ connected to the Post a few levels higher in the resolve tree. 

My attempt at solving this was to use the `$GLOBALS['post']` and resolve _only_ children that were _also_ connected with the Post being resolved. 

See: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/TermObjectConnectionResolver.php#L134-L136

So, the goal here was that if you queried a post, it's categories (top level by default. . .as in no parent), and the categories children, you would only get top-level categories that the post is assigned to and child categories that the Post is also assigned to. 

It seems reasonable, right?

Well, I've come to the conclusion that my original design was a bit naiive and is actually problematic.

I've spoken with a few folks deep in GraphQL and read a lot more about passing context multiple levels deep, and it turns out my design has some flaws. 

The relationship between Connections shouldn't be deeper than one level. 

What I mean by that, is that the `posts -> categories` connection is a connection between the post(s) and their categories. But the `categories -> children` connection is a connection between the `categories` and their `children`, **NOT** a connection between the `children` and the `post(s)`

So when querying for `children` of a Category, the connections should have info about the `Category` and the `Children`, but should _not_ be aware of the level higher (the post). 

Caching is the biggest reason for this. 

Anytime `Parent Category` is fetched, it should have the same shape regardless of how it was accessed in the Graph. 

For example, if a category has 3 children when queried from the root (`{ categories { nodes { children { name } } } }` it should _also_ have 3 children when queried from within a post ( `{ posts { nodes { categories { nodes { children { name } } } } } }`

Because a Caching client (Apollo, etc) is going to write to the cache for the category with the most recent results, and we'll run into some funky issues if the _same_ category has different children based on the direction we arrived to it from. 

So, I think the solution here is to change the resolvers for Terms queried against posts to return a flat list, instead of _just_ terms with `parent => 0`

So when querying for posts and their categories, instead of getting: 

```
- Post
   - Assigned Parent Term
      - Assigned Child Term
```

We would get

```
- Post
   - Assigned Parent Term
   - Assigned Child Term
```

In the same level. Then if the UI needs to present them in a tree, the UI can do so, because each term can expose its parent. 

----

I hope this makes sense? 

I'll try and have a PR to address shortly. 

If there are questions on this, let me know and I'll try my best to explain better.

**Comment by drewbaker** [comment]
OK I can see why they do this, and how it gets funky when WordPress gets involved. If you return them all as a flat list, how will the parent and child order be presented? 

I guess it doesn't really matter because WordPress doesn't have an order for categories (it's just date or alphabetical I think). But do tags get stored on a post in the order they were assigned to the post, or is the order a date/alphabetical too?

And do you imagine that order will be returned like Parent/Child/Sub-child or is it going to be grouped parent/parent/parent and then child/child/child etc?

**Comment by epeli** [comment]
We hit a similar issue https://github.com/wp-graphql/wp-graphql/issues/905

and sent a failing test for it https://github.com/wp-graphql/wp-graphql/pull/908

I also found a solution that fixes my specific issue:

https://github.com/wp-graphql/wp-graphql/commit/26ea392d5830299b1b951c0198fb6a88278ff4e7

It just moves the global post setup to happen right before the resolver function executes from the Model constructor. This seem to solve issue with nested queries that each need different global post.

Not sure if this is the correct solution as this might be more nuanced than I realise (could not quite follow @jasonbahl's explanation above...)

**Comment by jasonbahl** [comment]
@epeli 

So, a caching client is going to cache an object the same way no matter where in the Graph it is accessed from. 

So, let's say you query Category 1 from the root, and it's children, like so:

```
{
  category( id: 1 ) {
     id
     name
     children {
        nodes {
            id
            name
        }
     }
  }
}
```

And let's say it returned 2 children: `Child 1` and `Child 2`

----

This is going to get cached like something like this: 

`category:1.children: [ child1, child2 ]`

Now, let's say you have _another_ component in your application with a query for a Post, it's categories and the children categories, and the context of the Post is passed down so only the children categories that are assigned to the :

```
{
  post( id: "postWithCategory1" ) {
      id
      title
      categories {
         nodes {
             id
             name
             children {
               nodes {
                 id
                 name
              }
           }
         }
      }
   }
}
```

Assuming the post was assigned to Category1, but only assigned to `Child 1`, the cache for `category:1` would get written to and replaced to look like:

`category:1.children: [ child1 ]`

So, the first component that wanted _all_ categories now appears to have a bug, because the cache it's reading from has been overridden with _just_ the categories associated with a certain post. 

---

I hope that makes some better sense on the issue. 

I'll see if I can work up a quick example using Apollo to better show the issue in action and a possible alternative.

**Comment by epeli** [comment]
🤦 Just realized you where talking about the schema design in general and not the issue at hand. But yeah, that totally makes sense. Do you plan to deprecate the `children` field or make it unaware of the connected post?

Anyway what do you think about this change? https://github.com/wp-graphql/wp-graphql/commit/26ea392d5830299b1b951c0198fb6a88278ff4e7

It seems to fix the immediate issue. I'm pretty sure there are other bugs too that are related to the Model setting up the global post too early. I will try to come up with some tomorrow.

**Comment by jasonbahl** [comment]
> Do you plan to deprecate the children field or make it unaware of the connected post?

The plan is to make it unaware of the connected post. 

The `Category` Type still should have a `children` field, but it's use should be to get children of the category, without added magical connection to a Post. 

Currently, when you query `categories` on a Post, I have the resolver default to `parent => 0` (top level categories), then I had it so you had to query the children. 

I'll change that to _not_ have `parent => 0` by default, so instead you'll get a flat list of all associated terms, whether they are top level or nested.

**Comment by jasonbahl** [comment]
> Anyway what do you think about this change? 26ea392

Ah. . .yes. I like that. I went down a very similar path as well. Open a PR 😄

**Comment by epeli** [comment]
I've updated the test PR I sent earlier with it https://github.com/wp-graphql/wp-graphql/pull/908

**Comment by jasonbahl** [comment]
@drewbaker  #1337 Addresses this (finally!) 

Connections now by default DO NOT set `post_parent => 0` as the default argument (or term parent, comment parent, etc). Instead, even for hierarchical types such as Pages (that can have parent->child relationships) all content will be returned by default at the top level and the client can make use of things such as `node.parentId` to appropriately fold into a hierarchical UI. 

A specific connection, such as `Page->children` explicitly sets the `post_parent => $source->ID` argument to apply to _that_ specific connection. 

Below is an example of how hierarchical data is now returned in a flat list. In the example, we query for Pages, and in response we get a list that includes a Parent Page as well as a Child Page, both at the same level.

![Screen Shot 2020-06-04 at 1 13 00 PM](https://user-images.githubusercontent.com/1260765/83800749-376cb400-a665-11ea-90eb-13c495c726f5.png)

**Query:**

```graphql
{
  pages {
    nodes {
      id
      title
      children {
        nodes {
          id
          uri
        }
      }
    }
  }
}
```

**Results:**

```json
{
  "data": {
    "pages": {
      "nodes": [
        {
          "id": "cG9zdDo2MDI=",
          "title": "Child Page",
          "children": {
            "nodes": []
          }
        },
        {
          "id": "cG9zdDoy",
          "title": "Sample Page",
          "children": {
            "nodes": [
              {
                "id": "cG9zdDo2MDI=",
                "uri": "/sample-page/child-page/"
              }
            ]
          }
        }
      ]
    }
  }
}
```

## Fetching as a hierarchy

If you want to get data in a hierarchical fashion, which is a very valid use case, you can by specifying the parent in the args, like below. In the below example, we specify to query pages with the parent of 0. This will fetch top level pages. We can see now that the page with title "Child Page" is no longer included in the result, just the top level "Sample Page", but, by asking for `children` on "Sample Page" we are able to get the "Child Page" node still. 

![Screen Shot 2020-06-04 at 1 19 08 PM](https://user-images.githubusercontent.com/1260765/83801221-02149600-a666-11ea-980c-002fb134fd96.png)

**Query:**

```graphql
{
  pages {
    nodes {
      id
      title
      children {
        nodes {
          id
          uri
        }
      }
    }
  }
}
```

**Results:**

```json
{
  "data": {
    "pages": {
      "nodes": [
        {
          "id": "cG9zdDoy",
          "title": "Sample Page",
          "children": {
            "nodes": [
              {
                "id": "cG9zdDo2MDI=",
                "uri": "/sample-page/child-page/"
              }
            ]
          }
        }
      ]
    }
  }
}
```
