### ISSUE TITLE
Menu query error when one of pages is in Draft. 

### ISSUE THREAD

**Issue by BartoszLobejko** [wp-graphql/wp-graphql#891]
Hey,

I have below query that lists menu items. Whenever I unpublish any of pages query return undefined data. Weirdly when I use GraphiQL everything is fine... I'm using React.js with react-apollo <Query> Component. Not sure where is the issue, on Wp-graphql or Apollo side. 

Any idea what is wrong? @jasonbahl 

```
fragment MenuItem on MenuItem {
  id
  menuItemId
  connectedObject {
    __typename
    ... on Page {
      uri
      title
      status
    }
  }
}

query MenuQuery($menuId: Int = 3) {
  menus(where: {id: $menuId}) {
    edges {
      node {
        id
        menuId
        count
        name
        slug
        menuItems {
          nodes {
            ...MenuItem
            childItems {
              nodes {
                ...MenuItem
              }
            }
          }
        }
      }
    }
  }
}
```

Also, I couldn't find a way how to filter items by Status.

**Comment by BartoszLobejko** [comment]
Ok, I found where was the problem. 
When you list menu items that are for example page type the connection between menu item and page is lost at the moment you put the page in a draft or private state. 

To solve the issue you need to set error policy to "all" and regardless of errors list menu items with the condition to show only items that are connected to page type not null.  "connectedObject" is basically null when the page is in a draft. 

However, I think that should be solved on wp-graphql level so query doesn't return "internal server error" @jasonbahl @CodeProKid

**Comment by jasonbahl** [comment]
@BartoszLobejko thanks for the added info. 

So, in GraphQL since you can access many resources at once, errors can be returned in addition to the response. 

This is because part of the response may succeed and part may not. 

If you were to do the same request with REST, you’d make a request to get the menu item ids, then make follow up requests to get each item’s connected object, and if one was a draft or private you would also get an error. 

I’ll need to think about this a bit more, but I think the current behavior is largely acceptable. Happy to discuss if you have other ideas on how to
Handle this though.

**Comment by BartoszLobejko** [comment]
@jasonbahl What you're saying and how it works makes sense. It makes sense for the classic "callback hell" REST approach. 

But my personal impression after watching GraphQL documentary https://www.youtube.com/watch?v=783ccP__No8 was that we want to have queries that are "all in one". 

It would make sense for me to "connectedObject" return null or even not returning "connectedObject" while there is also NO error. Or at least if there is error it should be related to user authentication as a Draft and Private pages should be queryable after authentication.   

Those are just my thoughts, I'm also happy with the current setup. Thank you for consideration

**Comment by jasonbahl** [comment]
I’m not saying to have callbacks. What I mean is that if you request resources you don’t have access to (draft/private) in REST, GraphQL or other you will be met with some sort of error. 

I’ll think through this more. I think there’s a happy medium where we can return a null, and a corresponding error so there is some context on why it’s null

**Comment by CodeProKid** [comment]
It would be good to get a clear action item here. Are we doing something to fix this, or is the current functionality what's expected, and we just need better docs?

**Comment by jasonbahl** [comment]
@BartoszLobejko over the past several releases a lot of work has been done to fix how nodes are resolved in regards to permission issues, etc. 

Instead of throwing exceptions and returning errors in the payload when a node is considered private we now return a null instead. 

The query that was returning errors for you above no longer returns errors. 

For example, when I run this query as a logged in user with a Draft page in the menu, I get the following: 

![Screen Shot 2020-06-25 at 10 20 59 AM](https://user-images.githubusercontent.com/1260765/85758455-94401500-b6cd-11ea-9a0e-4112451e030a.png)

There are no errors, and I can see the Draft post. 

If I query as a public, non-authenticated user, I get the following: 

![Screen Shot 2020-06-25 at 9 59 51 AM](https://user-images.githubusercontent.com/1260765/85772736-61e8e480-b6da-11ea-87db-dea91f7349b5.png)

A `null` for the `connectedObject` and no errors. 

I'm thinking there might still be some improvements to how menus are handled. For example, if the `connectedObject` is private, the `menuItem` probably should be as well? Like it does  seem that the menuItem for a draft post shouldn't be returned at all if the connected item can't be returned. 🤔

**Comment by BartoszLobejko** [comment]
I think it would make sense to keep Private menu items as connectedObject: null, just to keep it secure. This way we can easily display the same navigation for different users but with completely different menu items. I think that would be handy.
