### ISSUE TITLE
Support for Gatsby Image

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#920]
At the moment, it's difficult to use Gatsby Image with WPGraphQL. 

This issue is intended to get the conversation going around how to best support Gatsby Image when using WPGraphQL.

**Comment by jerome281** [comment]
Maybe this plugin could help `gatsby-plugin-remote-images` Have been testing this plugin but so far I can't get it to work, I'm struggling to map to the correct node. Anybody else have any other suggestions?

**Comment by gustavpursche** [comment]
@jasonbahl 

You are saying

> At the moment, it's *difficult* to use Gatsby Image with WPGraphQL.

That means you found a way to make it work? Could you explain your current setup for this?

**Comment by jasonbahl** [comment]
@henrikwirth worked up this solution: https://dev.to/nevernull/gatsby-with-wpgraphql-acf-and-gatbsy-image-72m

Would love to hear from folks if this seems like a solid solution?

There's also `gatsby-wpgraphql-inline-images` for the cases when the images are within the content of the post, and not queried as a media item directly. 

Would love to hear more about how folks feel about these solutions or whether there's more room to improve on the WPGraphQL side in some way.

**Comment by henrikwirth** [comment]
I think my solution is a very pragmatic one and should be considered as something easy to apply and use. Especially if you don't have a large scale application.

But, if you do have a big application with lots of MediaItems, I think we have to dig deeper in how to handle caching/syncing the Media-Files. Because if for some reason the cache is cleared, as I understand it with my method, all Media-Files would be pulled in the cache again.

Looking forward to get some other thoughts and ideas on this too :)

**Comment by jasonbahl** [comment]
I'm going to close this issue, as I believe the work needs to happen on the Gatsby side, not the WordPress side, as demonstrated above. 

Another Issue worth keeping an eye on is: https://github.com/gatsbyjs/gatsby/issues/15906

We're exploring a new way to source external GraphQL APIs into Gatsby which will allow us to take advantage of some Gatsby APIs, such as Images and the Node API more natively.

**Comment by samburgers** [comment]
Best solution I have found is here:

https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image

and a clear write up here:

https://dev.to/nevernull/gatsby-with-wpgraphql-acf-and-gatbsy-image-72m
