### ISSUE TITLE
Feature Request: Add homepage display

### ISSUE THREAD

**Issue by gustavpursche** [wp-graphql/wp-graphql#937]
Wordpress allows selecting which homepage should be shown in the "Reading Settings"

<img width="610" alt="Screenshot 2019-08-12 at 15 03 39" src="https://user-images.githubusercontent.com/2244375/62866941-64388f00-bd12-11e9-8612-0522d5e30ae6.png">

This information is missing by the `allSettings` query. Others, like `readingSettingsPostsPerPage` are included. It would be great to have this piece of information available through the API.

❤️

**Comment by jasonbahl** [comment]
Related to #661

**Comment by jasonbahl** [comment]
Some context on why this doesn't exist at the moment:

WordPress core is inconsistent with using the `register_setting` API, and WPGraphQL generates Schema from that API. This field, among others, isn't registered by WordPress core using the `register_setting` API. 

@kidunot89 has done some work toward a patch to support fields like this that exist in WordPress core, but don't use that API. (see: https://github.com/wp-graphql/wp-graphql/pull/661). 

That PR isn't quite ready, as it treats all options as Scalar values, and not an entry into the application data graph. 

For example, the `show_on_front` setting should be exposed as an entry to the Home Page object, not just the scalar value of the homepage ID. 

I think this field would be great to support, but it should be supported as part of an application data graph, where the client can access information deeper in the Graph. 

I'm thinking a setting like this might make more sense to live at the Root of the graph, instead of nested within settings? 

Something like be able to query like so: 

```
{
  homePage {
    ...homePageFields
  }
}
```

To accomplish this, I believe we will need to implement interfaces (see: #672) that Types like a `HomePage` type can implement. 

Something like the below mock implementation should probably work:

```
interface PostObject {
  id: ID!
  title: String
}

type HomePage implements Node, PostObject {
    id: ID!
   title: String
   otherHomePageField: String
}
```

**Comment by jasonbahl** [comment]
Blocked by #672

**Comment by urvish25** [comment]
Is there any way to make dynamic homepage in next.js with wordpress graphql??
