### ISSUE TITLE
Get post_type_object info via \WP_Post_Type_Object class?

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#94]
We should look into getting "post_type_object" data from the `\WP_Post_Type_Object` class instead of using `get_post_type_object` in various spots. 

see: https://github.com/wp-graphql/wp-graphql/search?utf8=%E2%9C%93&q=get_post_type_object

**Comment by CodeProKid** [comment]
@jasonbahl my one questions about this would be; is there upside in using `get_post_type_object()` because of some filters that may be in there? I can see how `\WP_Post_Type_Object` would fit in better with the architecture, but if we are losing functionality / filters that are expected to be there then there's a good reason to keep it the way it is.

**Comment by jasonbahl** [comment]
Hmm. Good call. I'll check it out a bit

**Comment by jasonbahl** [comment]
@codeprokid no filters. I think we're good

**Comment by BE-Webdesign** [comment]
This would be a good change to make, 👍

**Comment by jasonbahl** [comment]
So, I dug into this and it's actually a pretty big PITA because the class is indeed treated differently than the function. I'm going to close this, but if there's a _really_ good argument in favor of opening it back up that can justify the difficulty of the transition, we can discuss and potentially re-open
