### ISSUE TITLE
Previewing posts?

### ISSUE THREAD

**Issue by danielbachhuber** [wp-graphql/wp-graphql#951]
Hi, is there an implementation for previewing posts?

**Comment by jasonbahl** [comment]
@justinwhall has an implementation of a Gatsby site with previews that he's written about here: https://justinwhall.com/live-previews-with-wordpress-gatsby/

**Comment by danielbachhuber** [comment]
Thanks. I don't quite think that will work for my purposes because it requires a nonce. I'll follow up with any additional discovery I have.

**Comment by jasonbahl** [comment]
@danielbachhuber you should be able to do the same with a JWT.

**Comment by danielbachhuber** [comment]
Yep, or even just a simple signed shared secret + custom authentication middleware.

**Comment by justinwhall** [comment]
Curious why you don't have access to a nonce? I've pulled revisions with a JWT token but for my particular needs, the nonce was simpler and doesn't require the user to login twice.

> Yep, or even just a simple signed shared secret + custom authentication middleware.

I like this idea as it could easily be extended.

**Comment by danielbachhuber** [comment]
> Curious why you don't have access to a nonce?

Frontend is on a different domain than the backend.

**Comment by drewbaker** [comment]
@danielbachhuber I've been working on this same thing. We are super close!

**Comment by drewbaker** [comment]
This is our Nuxt plugin if anyone is trying to figure this out. It's just a WIP, but it should show the general direction we were trying to go in.

```
//import Page from '~/gql/queries/Page.gql'
const endpoint = process.env.DEFAULT_ENDPOINT

function fetchGQL (params, nonce = null) {
    return fetch(endpoint, {
        method: `post`,
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
            ...(nonce && { 'X-Wp-Nonce': nonce })
        },
        body: JSON.stringify(params),
        credentials: 'include'
    }).then(function (response) {
        return response.json()
    })
}

const draftsQuery = `query HomePageDrafts($uri: String) {
  pageBy(uri: $uri) {
      title
      childPages(where: {stati: [DRAFT]}) {
          nodes {
              title
          }
      }
  }
}`

export default async (ctx) => {
    const { route, redirect } = ctx
    if (!route.query) {
        return
    }
    if (route.query.wp_token && route.query.uri) {
        redirect(`${route.query.uri}?wp_token=${route.query.wp_token}`)
    } else if (route.query.wp_token) {
        ctx.$wpAuth = { nonce: route.query.wp_token }
        const directResult = await fetchGQL(
            {
                // query: Page.loc.source.body,
                query: draftsQuery,
                variables: {
                    uri: route.path
                }
            },
            route.query.wp_token
        )
        console.log(directResult)
    }
}
```

**Comment by drewbaker** [comment]
Made a lot of progress on this today with @kidunot89, this plugin is the answer: https://github.com/funkhaus/wp-graphql-cors

Working on some better documentation and some examples.

**Comment by jasonbahl** [comment]
@danielbachhuber @drewbaker @TylerBarnes @justinwhall @kidunot89 Ya'll are actively working on previews in some capacity so I wanted to touch base here. 

I just pushed the v0.5.0 release which centers around refactoring how Revisions are being handled. 

It's a breaking change release, as it removes the `Revision` Type in favor of representing revisions in the Schema as the same Type as the parent node. So, a revision of a Page is represented as a Page in the Schema, a revision of a Post is represented as a Post in the Schema, etc. 

Revisions are still passed through the Model Layer, so you do have to be authenticated to view them, but the HUGE win here now is that since the Types are the same, you can actually use the same components to view the final page and the revisions for it! No weird transforms to figure out how to get a `Revision` to show in your components for a `Post` or `Page` and no weird funky ways of trying to figure out how to register fields for Posts to the `Revision` type, etc. 

Check out the release notes here: https://github.com/wp-graphql/wp-graphql/releases/tag/v0.5.0

I'm going to close this issue as I believe this release gets us in a pretty good spot to support rendering previews, generally speaking.

**Comment by drewbaker** [comment]
Thanks for the update Jason.
