### ISSUE TITLE
graphql() function in WordPress breaks Admin Bar

### ISSUE THREAD

**Issue by SimeonGriggs** [wp-graphql/wp-graphql#964]
Latest version of WordPress, WPGraphQL, default theme with no other plugins.

Run any query using the graphql() function and even when successful, the admin bar only contains the WordPress logo and search icons. Everything else (New, Edit, Query Monitor) disappears.

Trying to benchmark WPGraphQL against WP_Query and can't since all the info I need disappears when using the function!

No obvious errors reported with WP_DEBUG on, either.

**Comment by CodeProKid** [comment]
Thanks for the bug report @SimeonGriggs ! Do you have any code snippets we could use to reproduce this? Where are you executing the query? is it within a particular hook that it breaks?

**Comment by SimeonGriggs** [comment]
Even the function from the docs does it:

```
graphql(['query' => ' { generalSettings { url } }']);
```

I used this in the header of the page, not within a hook.

**Comment by jydmnd** [comment]
I found what is causing this. but I'm not sure what is the expected behavior. 

In the _has_authentication_errors()_ method from the _Request_ class, while connected as a user, _$wp_rest_auth_cookie_ will be true, so It will then check for a nonce. The nonce should be null using the Wordpress user login process I believe, so the user will then be set to 0, causing the Admin Bar to render incorrectly since it won't have the necessary permissions. This could cause other problems in rendering a page if user authentification is necessary. 

I believe the _has_authentication_errors()_ method is based from the _rest_cookie_check_errors()_ from the Wordpress REST API.

I'm not sure what is supposed to be going on instead. Are we supposed to get a nonce at this point or is $_wp_rest_auth_cookie_ supposed to be false?

**Comment by jasonbahl** [comment]
@jydmnd ah! Good catch. ya, something looks wrong here. And yes, you are correct that the `has_authentication_errors()` is based on the `rest_cookie_check_errors()`. 

The goal here is to make sure that improper attempts at authentication don't allow GraphQL to properly execute. It seems like we're not doing this quite properly though 🤔

**Comment by saulirajala** [comment]
@jasonbahl Any news on this?

**Comment by jasonbahl** [comment]
@saulirajala thanks for pinging on this. 

I've got a PR to resolve this coming.
