### ISSUE TITLE
Question: Is there a possibility to either get the GraphlQL schema or Mutate / subscribe

### ISSUE THREAD

**Issue by D19cannon** [wp-graphql/wp-graphql#973]
Hi sorry for asking another question so soon.

I've been playing around with Gatsby, WP + Apollo and I am trying to figure out an efficient way to subscribe and mutate (post) data in the WP backend.

The only solutions I can find are usually related using fetch() or axios(). However, I wish to have either to option to send a graphql mutation from the Gatsby or a Node/Apollo server.

As far as I can tell and understand, Gatsby is removing ALL the graphql queries on build including those from Apollo. thus, a mutation query is not possible.

Then I thought it would be nice if Apollo-client & server are hooked up so that the Apollo server would keep track of the WP-graphql schema and run the mutations and subscriptions from there.

Is there a way for me to either create a function in Gatsby that could send a mutation to WP or perhaps a way to get a schema in order to control the graphql queries from the Apollo server?

Thanks! :)

**Comment by jasonbahl** [comment]
@D19cannon It is possible to do mutations from a Gatsby site using Apollo Client and the `<Mutation>` component, or the `useMutation` hook. See: https://www.apollographql.com/docs/react/data/mutations/

In order to use Apollo on the client of a Gatsby site, you can wrap the root element of the Gatsby app with Apollo Client, like so: 

## Import `wrapRootElement` into `gatsby-browser.js`
https://github.com/jlengstorf/gatsby-with-apollo/blob/master/gatsby-browser.js#L1

## Setup ApolloProvider to wrap the element
https://github.com/jlengstorf/gatsby-with-apollo/blob/master/src/apollo/wrap-root-element.js

## Make use of Apollo functions (useQuery in this case)
https://github.com/jlengstorf/gatsby-with-apollo/blob/master/src/pages/index.js#L38

----

@scottopolis makes use of Apollo on the client for comment mutations in his Gatsby Publisher theme. You can explore that codebase here: https://github.com/scottopolis/gatsby-theme-publisher

---

In the case of using WPGraphQL, WordPress and WPGraphQL are your WordPress server, so you _shouldn't_ need to have Apollo server running for anything, unless you have special needs. But WPGraphQL turns your WordPress site into the GraphQL server, so you can use Apollo on the client to talk directly to your WordPress GraphQL API.

**Comment by D19cannon** [comment]
Hi @jasonbahl, 
Sorry for the slow response.

I've been going through the links that you send me and I guess I managed to make some progress after a couple of hours. However, I keep running into interesting problems.

The following error occurs (I have been trying to complete this by following a PDF book about graphql, grapql docs, apollo and the wpgraphql.

I got to a point where I realised that the wpgraphql is offering some functions such as: updatePost in graphql. However, the documentation / examples about it are not working. All it returns is some error (different)

https://docs.wpgraphql.com/getting-started/posts#mutations

<img width="954" alt="Screenshot 2019-10-16 at 17 12 54" src="https://user-images.githubusercontent.com/14916043/66927311-40f2ce80-f038-11e9-9ca5-5f2a956e37dc.png">

```
Error: GraphQL error: Variable "$input" got invalid value {"id":"cG9zdDoxMzMz","title":"daniel"}; Field value.clientMutationId of required type String! was not provided.
```
```
Error: GraphQL error: Variable "$input" of required type "UpdatePostInput!" was not provided..
```

```
const MUTATION = gql`
  mutation UpdateTitle($input: UpdatePostInput!) {
    updatePost(input: $input) {
      post {
        id
        title
      }
    }
  }
`;

const mutationFunction = () => {

  const [mutateTitle, { data }] = useMutation(MUTATION);
  let input;

  return (
    <div>
      <form
        onSubmit={e => {
          e.preventDefault();
          mutateTitle({ variables: { input: { id: "cG9zdDoxMzMz", title: input.value } } });
          mutateTitle({ variables: { id: "cG9zdDoxMzMz", title: input.value } });

          const arg = { variables: { input: { id: "cG9zdDoxMzMz", title: input.value } } }
          const arg = { variables: { id: "cG9zdDoxMzMz", title: input.value } }
          console.log('arg: ', arg)
          mutateTitle(arg);

          input.value = '';
        }}
      >
        <input ref={node => { input = node }} />
        <button type="submit">Update Title</button>
      </form>
    </div>
  )
}


```

Any ideas why this is happening or am I missing something from the documentation?

**Comment by jasonbahl** [comment]
> All it returns is some error (different). I also, tried the filters that are given in graphql, but with no success.

Ya, in the docs, I tried to point out that the examples would fail. Right above is this callout: 

> The demos below are public requests and will not actually mutate data, but you can get an idea of how to compose mutations by looking at the examples.

![Screen Shot 2019-10-17 at 4 07 26 PM](https://user-images.githubusercontent.com/1260765/67051406-3b5cbd80-f0f8-11e9-83c1-c7aabd5b1ef1.png)

----

For mutations, you need authentication. I recommend checking out [WPGraphQL JWT Authentication](https://github.com/wp-graphql/wp-graphql-jwt-authentication)
